"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

const money=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0});
const lim=(n:number|null)=>n==null?"Unlimited":n.toLocaleString();
const INVENTORY_MONTHLY=299;

export default function SubscriptionPage(){
 const [ctx,setCtx]=useState<any>(null),[message,setMessage]=useState(""),[selected,setSelected]=useState(""),[billingCycle,setBillingCycle]=useState<"monthly"|"yearly">("monthly"),[inventoryAddon,setInventoryAddon]=useState(false),[contact,setContact]=useState(""),[email,setEmail]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const payment=new URLSearchParams(location.search).get("payment");if(payment==="success")reconcile();else{load();if(payment==="cancelled")setMessage("Payment was cancelled. No charge was made.")}},[]);
 async function load(){const r=await supabase.rpc("get_my_subscription_portal_context");if(r.error)setMessage(r.error.message);else{const scheduled=r.data.requests?.find((request:any)=>request.request_type==="plan_upgrade"&&request.status==="pending"&&request.payment_method==="paymongo_after_trial");setCtx(r.data);setSelected(scheduled?.requested_plan_key??r.data.subscription.plan_key);setBillingCycle(scheduled?.billing_cycle??r.data.subscription.billing_cycle??"monthly");setInventoryAddon(Boolean(scheduled?.product_inventory_addon));setContact(scheduled?.billing_contact??"");setEmail(scheduled?.billing_email??"");setNotes(scheduled?.notes??"")}}
 async function reconcile(){setBusy(true);setMessage("Verifying your payment with PayMongo…");const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){setBusy(false);setMessage("Please sign in again to verify the payment.");await load();return}try{const response=await fetch("/api/subscriptions/paymongo/reconcile",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const result=await response.json();if(!response.ok&&response.status!==202)throw new Error(result.error||"Unable to verify payment");if(result.status==="activated")setMessage("Payment confirmed. Your subscription is now active.");else if(result.status==="no_pending_payment")setMessage("Your payment has already been processed.");else setMessage("Payment is still processing. Refresh this page in a moment to check again.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to verify payment")}finally{setBusy(false);await load()}}
 async function submit(type:"plan_upgrade"|"trial_extension"){setBusy(true);const r=await supabase.rpc("request_subscription_change_v3",{p_request_type:type,p_plan_key:type==="plan_upgrade"?selected:null,p_extension_days:type==="trial_extension"?7:null,p_billing_contact:contact||null,p_billing_email:email||null,p_payment_method:"manual",p_notes:notes||null,p_billing_cycle:billingCycle,p_product_inventory_addon:inventoryAddon});setBusy(false);setMessage(r.error?r.error.message:type==="plan_upgrade"?"Upgrade request submitted for Platform Admin approval.":"Seven-day trial extension requested.");if(!r.error)await load()}
 async function schedule(){setBusy(true);const r=await supabase.rpc("schedule_subscription_after_trial",{p_plan_key:selected,p_billing_cycle:billingCycle,p_product_inventory_addon:inventoryAddon,p_billing_contact:contact||null,p_billing_email:email||null,p_notes:notes||null});setBusy(false);setMessage(r.error?r.error.message:"Plan saved. No charge will be made until your free trial ends.");if(!r.error)await load()}
 async function pay(){setBusy(true);setMessage("");const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){setBusy(false);setMessage("Please sign in again before starting payment.");return}try{const response=await fetch("/api/subscriptions/paymongo/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({plan_key:selected,billing_cycle:billingCycle,product_inventory_addon:inventoryAddon,billing_contact:contact,billing_email:email,notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to start payment");location.href=result.checkout_url}catch(error){setBusy(false);setMessage(error instanceof Error?error.message:"Unable to start payment")}}
 if(!ctx)return <main className="workspace"><h1>Subscription</h1><p className="notice">{message||"Loading subscription…"}</p></main>;
 const pending=ctx.requests?.filter((r:any)=>r.status==="pending")??[];const scheduled=pending.find((r:any)=>r.request_type==="plan_upgrade"&&r.payment_method==="paymongo_after_trial");const trialEnds=new Date(ctx.subscription.trial_ends_at);const inTrial=ctx.subscription.status==="trialing"&&Date.now()<trialEnds.getTime();const annual=(monthly:number)=>monthly*12*.9;
 return <main className="workspace">
  <header><div><p className="eyebrow">ORGANIZATION SUBSCRIPTION</p><h1>Upgrade LabaFlow</h1><p className="muted">Current plan: {ctx.subscription.plan_name} · Trial ends {trialEnds.toLocaleDateString()}</p></div></header>
  {message&&<p className="notice">{message}</p>}
  <section className="stats"><article><span>Branches</span><strong>{ctx.usage.branches}</strong></article><article><span>Staff</span><strong>{ctx.usage.staff}</strong></article><article><span>Customers</span><strong>{ctx.usage.customers}</strong></article><article><span>Transactions this month</span><strong>{ctx.usage.transactions}</strong></article></section>
  <section className="panel">
   <div className="panelHead"><h2>Choose a Plan</h2><div className="headerActions"><button type="button" className={billingCycle==="monthly"?"primary":"secondary"} onClick={()=>setBillingCycle("monthly")}>Monthly</button><button type="button" className={billingCycle==="yearly"?"primary":"secondary"} onClick={()=>setBillingCycle("yearly")}>Yearly · Save 10%</button></div></div>
   <div className="subscriptionPlanGrid">{ctx.plans.map((p:any)=><button type="button" className={`subscriptionPlanCard ${selected===p.plan_key?"selected":""}`} key={p.plan_key} onClick={()=>setSelected(p.plan_key)}><small>{p.plan_key.toUpperCase()}</small><h3>{p.display_name}</h3><strong>{p.monthly_price==null?"Contact us":billingCycle==="yearly"?`${money.format(annual(Number(p.monthly_price)))}/yr`:`${money.format(p.monthly_price)}/mo`}</strong>{p.monthly_price!=null&&billingCycle==="yearly"&&<span>{money.format(Number(p.monthly_price)*.9)}/mo equivalent · save {money.format(Number(p.monthly_price)*1.2)}</span>}<span>Branches: {lim(p.branch_limit)}</span><span>Staff: {lim(p.staff_limit)}</span><span>Transactions/month: {lim(p.transaction_limit)}</span><span>Customers: {lim(p.customer_limit)}</span></button>)}</div>
   <div className={`subscriptionPlanCard ${inventoryAddon?"selected":""}`}><small>OPTIONAL ADD-ON</small><h3>Product &amp; Inventory</h3><strong>{billingCycle==="yearly"?`${money.format(annual(INVENTORY_MONTHLY))}/yr`:`${money.format(INVENTORY_MONTHLY)}/mo`}</strong>{billingCycle==="yearly"&&<span>{money.format(INVENTORY_MONTHLY*.9)}/mo equivalent · save {money.format(INVENTORY_MONTHLY*1.2)}</span>}<span>Product catalog, branch stock, SKU and product sales</span><label><input type="checkbox" checked={inventoryAddon} onChange={e=>setInventoryAddon(e.target.checked)}/> Add Product &amp; Inventory</label></div>
   <div className="gridForm"><label>Billing Contact<input value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Billing Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="wide">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Payment reference or billing request"/></label></div>
   <div className="panel"><strong>{inTrial?"Choose now, pay after your free trial":"Secure online payment via PayMongo"}</strong><p className="muted">{inTrial?`No charge will be made today. PayMongo checkout becomes available after ${trialEnds.toLocaleDateString()}.`:`${billingCycle==="yearly"?"The discounted annual amount is paid upfront. ":"This payment covers the first monthly billing period. "}Your subscription activates after PayMongo confirms the payment.`}</p>{scheduled&&<p className="muted">Saved plan: {scheduled.requested_plan_key} · {scheduled.billing_cycle}{scheduled.product_inventory_addon?" · Product & Inventory":""}</p>}</div>
   <div className="headerActions"><button className="secondary" disabled={busy||pending.some((r:any)=>r.request_type==="trial_extension")} onClick={()=>submit("trial_extension")}>Request 7-Day Trial Extension</button>{!inTrial&&<button className="secondary" disabled={busy||!selected||pending.some((r:any)=>r.request_type==="plan_upgrade"&&r.payment_method!=="paymongo_after_trial")} onClick={()=>submit("plan_upgrade")}>Request Manual Payment</button>}{inTrial?<button className="primary" disabled={busy||!selected||selected==="enterprise"} onClick={schedule}>{busy?"Saving…":selected==="enterprise"?"Request a Quote":"Save Plan for After Trial"}</button>:<button className="primary" disabled={busy||!selected||selected==="enterprise"||pending.some((r:any)=>r.request_type==="plan_upgrade"&&r.payment_method!=="paymongo_after_trial")} onClick={pay}>{busy?"Starting…":selected==="enterprise"?"Request a Quote":`Pay ${billingCycle==="yearly"?"Annually":"Monthly"}`}</button>}</div>
  </section>
  {ctx.requests?.length>0&&<section className="panel"><h2>Request History</h2>{ctx.requests.map((r:any)=><div className="adminRow" key={r.id}><div><strong>{r.request_type==="plan_upgrade"?`Plan upgrade: ${r.requested_plan_key} · ${r.billing_cycle??"monthly"}${r.product_inventory_addon?" · Product & Inventory":""}`:`Trial extension: ${r.requested_extension_days} days`}</strong><small>{new Date(r.created_at).toLocaleString()}</small></div><span className={`status ${r.status==="approved"?"active":""}`}>{r.status}</span></div>)}</section>}
 </main>
}
