"use client";

import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

type LocalSession={token:string;expires_at:string;staff:{id:string;full_name:string;username:string;role:string};organization:{id:string;name:string;slug:string};branch:{id:string;name:string;code:string}|null};
const key="labaflow.local_staff_session";
export default function StaffLoginPage(){
 const [org,setOrg]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(!raw)return;const saved=JSON.parse(raw) as LocalSession;supabase.rpc("get_local_staff_session",{p_token:saved.token}).then(({data})=>{if(data){localStorage.setItem(key,JSON.stringify(data));location.replace("/dashboard")}else localStorage.removeItem(key)})}catch{localStorage.removeItem(key)}},[]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {data,error}=await supabase.rpc("authenticate_local_staff",{p_organization_slug:org.trim().toLowerCase(),p_username:username.trim().toLowerCase(),p_pin:pin});if(error){setBusy(false);setMessage(error.message);return}const session=data as LocalSession;await supabase.auth.signOut();localStorage.setItem(key,JSON.stringify(session));setBusy(false);location.replace("/dashboard")}
 return <main className="authPage"><section className="brandPanel"><div className="logoMark">LF</div><h1>LabaFlow</h1><p>Quick branch staff access.</p><div className="authBenefits"><span>No email required</span><span>Organization-based account</span><span>Username + PIN</span><span>12-hour local staff session</span></div></section><section className="authCard"><p className="eyebrow">STAFF LOGIN</p><h2>Sign in to your organization</h2><p className="muted">Use the organization code given by your administrator, your username, and your PIN.</p><form className="stack" onSubmit={login}><label>Organization Code<input value={org} onChange={e=>setOrg(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="glenn-wash-and-dry" autoCapitalize="none" required/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,""))} placeholder="maria" autoCapitalize="none" required/></label><label>PIN<input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,8))} minLength={4} maxLength={8} required/></label><button className="primary" disabled={busy}>{busy?"Signing in…":"Staff Sign In"}</button><button type="button" className="secondary" onClick={()=>location.href="/"}>Administrator Login</button></form>{message&&<p className="notice">{message}</p>}</section></main>
}
