"use client";

import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

type LocalSession={token:string;expires_at:string;staff:{id:string;full_name:string;username:string;role:string};organization:{id:string;name:string;slug:string};branch:{id:string;name:string;code:string}|null};
const key="labaflow.local_staff_session";
export default function StaffLoginPage(){
 const [org,setOrg]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[active,setActive]=useState<LocalSession|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(!raw)return;const saved=JSON.parse(raw) as LocalSession;supabase.rpc("get_local_staff_session",{p_token:saved.token}).then(({data})=>{if(data){setActive(data as LocalSession);localStorage.setItem(key,JSON.stringify(data))}else localStorage.removeItem(key)})}catch{localStorage.removeItem(key)}},[]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {data,error}=await supabase.rpc("authenticate_local_staff",{p_organization_slug:org.trim().toLowerCase(),p_username:username.trim().toLowerCase(),p_pin:pin});setBusy(false);if(error){setMessage(error.message);return}const session=data as LocalSession;localStorage.setItem(key,JSON.stringify(session));setActive(session);setPin("")}
 async function logout(){if(active)await supabase.rpc("logout_local_staff",{p_token:active.token});localStorage.removeItem(key);setActive(null)}
 if(active)return <main className="onboarding"><section className="onboardCard"><div className="logoMark">LF</div><p className="eyebrow">LOCAL STAFF SESSION</p><h1>Welcome, {active.staff.full_name}</h1><p className="muted">{active.organization.name}{active.branch?` · ${active.branch.name}`:""}</p><div className="settingsGrid"><div><span>Username</span><strong>@{active.staff.username}</strong></div><div><span>Role</span><strong>{active.staff.role.replaceAll("_"," ")}</strong></div><div><span>Session Expires</span><strong>{new Date(active.expires_at).toLocaleTimeString()}</strong></div></div><p className="notice">Local staff authentication is active. Operational screens are being connected to this local session next; until then, this login should be used for testing account creation and authentication only.</p><button className="secondary" onClick={logout}>End Staff Session</button></section></main>;
 return <main className="authPage"><section className="brandPanel"><div className="logoMark">LF</div><h1>LabaFlow</h1><p>Quick branch staff access.</p><div className="authBenefits"><span>No email required</span><span>Organization-based account</span><span>Username + PIN</span><span>12-hour local staff session</span></div></section><section className="authCard"><p className="eyebrow">STAFF LOGIN</p><h2>Sign in to your organization</h2><p className="muted">Use the organization code given by your administrator, your username, and your PIN.</p><form className="stack" onSubmit={login}><label>Organization Code<input value={org} onChange={e=>setOrg(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} placeholder="glenn-wash-and-dry" autoCapitalize="none" required/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,""))} placeholder="maria" autoCapitalize="none" required/></label><label>PIN<input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,8))} minLength={4} maxLength={8} required/></label><button className="primary" disabled={busy}>{busy?"Signing in…":"Staff Sign In"}</button><button type="button" className="secondary" onClick={()=>location.href="/"}>Administrator Login</button></form>{message&&<p className="notice">{message}</p>}</section></main>
}
