"use client";

import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

type LocalSession={token:string;expires_at:string;staff:{id:string;full_name:string;username:string;role:string};organization:{id:string;name:string;slug:string};branch:{id:string;name:string;code:string}|null};
const key="labaflow.local_staff_session";
const orgKey="labaflow.last_staff_org";
export default function StaffLoginPage(){
 const [org,setOrg]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[confirmPin,setConfirmPin]=useState(""),[setupCode,setSetupCode]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState<"login"|"setup">("login");
 useEffect(()=>{
  const params=new URLSearchParams(location.search);
  const fromUrl=(params.get("org")??"").toLowerCase().replace(/[^a-z0-9-]/g,"");
  const remembered=(localStorage.getItem(orgKey)??"").toLowerCase().replace(/[^a-z0-9-]/g,"");
  if(fromUrl){setOrg(fromUrl);localStorage.setItem(orgKey,fromUrl)}else if(remembered)setOrg(remembered);
  try{const raw=localStorage.getItem(key);if(!raw)return;const saved=JSON.parse(raw) as LocalSession;supabase.rpc("get_local_staff_session",{p_token:saved.token}).then(({data})=>{if(data){localStorage.setItem(key,JSON.stringify(data));location.replace("/dashboard")}else localStorage.removeItem(key)})}catch{localStorage.removeItem(key)}
 },[]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const normalizedOrg=org.trim().toLowerCase();const {data,error}=await supabase.rpc("authenticate_local_staff",{p_organization_slug:normalizedOrg,p_username:username.trim().toLowerCase(),p_pin:pin});if(error){setBusy(false);setMessage(error.message);return}const session=data as LocalSession;await supabase.auth.signOut();localStorage.setItem(key,JSON.stringify(session));localStorage.setItem(orgKey,session.organization.slug||normalizedOrg);setBusy(false);location.replace("/dashboard")}
 async function createPin(e:FormEvent){e.preventDefault();setMessage("");if(pin.length<4||pin.length>8){setMessage("PIN must contain 4 to 8 digits.");return}if(pin!==confirmPin){setMessage("PIN entries do not match.");return}setBusy(true);const normalizedOrg=org.trim().toLowerCase();const {error}=await supabase.rpc("set_local_staff_pin",{p_organization_slug:normalizedOrg,p_username:username.trim().toLowerCase(),p_setup_code:setupCode.trim(),p_new_pin:pin});setBusy(false);if(error){setMessage(error.message);return}localStorage.setItem(orgKey,normalizedOrg);setMessage("Your private PIN is ready. You can now sign in.");setSetupCode("");setConfirmPin("");setMode("login")}
 const numeric=(v:string)=>v.replace(/\D/g,"").slice(0,8);
 return <main className="authPage"><section className="brandPanel"><div className="logoMark">LF</div><h1>LabaFlow</h1><p>Quick branch staff access.</p><div className="authBenefits"><span>No email required</span><span>Organization-based account</span><span>You choose your own private PIN</span><span>12-hour login session</span></div></section><section className="authCard"><p className="eyebrow">STAFF LOGIN</p><h2>{mode==="login"?"Sign in to your organization":"Create your private PIN"}</h2><p className="muted">{mode==="login"?"Use your organization code, username, and PIN.":"Enter the one-time setup code from your administrator, then choose a PIN only you know."}</p><form className="stack" onSubmit={mode==="login"?login:createPin}><label>Organization Code<input value={org} onChange={e=>{const value=e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"");setOrg(value);localStorage.setItem(orgKey,value)}} placeholder="your-organization" autoCapitalize="none" required/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,""))} placeholder="maria" autoCapitalize="none" required/></label>{mode==="setup"&&<label>One-Time Setup Code<input value={setupCode} onChange={e=>setSetupCode(e.target.value.toUpperCase().replace(/[^A-F0-9]/g,"").slice(0,10))} placeholder="Enter setup code" autoCapitalize="characters" required/><small className="muted">This code expires after 24 hours and is only used to create your PIN.</small></label>}<label>{mode==="login"?"PIN":"Choose PIN"}<input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(numeric(e.target.value))} minLength={4} maxLength={8} placeholder="4-8 digits" required/></label>{mode==="setup"&&<label>Confirm PIN<input type="password" inputMode="numeric" value={confirmPin} onChange={e=>setConfirmPin(numeric(e.target.value))} minLength={4} maxLength={8} placeholder="Re-enter PIN" required/><small className="muted">Your administrator cannot see this PIN.</small></label>}<button className="primary" disabled={busy}>{busy?(mode==="login"?"Signing in…":"Creating PIN…"):(mode==="login"?"Staff Sign In":"Create My PIN")}</button><button type="button" className="secondary" onClick={()=>{setMode(mode==="login"?"setup":"login");setMessage("");setPin("");setConfirmPin("")}}>{mode==="login"?"First time? Create my PIN":"Back to Staff Sign In"}</button><button type="button" className="secondary" onClick={()=>location.href="/"}>Administrator Login</button></form>{message&&<p className="notice">{message}</p>}</section></main>
}
