"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
import {getStoredLocalStaffSession} from "../../lib/localStaff";
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function ReceiptPage(){
 const [data,setData]=useState<any>(null),[branding,setBranding]=useState<any>(null),[error,setError]=useState("");const id=typeof window!=="undefined"?new URLSearchParams(location.search).get("id"):null;
 useEffect(()=>{(async()=>{if(!id)return setError("Order ID is missing.");const local=getStoredLocalStaffSession();let result:any;if(local){const r=await supabase.rpc("get_local_staff_order_checkout",{p_token:local.token,p_order_id:id});if(r.error)return setError(r.error.message);result=r.data}else{const [o,i,p]=await Promise.all([supabase.from("laundry_orders").select("id,order_code,status,payment_status,subtotal,discount,total,amount_paid,created_at,notes,customers(full_name,customer_code,loyalty_points),branches(name,address,phone)").eq("id",id).maybeSingle(),supabase.from("laundry_order_items").select("id,quantity,unit_price,line_total,services(name,pricing_unit)").eq("order_id",id).order("created_at"),supabase.from("payments").select("id,amount,method,reference,created_at").eq("order_id",id).order("created_at")]);if(o.error||!o.data)return setError(o.error?.message||"Order not found.");result={order:o.data,items:(i.data??[]).map((x:any)=>({...x,service_name:Array.isArray(x.services)?x.services[0]?.name:x.services?.name})),payments:p.data??[]}}setData(result);const b=await supabase.rpc("get_receipt_branding",{p_order_id:id,p_staff_token:local?.token??null});if(!b.error)setBranding(b.data)})()},[id]);
 if(error)return <main className="center"><section className="onboardCard"><h2>Receipt unavailable</h2><p>{error}</p></section></main>;if(!data)return <main className="center"><div className="loader">Loading receipt…</div></main>;
 const o=data.order,customer=Array.isArray(o.customers)?o.customers[0]:o.customers,branch=Array.isArray(o.branches)?o.branches[0]:o.branches,items=data.items??[],payments=data.payments??[],balance=Math.max(Number(o.total)-Number(o.amount_paid),0),points=Number(customer?.loyalty_points??data.customer?.loyalty_points??0);const business=branding?.organization_name||"LabaFlow",branchName=branding?.branch_name||branch?.name||"",logo=branding?.branch_logo_url||branding?.organization_logo_url||"/labaflow-icon.svg",address=branding?.branch_address||branding?.business_address||branch?.address,phone=branding?.branch_phone||branding?.business_phone||branch?.phone,email=branding?.business_email,website=branding?.business_website,thanks=branding?.receipt_footer||`Thank you for choosing ${business}.`;
 async function share(){const card=document.querySelector<HTMLElement>(".receiptCard");if(!card){window.print();return}window.print()}
 return <main className="receiptPage"><div className="receiptToolbar noPrint"><button onClick={()=>history.back()}>← Back</button><button onClick={share}>↗ Share / Print</button><button onClick={()=>window.print()}>🖨 Print / PDF</button></div><article className="receiptCard"><header><img src={logo} alt={`${business} logo`}/><h1>{business}</h1>{branchName&&branchName!==business&&<p>{branchName}</p>}<small>Laundry Service Receipt</small>{address&&<small>{address}</small>}{phone&&<small>{phone}</small>}{email&&<small>{email}</small>}{website&&<small>{website}</small>}</header><section className="receiptMeta"><div><span>Order</span><b>{o.order_code}</b></div><div><span>Date</span><b>{new Date(o.created_at).toLocaleString()}</b></div><div><span>Customer</span><b>{customer?.full_name||"Walk-in Customer"}</b></div><div><span>Status</span><b>{label(o.status)}</b></div>{customer?.customer_code&&<div><span>Customer Code</span><b>{customer.customer_code}</b></div>}<div><span>Payment</span><b>{balance<=0?"Paid":label(o.payment_status)}</b></div>{customer&&<div><span>Loyalty Points</span><b>{points.toLocaleString()} points</b></div>}</section><section><h2>Services</h2><table><thead><tr><th>Service</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id}><td>{x.service_name||"Service"}</td><td>{x.quantity}</td><td>{peso.format(Number(x.unit_price))}</td><td>{peso.format(Number(x.line_total))}</td></tr>)}</tbody></table><div className="receiptTotals"><div><span>Subtotal</span><b>{peso.format(Number(o.subtotal))}</b></div>{Number(o.discount)>0&&<div><span>Discount</span><b>-{peso.format(Number(o.discount))}</b></div>}<div className="grand"><span>Total</span><b>{peso.format(Number(o.total))}</b></div><div><span>Paid</span><b>{peso.format(Number(o.amount_paid))}</b></div><div><span>Balance</span><b>{peso.format(balance)}</b></div></div></section><section><h2>Payments</h2>{payments.length?<table><tbody>{payments.map((p:any)=><tr key={p.id}><td>{new Date(p.created_at).toLocaleString()}</td><td>{label(p.method)}</td><td>{peso.format(Number(p.amount))}</td></tr>)}</tbody></table>:<p className="muted">No payment recorded yet.</p>}</section><footer><strong>{thanks}</strong><small>Powered by LabaFlow · labaflow.paotechs.com</small></footer></article></main>
}
