"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
import {getStoredLocalStaffSession} from "../../lib/localStaff";
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const round=(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,fill:string)=>{c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill()};
export default function ReceiptPage(){
 const [data,setData]=useState<any>(null),[error,setError]=useState("");
 const id=typeof window!=="undefined"?new URLSearchParams(location.search).get("id"):null;
 useEffect(()=>{(async()=>{if(!id)return setError("Order ID is missing.");const local=getStoredLocalStaffSession();if(local){const {data,error}=await supabase.rpc("get_local_staff_order_checkout",{p_token:local.token,p_order_id:id});if(error)return setError(error.message);setData(data);return}const [o,i,p]=await Promise.all([supabase.from("laundry_orders").select("id,order_code,status,payment_status,subtotal,discount,total,amount_paid,created_at,notes,customers(full_name,customer_code,loyalty_points),branches(name,address)").eq("id",id).maybeSingle(),supabase.from("laundry_order_items").select("id,quantity,unit_price,line_total,services(name,pricing_unit)").eq("order_id",id).order("created_at"),supabase.from("payments").select("id,amount,method,reference,created_at").eq("order_id",id).order("created_at")]);if(o.error||!o.data)return setError(o.error?.message||"Order not found.");setData({order:o.data,items:(i.data??[]).map((x:any)=>({...x,service_name:Array.isArray(x.services)?x.services[0]?.name:x.services?.name,pricing_unit:Array.isArray(x.services)?x.services[0]?.pricing_unit:x.services?.pricing_unit})),payments:p.data??[]})})()},[id]);
 if(error)return <main className="center"><section className="onboardCard"><h2>Receipt unavailable</h2><p>{error}</p></section></main>;if(!data)return <main className="center"><div className="loader">Loading receipt…</div></main>;
 const o=data.order,customer=Array.isArray(o.customers)?o.customers[0]:o.customers,branch=Array.isArray(o.branches)?o.branches[0]:o.branches,items=(data.items??[]),payments=(data.payments??[]),balance=Math.max(Number(o.total)-Number(o.amount_paid),0),points=Number(customer?.loyalty_points??data.customer?.loyalty_points??0);
 async function share(){
  const w=1240,pad=62,metaRows=customer?.customer_code?4:3,servicesH=92+items.length*56,totalsCount=4+(Number(o.discount)>0?1:0),totalsH=totalsCount*52+20,paymentsH=payments.length?70+payments.length*50:110,h=250+metaRows*54+servicesH+totalsH+paymentsH+145;
  const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const c=canvas.getContext("2d");if(!c)return;c.textBaseline="top";c.fillStyle="#eef5f7";c.fillRect(0,0,w,h);round(c,30,20,w-60,h-40,26,"#fff");
  c.textAlign="center";c.fillStyle="#082f49";c.font="700 58px Arial";c.fillText("LabaFlow",w/2,46);c.font="400 28px Arial";c.fillText(branch?.name||"LabaFlow",w/2,112);c.font="400 22px Arial";c.fillStyle="#67808c";c.fillText("Laundry Service Receipt",w/2,151);c.strokeStyle="#91a9b5";c.setLineDash([7,6]);c.beginPath();c.moveTo(30,205);c.lineTo(w-30,205);c.stroke();c.setLineDash([]);
  const meta:any[]=[["Order",o.order_code,"Date",new Date(o.created_at).toLocaleString()],["Customer",customer?.full_name||"Walk-in Customer","Status",label(o.status)]];if(customer?.customer_code)meta.push(["Customer Code",customer.customer_code,"Payment",balance<=0?"Paid":label(o.payment_status)]);else meta.push(["Payment",balance<=0?"Paid":label(o.payment_status),"Loyalty Points",`${points.toLocaleString()} points`]);if(customer?.customer_code)meta.push(["Loyalty Points",`${points.toLocaleString()} points`,"",""]);
  let y=234;for(const r of meta){c.textAlign="left";c.font="400 24px Arial";c.fillStyle="#607985";c.fillText(r[0],pad,y);c.font="700 25px Arial";c.fillStyle="#0b3048";c.fillText(r[1],235,y);if(r[2]){c.font="400 24px Arial";c.fillStyle="#607985";c.fillText(r[2],650,y);c.font="700 25px Arial";c.fillStyle="#0b3048";c.fillText(r[3],842,y)}y+=54}
  c.strokeStyle="#91a9b5";c.setLineDash([7,6]);c.beginPath();c.moveTo(30,y+4);c.lineTo(w-30,y+4);c.stroke();c.setLineDash([]);y+=34;
  c.textAlign="left";c.font="700 34px Arial";c.fillStyle="#092f48";c.fillText("Services",pad,y);y+=56;c.font="700 20px Arial";c.fillText("Service",72,y);c.fillText("Qty",558,y);c.fillText("Rate",818,y);c.textAlign="right";c.fillText("Amount",1170,y);y+=34;c.strokeStyle="#d9e4e9";c.beginPath();c.moveTo(pad,y);c.lineTo(w-pad,y);c.stroke();y+=15;
  for(const it of items){c.textAlign="left";c.font="400 23px Arial";c.fillStyle="#173b50";c.fillText(it.service_name||"Service",72,y);c.fillText(String(it.quantity),582,y);c.fillText(peso.format(Number(it.unit_price)),816,y);c.textAlign="right";c.fillText(peso.format(Number(it.line_total)),1170,y);y+=50;c.strokeStyle="#e7eef1";c.beginPath();c.moveTo(pad,y-8);c.lineTo(w-pad,y-8);c.stroke()}y+=12;
  const totals:any[]=[["Subtotal",peso.format(Number(o.subtotal))]];if(Number(o.discount)>0)totals.push(["Discount",`-${peso.format(Number(o.discount))}`]);totals.push(["Total",peso.format(Number(o.total))],["Paid",peso.format(Number(o.amount_paid))],["Balance",peso.format(balance)]);
  for(const r of totals){const grand=r[0]==="Total",bal=r[0]==="Balance";if(grand){c.strokeStyle="#15394e";c.lineWidth=3;c.beginPath();c.moveTo(pad,y-8);c.lineTo(w-pad,y-8);c.stroke();c.lineWidth=1}c.textAlign="left";c.font=(grand?"700 31px":"400 25px")+" Arial";c.fillStyle="#16384b";c.fillText(r[0],pad,y);c.textAlign="right";c.fillStyle=bal?"#d61f2c":"#16384b";c.fillText(r[1],1170,y);y+=52}y+=18;
  c.textAlign="left";c.font="700 34px Arial";c.fillStyle="#092f48";c.fillText("Payments",pad,y);y+=54;if(payments.length){for(const p of payments){c.font="400 21px Arial";c.fillStyle="#173b50";c.textAlign="left";c.fillText(new Date(p.created_at).toLocaleString(),72,y);c.textAlign="center";c.fillText(label(p.method),820,y);c.textAlign="right";c.fillText(peso.format(Number(p.amount)),1170,y);y+=48;c.strokeStyle="#e7eef1";c.beginPath();c.moveTo(pad,y-8);c.lineTo(w-pad,y-8);c.stroke()}}else{c.font="400 21px Arial";c.fillStyle="#607985";c.fillText("No payment recorded yet.",72,y);y+=48}y+=18;round(c,pad,y,w-pad*2,76,16,"#eaf8f9");c.textAlign="center";c.fillStyle="#0b3a50";c.font="700 27px Arial";c.fillText("Thank you for choosing LabaFlow.",w/2,y+23);
  const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/png",.96));if(!blob)return;const file=new File([blob],`${o.order_code}-receipt.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:`LabaFlow Receipt ${o.order_code}`,files:[file]});return}catch(e:any){if(e?.name==="AbortError")return}}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
 }
 return <main className="receiptPage"><div className="receiptToolbar noPrint"><button onClick={()=>history.back()}>← Back</button><button onClick={share}>↗ Share Image</button><button onClick={()=>window.print()}>🖨 Print / PDF</button></div><article className="receiptCard"><header><img src="/labaflow-icon.svg" alt="LabaFlow"/><h1>LabaFlow</h1><p>{branch?.name||"LabaFlow"}</p><small>Laundry Service Receipt</small></header><section className="receiptMeta"><div><span>Order</span><b>{o.order_code}</b></div><div><span>Date</span><b>{new Date(o.created_at).toLocaleString()}</b></div><div><span>Customer</span><b>{customer?.full_name||"Walk-in Customer"}</b></div><div><span>Status</span><b>{label(o.status)}</b></div>{customer?.customer_code&&<div><span>Customer Code</span><b>{customer.customer_code}</b></div>}<div><span>Payment</span><b>{balance<=0?"Paid":label(o.payment_status)}</b></div>{customer&&<div><span>Loyalty Points</span><b>{points.toLocaleString()} points</b></div>}</section><section><h2>Services</h2><table><thead><tr><th>Service</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id}><td>{x.service_name||"Service"}</td><td>{x.quantity}</td><td>{peso.format(Number(x.unit_price))}</td><td>{peso.format(Number(x.line_total))}</td></tr>)}</tbody></table><div className="receiptTotals"><div><span>Subtotal</span><b>{peso.format(Number(o.subtotal))}</b></div>{Number(o.discount)>0&&<div><span>Discount</span><b>-{peso.format(Number(o.discount))}</b></div>}<div className="grand"><span>Total</span><b>{peso.format(Number(o.total))}</b></div><div><span>Paid</span><b>{peso.format(Number(o.amount_paid))}</b></div><div><span>Balance</span><b>{peso.format(balance)}</b></div></div></section><section><h2>Payments</h2>{payments.length?<table><tbody>{payments.map((p:any)=><tr key={p.id}><td>{new Date(p.created_at).toLocaleString()}</td><td>{label(p.method)}</td><td>{peso.format(Number(p.amount))}</td></tr>)}</tbody></table>:<p className="muted">No payment recorded yet.</p>}</section><footer>Thank you for choosing LabaFlow.</footer></article></main>
}
