"use client";

import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../../../lib/supabase";

type Promo={id:string;code:string;name:string|null;discount_type:"amount"|"percentage";discount_value:number;starts_at:string|null;expires_at:string|null;usage_limit:number|null;usage_count:number;active:boolean};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const fmt=(v:string|null)=>v?new Date(v).toLocaleString():"—";

export default function PromoAdminPage(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState("");
 const [promos,setPromos]=useState<Promo[]>([]);
 const [form,setForm]=useState({code:"",name:"",discount_type:"amount",discount_value:"",starts_at:"",expires_at:"",usage_limit:""});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data,error}=await supabase.from("promo_codes").select("id,code,name,discount_type,discount_value,starts_at,expires_at,usage_limit,usage_count,active").order("created_at",{ascending:false});if(error)setMessage(error.message);else setPromos((data??[]).map((p:any)=>({...p,discount_value:Number(p.discount_value)})))}
 async function createPromo(){const {error}=await supabase.rpc("create_promo_code",{p_code:form.code,p_name:form.name||null,p_discount_type:form.discount_type,p_discount_value:Number(form.discount_value),p_starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,p_expires_at:form.expires_at?new Date(form.expires_at).toISOString():null,p_usage_limit:form.usage_limit?Number(form.usage_limit):null});if(error)setMessage(error.message);else{setForm({code:"",name:"",discount_type:"amount",discount_value:"",starts_at:"",expires_at:"",usage_limit:""});setMessage("Promo code created.");await load()}}
 async function toggle(p:Promo){const {error}=await supabase.rpc("set_promo_code_active",{p_promo_id:p.id,p_active:!p.active});if(error)setMessage(error.message);else await load()}
 if(checking)return <main className="center"><div className="loader">Loading promo codes…</div></main>;
 if(!session)return <main className="center"><section className="onboardCard"><h2>Sign in required</h2><button className="primary" onClick={()=>location.href="/organization"}>Organization Login</button></section></main>;
 return <main className="workspace"><div className="panelHead"><div><p className="eyebrow">ORGANIZATION ADMINISTRATION</p><h1>Promo Codes</h1><p className="muted">Create fixed-amount or percentage promos with schedules and usage limits.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/organization"}>Organization Admin</button><button className="secondary" onClick={()=>location.href="/"}>LabaFlow</button></div></div>{message&&<p className="notice">{message}</p>}
 <section className="panel"><h2>New Promo Code</h2><div className="gridForm"><label>Promo Code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/\s+/g,"")})} placeholder="WELCOME10"/></label><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Welcome Promo"/></label><label>Discount Type<select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="amount">Fixed Amount</option><option value="percentage">Percentage</option></select></label><label>{form.discount_type==="percentage"?"Percentage (%)":"Amount (₱)"}<input type="number" min="0.01" max={form.discount_type==="percentage"?100:undefined} step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></label><label>Start Date<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Expiration Date<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label><label>Promo Use Limit<input type="number" min="1" value={form.usage_limit} onChange={e=>setForm({...form,usage_limit:e.target.value})} placeholder="Unlimited if blank"/></label><button className="primary" type="button" onClick={createPromo}>Create Promo Code</button></div></section>
 <section className="panel"><div className="panelHead"><h2>Promo Codes</h2><span>{promos.length} configured</span></div>{promos.length===0?<p className="empty">No promo codes yet.</p>:promos.map(p=><div className="adminRow" key={p.id}><div><strong>{p.code}{p.name?` · ${p.name}`:""}</strong><small>{p.discount_type==="percentage"?`${p.discount_value}% off`:`${peso.format(p.discount_value)} off`} · Starts {fmt(p.starts_at)} · Expires {fmt(p.expires_at)} · Used {p.usage_count}{p.usage_limit?` / ${p.usage_limit}`:" / unlimited"}</small></div><span className={p.active?"status active":"status inactive"}>{p.active?"Active":"Inactive"}</span><button className="miniBtn" onClick={()=>toggle(p)}>{p.active?"Disable":"Enable"}</button></div>)}</section></main>;
}
