"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

type GCashSettings={integration_type:"manual_qr"|"gateway";merchant_name:string;account_number:string;qr_image_url:string;instructions:string;active:boolean};
const empty:GCashSettings={integration_type:"manual_qr",merchant_name:"",account_number:"",qr_image_url:"",instructions:"Scan the QR using GCash and show the successful payment confirmation to the cashier.",active:true};

export default function OrganizationPaymentsPage(){
 const [settings,setSettings]=useState<GCashSettings>(empty),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{load()},[]);
 async function load(){const {data,error}=await supabase.rpc("get_organization_payment_account",{p_payment_method:"gcash"});if(error){setMessage(error.message);return}if(data)setSettings({integration_type:data.integration_type??"manual_qr",merchant_name:data.merchant_name??"",account_number:data.account_number??"",qr_image_url:data.qr_image_url??"",instructions:data.instructions??"",active:data.active!==false})}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const {error}=await supabase.rpc("save_organization_gcash_settings",{p_integration_type:settings.integration_type,p_merchant_name:settings.merchant_name,p_account_number:settings.account_number,p_qr_image_url:settings.qr_image_url,p_instructions:settings.instructions,p_active:settings.active});setSaving(false);setMessage(error?error.message:"GCash settings saved for this organization.")}
 return <main className="workspace"><header><div><p className="eyebrow">PAYMENT SETTINGS</p><h1>GCash</h1><p className="muted">Configure this organization's own GCash merchant account. Payments are never shared with another LabaFlow organization.</p></div></header>{message&&<p className="notice">{message}</p>}<section className="panel"><div className="panelHead"><div><h2>GCash Account</h2><span>Phase 1 uses your merchant QR with cashier confirmation. Automatic confirmation can be enabled later through a connected gateway.</span></div><button className="miniBtn" onClick={()=>setSettings(x=>({...x,active:!x.active}))}>{settings.active?"Enabled":"Disabled"}</button></div><form className="stack" onSubmit={save}><label>Integration Type<select value={settings.integration_type} onChange={e=>setSettings({...settings,integration_type:e.target.value as GCashSettings["integration_type"]})}><option value="manual_qr">Manual QR</option><option value="gateway" disabled>Payment Gateway — coming next</option></select></label><div className="gridForm"><label>Merchant / Business Name<input value={settings.merchant_name} onChange={e=>setSettings({...settings,merchant_name:e.target.value})} placeholder="ABC Laundry"/></label><label>GCash Number<input value={settings.account_number} onChange={e=>setSettings({...settings,account_number:e.target.value})} placeholder="09XX XXX XXXX"/></label></div><label>QR Image URL<input value={settings.qr_image_url} onChange={e=>setSettings({...settings,qr_image_url:e.target.value})} placeholder="https://..."/></label>{settings.qr_image_url&&<div className="customerCard"><img src={settings.qr_image_url} alt="Organization GCash QR" style={{maxWidth:280}}/><strong>{settings.merchant_name||"GCash Merchant"}</strong><span>{settings.account_number}</span></div>}<label>Payment Instructions<textarea value={settings.instructions} onChange={e=>setSettings({...settings,instructions:e.target.value})}/></label><button className="primary" disabled={saving}>{saving?"Saving…":"Save GCash Settings"}</button></form></section><section className="panel"><h2>Automatic Payment Confirmation</h2><p className="muted">The data model is gateway-ready, but automatic confirmation stays disabled until a payment provider is connected securely through a server-side integration. Provider secret keys will not be stored in the browser.</p></section></main>
}
