"use client";

import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

type Branch={id:string;name:string;code:string};
type Staff={id:string;full_name:string;username:string;role:string;branch_id:string|null;branch_name:string|null;active:boolean;last_login_at:string|null;created_at:string;pin_configured?:boolean};
type AdminContext={organization?:{id:string;name:string;slug:string}|null;branches?:Branch[]};
const roles=["manager","cashier","laundry_staff","delivery_staff","auditor"];
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function LocalStaffPage(){
 const [staff,setStaff]=useState<Staff[]>([]),[branches,setBranches]=useState<Branch[]>([]),[organizationCode,setOrganizationCode]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[setupCode,setSetupCode]=useState("");
 const [form,setForm]=useState({full_name:"",username:"",role:"cashier",branch_id:""});
 useEffect(()=>{void load()},[]);
 async function load(){setMessage("");const [s,c]=await Promise.all([supabase.rpc("get_local_staff_accounts"),supabase.rpc("get_organization_admin_context")]);if(s.error){setMessage(s.error.message);return}if(c.error){setMessage(c.error.message);return}setStaff((s.data??[]) as Staff[]);const ctx=(c.data??{}) as AdminContext;setBranches(ctx.branches??[]);setOrganizationCode(ctx.organization?.slug??"")}
 async function create(){if(!form.full_name.trim()||!form.username.trim()){setMessage("Name and username are required.");return}setBusy(true);setSetupCode("");const {data,error}=await supabase.rpc("create_local_staff_account_v2",{p_full_name:form.full_name.trim(),p_username:form.username.trim(),p_role:form.role,p_branch_id:form.branch_id||null});setBusy(false);if(error){setMessage(error.message);return}setForm({full_name:"",username:"",role:"cashier",branch_id:""});setSetupCode(data?.setup_code??"");setMessage("Staff account created. Give the staff member the one-time setup code below. They will create their own private PIN.");await load()}
 async function toggle(s:Staff){const {error}=await supabase.rpc("update_local_staff_account",{p_staff_id:s.id,p_full_name:s.full_name,p_role:s.role,p_branch_id:s.branch_id,p_active:!s.active,p_new_pin:null});if(error)setMessage(error.message);else await load()}
 async function resetPin(s:Staff){const {data,error}=await supabase.rpc("issue_local_staff_pin_setup_code",{p_staff_id:s.id});if(error){setMessage(error.message);return}setSetupCode(data?.setup_code??"");setMessage(`A new one-time PIN setup code was issued for ${s.full_name}. Their current sessions were revoked.`);await load()}
 function openStaffLogin(){const suffix=organizationCode?`?org=${encodeURIComponent(organizationCode)}`:"";window.open(`/staff-login${suffix}`,"_blank","noopener,noreferrer")}
 return <main className="workspace"><header><div><p className="eyebrow">ORGANIZATION ADMINISTRATION</p><h1>Local Staff Access</h1><p className="muted">Create branch staff accounts without knowing their PIN. Staff securely create their own PIN using a one-time setup code.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/organization"}>Organization Admin</button></div></header>{message&&<p className="notice">{message}</p>}{setupCode&&<section className="panel"><h2>One-Time Staff Setup Code</h2><p className="muted">Share this code privately with the staff member. It expires after 24 hours and can only be used to create their PIN.</p><p style={{fontSize:28,fontWeight:900,letterSpacing:3}}><code>{setupCode}</code></p><button className="secondary" onClick={()=>navigator.clipboard?.writeText(setupCode)}>Copy Setup Code</button></section>}
 <section className="panel"><h2>Add Local Staff</h2><div className="gridForm"><label>Full Name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="Maria Santos"/></label><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,"")})} placeholder="maria"/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label>Branch<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">All / unassigned</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary wide" disabled={busy} onClick={create}>{busy?"Creating…":"Create Local Staff Account"}</button></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Local Staff</h2><span>{staff.length} account{staff.length===1?"":"s"}</span></div></div>{staff.length===0?<p className="muted">No local staff accounts yet.</p>:staff.map(s=><div className="adminRow" key={s.id}><div><strong>{s.full_name}</strong><small>@{s.username} · {label(s.role)}{s.branch_name?` · ${s.branch_name}`:" · All / unassigned"}{s.last_login_at?` · Last login ${new Date(s.last_login_at).toLocaleString()}`:""}</small></div><span className={s.pin_configured?"status active":"status"}>{s.pin_configured?"PIN Ready":"Setup Required"}</span><div className="actions"><button className="miniBtn" onClick={()=>resetPin(s)}>{s.pin_configured?"Reset PIN Access":"New Setup Code"}</button><button className="miniBtn" onClick={()=>toggle(s)}>{s.active?"Deactivate":"Activate"}</button></div></div>)}</section>
 <section className="panel"><h2>How Staff Will Sign In</h2><p className="muted">The administrator creates the staff account and gives the staff member a one-time setup code. The staff member opens Staff Login, chooses “Create my PIN,” enters that code, and creates a private 4–8 digit PIN. Administrators never see or set the PIN.</p>{organizationCode&&<p><strong>Organization Code:</strong> <code>{organizationCode}</code></p>}<button className="secondary" onClick={openStaffLogin}>Open Staff Login</button></section></main>
}
