"use client";

import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

type Branch={id:string;name:string;code:string};
type Staff={id:string;full_name:string;username:string;role:string;branch_id:string|null;branch_name:string|null;active:boolean;last_login_at:string|null;created_at:string};
const roles=["manager","cashier","laundry_staff","delivery_staff","auditor"];
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function LocalStaffPage(){
 const [staff,setStaff]=useState<Staff[]>([]),[branches,setBranches]=useState<Branch[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({full_name:"",username:"",pin:"",role:"cashier",branch_id:""});
 useEffect(()=>{void load()},[]);
 async function load(){setMessage("");const [s,c]=await Promise.all([supabase.rpc("get_local_staff_accounts"),supabase.rpc("get_organization_admin_context")]);if(s.error){setMessage(s.error.message);return}if(c.error){setMessage(c.error.message);return}setStaff((s.data??[]) as Staff[]);setBranches((c.data?.branches??[]) as Branch[])}
 async function create(){if(!form.full_name.trim()||!form.username.trim()||!form.pin){setMessage("Name, username, and PIN are required.");return}setBusy(true);const {error}=await supabase.rpc("create_local_staff_account",{p_full_name:form.full_name.trim(),p_username:form.username.trim(),p_pin:form.pin,p_role:form.role,p_branch_id:form.branch_id||null});setBusy(false);if(error){setMessage(error.message);return}setForm({full_name:"",username:"",pin:"",role:"cashier",branch_id:""});setMessage("Local staff account created. This user does not need a Supabase account or email invitation.");await load()}
 async function toggle(s:Staff){const {error}=await supabase.rpc("update_local_staff_account",{p_staff_id:s.id,p_full_name:s.full_name,p_role:s.role,p_branch_id:s.branch_id,p_active:!s.active,p_new_pin:null});if(error)setMessage(error.message);else await load()}
 async function resetPin(s:Staff){const pin=window.prompt(`Enter a new 4-8 digit PIN for ${s.full_name}:`);if(pin===null)return;const {error}=await supabase.rpc("update_local_staff_account",{p_staff_id:s.id,p_full_name:s.full_name,p_role:s.role,p_branch_id:s.branch_id,p_active:s.active,p_new_pin:pin});setMessage(error?error.message:"PIN updated.");if(!error)await load()}
 return <main className="workspace"><header><div><p className="eyebrow">ORGANIZATION ADMINISTRATION</p><h1>Local Staff Access</h1><p className="muted">Create branch staff accounts that live inside your LabaFlow organization. No email address or Supabase Auth user is required.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/organization"}>Organization Admin</button></div></header>{message&&<p className="notice">{message}</p>}
 <section className="panel"><h2>Add Local Staff</h2><div className="gridForm"><label>Full Name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="Maria Santos"/></label><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,"")})} placeholder="maria"/></label><label>PIN<input type="password" inputMode="numeric" maxLength={8} value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,"").slice(0,8)})} placeholder="4-8 digits"/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label>Branch<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})}><option value="">All / unassigned</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary wide" disabled={busy} onClick={create}>{busy?"Creating…":"Create Local Staff Account"}</button></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Local Staff</h2><span>{staff.length} account{staff.length===1?"":"s"}</span></div></div>{staff.length===0?<p className="muted">No local staff accounts yet.</p>:staff.map(s=><div className="adminRow" key={s.id}><div><strong>{s.full_name}</strong><small>@{s.username} · {label(s.role)}{s.branch_name?` · ${s.branch_name}`:" · All / unassigned"}{s.last_login_at?` · Last login ${new Date(s.last_login_at).toLocaleString()}`:""}</small></div><span className={s.active?"status active":"status inactive"}>{s.active?"Active":"Inactive"}</span><div className="actions"><button className="miniBtn" onClick={()=>resetPin(s)}>Reset PIN</button><button className="miniBtn" onClick={()=>toggle(s)}>{s.active?"Deactivate":"Activate"}</button></div></div>)}</section>
 <section className="panel"><h2>How Staff Will Sign In</h2><p className="muted">Local staff will use the organization code, username, and PIN from the Staff Login screen. Their PIN is stored as a one-way hash. Local staff sessions expire automatically after 12 hours.</p><button className="secondary" onClick={()=>location.href="/staff-login"}>Open Staff Login</button></section></main>
}
