"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";

type Branch={id:string;name:string;code:string};
type Customer={id:string;full_name:string;customer_code:string;mobile:string|null};
type Order={id:string;order_code:string;customer_id:string|null;status:string};
type Address={id:string;customer_id:string;label:string;address_line:string;barangay:string|null;city:string|null;province:string|null;postal_code:string|null;landmark:string|null;is_default:boolean};
type Driver={user_id:string;name:string;email:string;role:string};
type Job={id:string;branch_id:string;customer_id:string;order_id:string|null;address_id:string;job_type:"pickup"|"delivery";status:string;scheduled_at:string;delivery_fee:number;assigned_to:string|null;contact_name:string|null;contact_mobile:string|null;notes:string|null;customers?:{full_name:string;customer_code:string}|null;customer_addresses?:{label:string;address_line:string;barangay:string|null;city:string|null;province:string|null}|null;laundry_orders?:{order_code:string}|null;profiles?:{full_name:string|null;email:string}|null};
type Access={role?:string;branches?:Branch[];features?:Record<string,boolean>;permissions?:{create_orders:boolean;delivery_access:boolean;view_reports:boolean;manage_customers:boolean}};

const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const pickupStatuses=["scheduled","assigned","en_route","arrived","picked_up","cancelled"];
const deliveryStatuses=["scheduled","assigned","en_route","arrived","out_for_delivery","delivered","cancelled"];

export default function PickupDeliveryPage(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState("");
 const [access,setAccess]=useState<Access>({}),[customers,setCustomers]=useState<Customer[]>([]),[orders,setOrders]=useState<Order[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[jobs,setJobs]=useState<Job[]>([]),[drivers,setDrivers]=useState<Driver[]>([]);
 const [showAddress,setShowAddress]=useState(false),[showJob,setShowJob]=useState(false);
 const [branchId,setBranchId]=useState(""),[customerId,setCustomerId]=useState("");
 const [addressForm,setAddressForm]=useState({customer_id:"",label:"Home",address_line:"",barangay:"",city:"Tagbilaran City",province:"Bohol",postal_code:"",landmark:"",is_default:true});
 const [jobForm,setJobForm]=useState({customer_id:"",order_id:"",address_id:"",job_type:"pickup",scheduled_at:"",delivery_fee:"0",assigned_to:"",contact_name:"",contact_mobile:"",notes:""});

 const branches=access.branches??[];
 const permissions=access.permissions??{create_orders:false,delivery_access:false,view_reports:false,manage_customers:false};
 const featureEnabled=access.features?.pickup_delivery!==false;
 const canCreate=permissions.create_orders||permissions.delivery_access;

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadBase()},[session]);
 useEffect(()=>{if(branchId){loadDrivers(branchId);loadJobs()}},[branchId]);
 useEffect(()=>{if(customerId)loadCustomerAddresses(customerId)},[customerId]);

 async function loadBase(){
   setMessage("");
   const {data,error}=await supabase.rpc("get_current_access_context");
   if(error){setMessage(error.message);return}
   const a=(data??{}) as Access;setAccess(a);const first=a.branches?.[0]?.id??"";setBranchId(first);
   const [c,o]=await Promise.all([
     supabase.from("customers").select("id,full_name,customer_code,mobile").eq("active",true).order("full_name"),
     supabase.from("laundry_orders").select("id,order_code,customer_id,status").order("created_at",{ascending:false}).limit(200)
   ]);
   if(c.error||o.error){setMessage(c.error?.message||o.error?.message||"");return}
   setCustomers((c.data??[]) as Customer[]);setOrders((o.data??[]) as Order[]);
 }
 async function loadCustomerAddresses(id:string){const {data,error}=await supabase.from("customer_addresses").select("id,customer_id,label,address_line,barangay,city,province,postal_code,landmark,is_default").eq("customer_id",id).eq("active",true).order("is_default",{ascending:false});if(error)setMessage(error.message);else setAddresses((data??[]) as Address[])}
 async function loadDrivers(id:string){const {data,error}=await supabase.rpc("get_delivery_staff",{p_branch_id:id});if(error)setMessage(error.message);else setDrivers((data??[]) as Driver[])}
 async function loadJobs(){const {data,error}=await supabase.from("delivery_jobs").select("id,branch_id,customer_id,order_id,address_id,job_type,status,scheduled_at,delivery_fee,assigned_to,contact_name,contact_mobile,notes,customers(full_name,customer_code),customer_addresses(label,address_line,barangay,city,province),laundry_orders(order_code),profiles:assigned_to(full_name,email)").order("scheduled_at",{ascending:true}).limit(200);if(error)setMessage(error.message);else setJobs((data??[]).map((x:any)=>({...x,delivery_fee:Number(x.delivery_fee)})) as Job[])}

 async function createAddress(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("create_customer_address",{p_customer_id:addressForm.customer_id,p_label:addressForm.label,p_address_line:addressForm.address_line,p_barangay:addressForm.barangay||null,p_city:addressForm.city||null,p_province:addressForm.province||null,p_postal_code:addressForm.postal_code||null,p_landmark:addressForm.landmark||null,p_is_default:addressForm.is_default});if(error){setMessage(error.message);return}setShowAddress(false);setCustomerId(addressForm.customer_id);setJobForm(j=>({...j,customer_id:addressForm.customer_id}));await loadCustomerAddresses(addressForm.customer_id);setMessage("Customer address saved.")}
 async function createJob(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("create_delivery_job",{p_branch_id:branchId,p_customer_id:jobForm.customer_id,p_order_id:jobForm.order_id||null,p_address_id:jobForm.address_id,p_job_type:jobForm.job_type,p_scheduled_at:new Date(jobForm.scheduled_at).toISOString(),p_delivery_fee:Number(jobForm.delivery_fee)||0,p_assigned_to:jobForm.assigned_to||null,p_contact_name:jobForm.contact_name||null,p_contact_mobile:jobForm.contact_mobile||null,p_notes:jobForm.notes||null});if(error){setMessage(error.message);return}setShowJob(false);setJobForm({customer_id:"",order_id:"",address_id:"",job_type:"pickup",scheduled_at:"",delivery_fee:"0",assigned_to:"",contact_name:"",contact_mobile:"",notes:""});setCustomerId("");await loadJobs();setMessage("Pickup / delivery job created.")}
 async function assignJob(job:Job,userId:string){const {error}=await supabase.rpc("assign_delivery_job",{p_job_id:job.id,p_assigned_to:userId});if(error)setMessage(error.message);else await loadJobs()}
 async function updateStatus(job:Job,status:string){const {error}=await supabase.rpc("update_delivery_job_status",{p_job_id:job.id,p_status:status,p_notes:null});if(error)setMessage(error.message);else{await loadJobs();setMessage(`${job.job_type==="pickup"?"Pickup":"Delivery"} marked ${label(status)}.`)}}

 const filteredOrders=useMemo(()=>orders.filter(o=>!jobForm.customer_id||o.customer_id===jobForm.customer_id),[orders,jobForm.customer_id]);
 const filteredAddresses=useMemo(()=>addresses.filter(a=>!jobForm.customer_id||a.customer_id===jobForm.customer_id),[addresses,jobForm.customer_id]);

 if(checking)return <main className="center"><div className="loader">Loading Pickup & Delivery…</div></main>;
 if(!session)return <main className="center"><section className="onboardCard"><h2>Sign in required</h2><p className="muted">Return to LabaFlow and sign in first.</p><button className="primary" onClick={()=>location.href="/"}>Back to LabaFlow</button></section></main>;
 if(!featureEnabled)return <main className="center"><section className="onboardCard"><h2>Pickup & Delivery is disabled</h2><p className="muted">Enable this module in Organization Administration → Feature Controls.</p><button className="primary" onClick={()=>location.href="/organization"}>Organization Administration</button></section></main>;

 return <main className="workspace"><div className="panelHead"><div><p className="eyebrow">OPERATIONS</p><h1>Pickup & Delivery</h1><p className="muted">Schedule customer pickups and deliveries, assign drivers, and track each trip.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/"}>LabaFlow</button>{canCreate&&<button className="secondary" onClick={()=>setShowAddress(true)}>+ Address</button>}{canCreate&&<button className="primary" onClick={()=>setShowJob(true)}>+ Pickup / Delivery</button>}</div></div>{message&&<p className="notice">{message}</p>}

 <section className="stats"><article><span>Scheduled</span><strong>{jobs.filter(j=>j.status==="scheduled"||j.status==="assigned").length}</strong></article><article><span>In Transit</span><strong>{jobs.filter(j=>["en_route","arrived","out_for_delivery"].includes(j.status)).length}</strong></article><article><span>Completed</span><strong>{jobs.filter(j=>["picked_up","delivered"].includes(j.status)).length}</strong></article><article><span>Delivery Fees</span><strong>{peso.format(jobs.reduce((n,j)=>n+j.delivery_fee,0))}</strong></article></section>

 <section className="panel"><div className="panelHead"><div><h2>Dispatch Board</h2><small>{jobs.length} jobs</small></div><label style={{minWidth:220}}>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><div className="orderList">{jobs.map(job=>{const statuses=job.job_type==="pickup"?pickupStatuses:deliveryStatuses;return <article className="orderCard" key={job.id}><div className="orderTop"><div><strong>{job.job_type==="pickup"?"Pickup":"Delivery"} · {job.customers?.full_name??"Customer"}</strong><small>{job.laundry_orders?.order_code?`${job.laundry_orders.order_code} · `:""}{new Date(job.scheduled_at).toLocaleString()}</small></div><div><span className={`status ${job.status}`}>{label(job.status)}</span><b>{peso.format(job.delivery_fee)}</b></div></div><div className="orderMeta"><span>{job.customer_addresses?.label??"Address"}: <b>{job.customer_addresses?.address_line}</b></span><span>{[job.customer_addresses?.barangay,job.customer_addresses?.city,job.customer_addresses?.province].filter(Boolean).join(", ")}</span><span>Driver: <b>{job.profiles?.full_name||job.profiles?.email||"Unassigned"}</b></span></div><div className="orderActions">{permissions.delivery_access&&<select value={job.assigned_to??""} onChange={e=>e.target.value&&assignJob(job,e.target.value)}><option value="">Assign driver</option>{drivers.map(d=><option key={d.user_id} value={d.user_id}>{d.name} · {label(d.role)}</option>)}</select>}{permissions.delivery_access&&<select value={job.status} onChange={e=>updateStatus(job,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select>}</div></article>})}{!jobs.length&&<p className="empty">No pickup or delivery jobs yet.</p>}</div></section>

 {showAddress&&<div className="modalBackdrop"><section className="modal"><div className="panelHead"><h2>Add Customer Address</h2><button className="iconBtn" onClick={()=>setShowAddress(false)}>×</button></div><form onSubmit={createAddress} className="gridForm"><label>Customer<select value={addressForm.customer_id} onChange={e=>setAddressForm({...addressForm,customer_id:e.target.value})} required><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name} — {c.customer_code}</option>)}</select></label><label>Label<input value={addressForm.label} onChange={e=>setAddressForm({...addressForm,label:e.target.value})} placeholder="Home / Office"/></label><label className="wide">Address<input value={addressForm.address_line} onChange={e=>setAddressForm({...addressForm,address_line:e.target.value})} required/></label><label>Barangay<input value={addressForm.barangay} onChange={e=>setAddressForm({...addressForm,barangay:e.target.value})}/></label><label>City<input value={addressForm.city} onChange={e=>setAddressForm({...addressForm,city:e.target.value})}/></label><label>Province<input value={addressForm.province} onChange={e=>setAddressForm({...addressForm,province:e.target.value})}/></label><label>Postal code<input value={addressForm.postal_code} onChange={e=>setAddressForm({...addressForm,postal_code:e.target.value})}/></label><label className="wide">Landmark / Instructions<input value={addressForm.landmark} onChange={e=>setAddressForm({...addressForm,landmark:e.target.value})}/></label><label className="wide"><input type="checkbox" style={{width:"auto"}} checked={addressForm.is_default} onChange={e=>setAddressForm({...addressForm,is_default:e.target.checked})}/> Set as default address</label><button className="primary wide">Save Address</button></form></section></div>}

 {showJob&&<div className="modalBackdrop"><section className="modal"><div className="panelHead"><h2>Schedule Pickup / Delivery</h2><button className="iconBtn" onClick={()=>setShowJob(false)}>×</button></div><form onSubmit={createJob} className="gridForm"><label>Type<select value={jobForm.job_type} onChange={e=>setJobForm({...jobForm,job_type:e.target.value})}><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></label><label>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)} required>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Customer<select value={jobForm.customer_id} onChange={async e=>{const id=e.target.value;setJobForm({...jobForm,customer_id:id,address_id:"",order_id:""});setCustomerId(id);if(id)await loadCustomerAddresses(id)}} required><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name} — {c.customer_code}</option>)}</select></label><label>Order<select value={jobForm.order_id} onChange={e=>setJobForm({...jobForm,order_id:e.target.value})}><option value="">No linked order</option>{filteredOrders.map(o=><option key={o.id} value={o.id}>{o.order_code} · {label(o.status)}</option>)}</select></label><label className="wide">Address<select value={jobForm.address_id} onChange={e=>setJobForm({...jobForm,address_id:e.target.value})} required><option value="">Select address</option>{filteredAddresses.map(a=><option key={a.id} value={a.id}>{a.label} — {a.address_line}</option>)}</select></label><label>Schedule<input type="datetime-local" value={jobForm.scheduled_at} onChange={e=>setJobForm({...jobForm,scheduled_at:e.target.value})} required/></label><label>Delivery fee<input type="number" min="0" step="0.01" value={jobForm.delivery_fee} onChange={e=>setJobForm({...jobForm,delivery_fee:e.target.value})}/></label><label>Assign driver<select value={jobForm.assigned_to} onChange={e=>setJobForm({...jobForm,assigned_to:e.target.value})}><option value="">Unassigned</option>{drivers.map(d=><option key={d.user_id} value={d.user_id}>{d.name} · {label(d.role)}</option>)}</select></label><label>Contact mobile<input value={jobForm.contact_mobile} onChange={e=>setJobForm({...jobForm,contact_mobile:e.target.value})}/></label><label className="wide">Notes<textarea value={jobForm.notes} onChange={e=>setJobForm({...jobForm,notes:e.target.value})}/></label><button className="primary wide">Create Job</button></form></section></div>}
 </main>;
}
