import type { Metadata } from "next";
import "../legal.css";

export const metadata: Metadata = {
  title: "Privacy Policy | LabaFlow",
  description: "How LabaFlow and PAO Technologies collect, use, and protect information.",
};

export default function PrivacyPage(){return <main className="legalPage"><div className="legalShell">
  <nav className="legalNav" aria-label="Legal pages"><a className="legalBrand" href="/"><img src="/labaflow-icon.svg" alt=""/>LabaFlow</a><div className="legalNavLinks"><a href="/privacy" aria-current="page">Privacy</a><a href="/account-deletion">Delete account</a></div></nav>
  <header className="legalHero"><p className="legalEyebrow">PAO TECHNOLOGIES · LABAFLOW</p><h1>Privacy Policy</h1><p>This policy explains how LabaFlow handles information when organizations, staff, and customers use our web and Android applications.</p><span className="legalUpdated">Last updated September 8, 2026</span></header>
  <article className="legalContent">
    <section><h2>Who operates LabaFlow</h2><p>LabaFlow is a laundry operations platform provided by PAO Technologies. Organizations using LabaFlow manage their own staff, customers, orders, and business records. Depending on the context, PAO Technologies acts as the service provider and the organization acts as the controller of its business and customer records.</p></section>
    <section><h2>Information we collect</h2><ul><li><strong>Account information:</strong> name, email address, telephone number, authentication details, organization membership, role, and branch assignment.</li><li><strong>Business and customer records:</strong> organization and branch details, customer profiles and codes, order history, services, products, inventory, payments recorded by staff, loyalty activity, pickup and delivery information, and receipt details.</li><li><strong>Files and device features:</strong> logos or images you upload, camera access when you scan QR codes, and Bluetooth access when you connect a supported receipt printer.</li><li><strong>Technical information:</strong> device and browser details, IP-derived connection information, application events, and error diagnostics used to secure and improve LabaFlow.</li></ul><p>LabaFlow does not require users to enter payment-card numbers into the app. Payment records may include a payment method or external transaction reference entered by an organization.</p></section>
    <section><h2>How we use information</h2><ul><li>Provide authentication, organization access, customer accounts, order tracking, receipts, loyalty, reporting, inventory, and related features.</li><li>Keep information synchronized across authorized devices and organization users.</li><li>Operate customer QR codes, printing, support, security monitoring, troubleshooting, and service alerts.</li><li>Prevent misuse, protect accounts, comply with legal obligations, and improve reliability and usability.</li></ul></section>
    <section><h2>Sharing and service providers</h2><p>We disclose information only as needed to operate LabaFlow, follow the organization’s instructions, comply with law, or protect users and the service. Infrastructure and communications providers may process limited information on our behalf, including cloud database and authentication services, hosting providers, and email-delivery services. We do not sell personal information or use it for third-party advertising.</p></section>
    <section><h2>Data access and separation</h2><p>LabaFlow uses organization and role controls to limit access. Authorized organization administrators and staff can access records belonging to their organization according to their assigned permissions. A customer who is associated with more than one organization can select the organization whose customer account they want to view.</p></section>
    <section><h2>Retention and deletion</h2><p>We retain information while an account or organization uses LabaFlow and as reasonably needed for legitimate business, security, backup, dispute-resolution, and legal purposes. Some records may be retained by an organization where law or legitimate recordkeeping obligations require it. When information is no longer required, it is deleted or de-identified.</p><div className="legalCallout"><strong>Want to delete an account or associated data?</strong><p>See our account deletion page for the available request methods, what will be removed, and what may need to be retained.</p><a className="legalAction" href="/account-deletion">Account deletion options →</a></div></section>
    <section><h2>Your choices</h2><p>You may request access, correction, or deletion of personal information. Organization customers should first contact the organization that created or manages their customer profile. Account holders may also follow the deletion process linked above. You can deny camera or Bluetooth permissions in device settings, although QR scanning or direct printing will then be unavailable.</p></section>
    <section><h2>Security and international processing</h2><p>We use administrative and technical safeguards designed to protect information. No system can guarantee absolute security. Our service providers may process information in locations outside your country, subject to appropriate contractual and legal protections where required.</p></section>
    <section><h2>Children and policy changes</h2><p>LabaFlow is a business operations service and is not directed to children. We may update this policy as the service changes. The date above shows the latest revision, and material changes will be communicated where appropriate.</p></section>
    <section><h2>Contact</h2><p>For privacy questions or requests, contact PAO Technologies through the official contact channel at <a href="https://paotechs.com" target="_blank" rel="noreferrer">paotechs.com</a>. Include “LabaFlow Privacy” in your message and do not send passwords or payment-card details.</p></section>
  </article><footer className="legalFooter">© 2026 PAO Technologies · <a href="/">Return to LabaFlow</a></footer>
</div></main>}
