"use client";

import {ChangeEvent,useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {supabase} from "../lib/supabase";

type Org={id:string;name:string;logo_url?:string|null;contact_person?:string|null;phone?:string|null;email?:string|null;address?:string|null;website?:string|null;receipt_footer?:string|null};
type Branch={id:string;name:string;code:string;logo_url?:string|null};
const allowed=["image/png","image/jpeg","image/webp"];
export default function BrandingSettingsEnhancer(){
 const [host,setHost]=useState<HTMLElement|null>(null),[org,setOrg]=useState<Org|null>(null),[branches,setBranches]=useState<Branch[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 const [profile,setProfile]=useState({name:"",contact_person:"",phone:"",email:"",address:"",website:"",receipt_footer:""});
 useEffect(()=>{if(location.pathname!=="/organization")return;let mounted=true,observer:MutationObserver;const find=()=>{const head=document.querySelector<HTMLElement>(".orgAdminPage .panelHead");if(head&&!document.getElementById("branding-settings-host")){const node=document.createElement("div");node.id="branding-settings-host";head.insertAdjacentElement("afterend",node);if(mounted)setHost(node)}};find();observer=new MutationObserver(find);observer.observe(document.body,{childList:true,subtree:true});supabase.auth.getSession().then(({data})=>{if(data.session)load()});return()=>{mounted=false;observer.disconnect()}},[]);
 async function load(){const {data,error}=await supabase.rpc("get_organization_admin_context");if(error){setMessage(error.message);return}const o=data?.organization??null;setOrg(o);setBranches(data?.branches??[]);if(o)setProfile({name:o.name??"",contact_person:o.contact_person??"",phone:o.phone??"",email:o.email??"",address:o.address??"",website:o.website??"",receipt_footer:o.receipt_footer??""})}
 async function saveProfile(){if(!profile.name.trim()){setMessage("Business name is required.");return}setBusy("profile");const {error}=await supabase.rpc("update_organization_business_profile",{p_name:profile.name,p_contact_person:profile.contact_person||null,p_phone:profile.phone||null,p_email:profile.email||null,p_address:profile.address||null,p_website:profile.website||null,p_receipt_footer:profile.receipt_footer||null});setMessage(error?error.message:"Business information updated.");if(!error)await load();setBusy("")}
 function ext(file:File){if(file.type==="image/png")return"png";if(file.type==="image/webp")return"webp";return"jpg"}function validate(file:File){if(!allowed.includes(file.type))return"Use a PNG, JPG, or WebP image.";if(file.size>2*1024*1024)return"Logo must be 2 MB or smaller.";return""}
 async function upload(file:File,target:"organization"|"branch",branch?:Branch){if(!org)return;const problem=validate(file);if(problem){setMessage(problem);return}setBusy(target==="organization"?"org":branch?.id||"");setMessage("");const path=target==="organization"?`${org.id}/organization/logo-${Date.now()}.${ext(file)}`:`${org.id}/branches/${branch!.id}/logo-${Date.now()}.${ext(file)}`;const {error:uploadError}=await supabase.storage.from("business-logos").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(uploadError){setMessage(uploadError.message);setBusy("");return}const {data:urlData}=supabase.storage.from("business-logos").getPublicUrl(path);const url=urlData.publicUrl;const result=target==="organization"?await supabase.rpc("set_organization_logo",{p_logo_url:url}):await supabase.rpc("set_branch_logo",{p_branch_id:branch!.id,p_logo_url:url});if(result.error){setMessage(result.error.message);setBusy("");return}setMessage(target==="organization"?"Business logo updated.":`${branch!.name} logo updated.`);await load();setBusy("");location.reload()}
 async function remove(target:"organization"|"branch",branch?:Branch){if(!org)return;setBusy(target==="organization"?"org":branch?.id||"");const result=target==="organization"?await supabase.rpc("set_organization_logo",{p_logo_url:""}):await supabase.rpc("set_branch_logo",{p_branch_id:branch!.id,p_logo_url:""});setMessage(result.error?result.error.message:"Logo removed. Organization logo will be used as fallback.");await load();setBusy("");location.reload()}
 function pick(target:"organization"|"branch",branch?:Branch){return(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(file)upload(file,target,branch);e.target.value=""}}
 if(!host||!org)return null;
 return createPortal(<><section className="panel brandingSettingsPanel"><div className="brandingPanelHead"><div><p className="eyebrow">BUSINESS PROFILE</p><h2>Business Information</h2><p className="muted">This information identifies your business throughout LabaFlow and on customer receipts.</p></div></div>{message&&<p className="notice">{message}</p>}<div className="gridForm"><label>Business Name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Contact Person<input value={profile.contact_person} onChange={e=>setProfile({...profile,contact_person:e.target.value})}/></label><label>Business Phone<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>Business Email<input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label className="wide">Business Address<input value={profile.address} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><label>Website<input value={profile.website} onChange={e=>setProfile({...profile,website:e.target.value})} placeholder="https://..."/></label><label className="wide">Receipt Thank-you Message<input value={profile.receipt_footer} onChange={e=>setProfile({...profile,receipt_footer:e.target.value})} placeholder={`Thank you for choosing ${profile.name||"our business"}.`}/></label></div><button className="primary" disabled={Boolean(busy)} onClick={saveProfile}>{busy==="profile"?"Saving…":"Save Business Information"}</button></section>
 <section className="panel brandingSettingsPanel"><div className="brandingPanelHead"><div><p className="eyebrow">BUSINESS BRANDING</p><h2>Business & Branch Logos</h2><p className="muted">The business logo is the default throughout your organization. A branch logo overrides it for receipts and branch-specific screens.</p></div></div><div className="brandingLogoRow"><div className="brandingPreview">{org.logo_url?<img src={org.logo_url} alt={`${org.name} logo`}/>:<span>LF</span>}</div><div className="brandingLogoInfo"><strong>{org.name}</strong><small>Organization default logo · PNG, JPG, or WebP · max 2 MB</small><div className="brandingActions"><label className="primary brandingUploadButton">{busy==="org"?"Uploading…":"Upload Business Logo"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={Boolean(busy)} onChange={pick("organization")}/></label>{org.logo_url&&<button className="secondary" disabled={Boolean(busy)} onClick={()=>remove("organization")}>Remove</button>}</div></div></div><h3>Branch Logos</h3><div className="brandingBranchGrid">{branches.map(b=><article key={b.id} className="brandingBranchCard"><div className="brandingPreview small">{b.logo_url?<img src={b.logo_url} alt={`${b.name} logo`}/>:org.logo_url?<img src={org.logo_url} alt={`${org.name} logo`}/>:<span>LF</span>}</div><div><strong>{b.name}</strong><small>{b.code} · {b.logo_url?"Custom branch logo":"Using business logo"}</small></div><div className="brandingActions"><label className="miniBtn brandingUploadButton">{busy===b.id?"Uploading…":"Upload"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={Boolean(busy)} onChange={pick("branch",b)}/></label>{b.logo_url&&<button className="miniBtn" disabled={Boolean(busy)} onClick={()=>remove("branch",b)}>Use Business Logo</button>}</div></article>)}</div></section></>,host)
}
