"use client";

import {useCallback,useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {supabase} from "../lib/supabase";
import {getStoredLocalStaffSession,getLocalStaffOperationalContext} from "../lib/localStaff";

type Customer={id:string;customer_code:string;full_name:string;mobile:string|null;email:string|null;lifetime_visits:number;lifetime_spend:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});

export default function CustomerArchiveEnhancer(){
 const [host,setHost]=useState<HTMLElement|null>(null),[active,setActive]=useState<Customer[]>([]),[archived,setArchived]=useState<Customer[]>([]),[canManage,setCanManage]=useState(false),[open,setOpen]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{if(location.pathname!=="/customers")return;const local=getStoredLocalStaffSession();if(local){const context=await getLocalStaffOperationalContext();setCanManage(Boolean(context.data?.permissions?.manage_customers));setActive((context.data?.customers??[]) as Customer[]);const result=await supabase.rpc("list_inactive_customers_local",{p_token:local.token});if(!result.error)setArchived((result.data??[]) as Customer[]);return}const [access,a,i]=await Promise.all([supabase.rpc("get_current_access_context"),supabase.from("customers").select("id,customer_code,full_name,mobile,email,lifetime_visits,lifetime_spend").eq("active",true).order("full_name"),supabase.from("customers").select("id,customer_code,full_name,mobile,email,lifetime_visits,lifetime_spend").eq("active",false).order("full_name")]);setCanManage(Boolean(access.data?.permissions?.manage_customers));if(!a.error)setActive((a.data??[]) as Customer[]);if(!i.error)setArchived((i.data??[]) as Customer[])},[]);
 useEffect(()=>{if(location.pathname!=="/customers")return;let mounted=true;const attach=()=>{const panel=document.querySelector<HTMLElement>(".customerDirectoryPanel");if(!panel)return;let node=document.getElementById("customer-archive-host");if(!node){node=document.createElement("div");node.id="customer-archive-host";panel.insertAdjacentElement("afterend",node)}if(mounted)setHost(node)};attach();load();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{mounted=false;observer.disconnect()}},[load]);
 useEffect(()=>{if(!canManage)return;const enhance=()=>{document.querySelectorAll<HTMLElement>(".customerTable tbody tr").forEach(row=>{const code=Array.from(row.querySelectorAll(".customerIdentity small")).map(x=>x.textContent?.trim()).find(x=>x?.startsWith("LF-C-"));const customer=active.find(x=>x.customer_code===code);const actions=row.querySelector<HTMLElement>(".customerActions");if(!customer||!actions||actions.querySelector("[data-customer-toggle]"))return;const label=document.createElement("label");label.className="customerActiveSwitch";label.dataset.customerToggle="1";label.innerHTML='<span>Active</span><input type="checkbox" checked><i></i>';const input=label.querySelector("input")!;input.onchange=()=>{if(!confirm(`Archive ${customer.full_name}? They will be hidden from active customer lists and My LabaFlow access will be paused.`)){input.checked=true;return}void change(customer,false)};actions.appendChild(label)})};enhance();const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[active,canManage]);
 async function change(customer:Customer,next:boolean){setBusy(customer.id);setMessage("");const local=getStoredLocalStaffSession();const result=local?await supabase.rpc("set_customer_active_local",{p_token:local.token,p_customer_id:customer.id,p_active:next}):await supabase.rpc("set_customer_active",{p_customer_id:customer.id,p_active:next});if(result.error){setMessage(result.error.message);setBusy("");return}await load();setBusy("");setMessage(next?`${customer.full_name} was restored to active customers.`:`${customer.full_name} was moved to the Customer Archive.`);location.reload()}
 if(!host)return null;
 return createPortal(<section className="panel customerArchivePanel"><button type="button" className="archiveHeader" onClick={()=>setOpen(v=>!v)}><div className="archiveTitle"><span className="archiveIcon">♙</span><div><p className="eyebrow">CUSTOMER ARCHIVE</p><h2>Inactive Customers</h2><span>{archived.length} archived customer{archived.length===1?"":"s"} · Hidden from active lists</span></div></div><span className="archiveToggle">{open?"Hide":"View Archive"} {open?"⌃":"⌄"}</span></button>{message&&<p className="notice">{message}</p>}{open&&<div className="customerArchiveBody">{archived.map(c=><article className="archivedCustomer" key={c.id}><div className="customerIdentity"><span className="customerAvatar">{c.full_name.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join("").toUpperCase()||"C"}</span><div><strong>{c.full_name}</strong><small>{c.customer_code}</small><small>{c.mobile||c.email||"No contact"}</small></div></div><div><small>{Number(c.lifetime_visits||0).toLocaleString()} visits</small><strong>{peso.format(Number(c.lifetime_spend||0))}</strong></div>{canManage&&<label className="customerActiveSwitch"><span>Inactive</span><input type="checkbox" checked={false} disabled={busy===c.id} onChange={()=>void change(c,true)}/><i></i></label>}</article>)}{!archived.length&&<p className="customerEmpty">No inactive customers. Customers switched off will appear here.</p>}</div>}</section>,host);
}
