"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import QRCode from "qrcode";
import { supabase } from "../lib/supabase";

type Branch={id:string;code:string;name:string;address:string|null};
type Customer={id:string;customer_code:string;full_name:string;mobile:string|null;email:string|null;loyalty_points:number;lifetime_visits:number;lifetime_spend:number;created_at:string};
type Service={id:string;name:string;description:string|null;pricing_unit:"kg"|"piece"|"load"|"package";default_price:number;loyalty_points:number;active:boolean};
type Order={id:string;order_code:string;branch_id:string;customer_id:string|null;status:string;payment_status:string;subtotal:number;discount:number;total:number;amount_paid:number;created_at:string;loyalty_awarded?:boolean;customers:{full_name:string;customer_code:string}|null};
type Permissions={manage_organization:boolean;manage_services:boolean;manage_staff:boolean;manage_customers:boolean;adjust_loyalty:boolean;create_orders:boolean;process_orders:boolean;record_payments:boolean;delivery_access:boolean;view_reports:boolean};
type Access={has_membership:boolean;membership_active?:boolean;organization_active?:boolean;role?:string;branches?:Branch[];features?:Record<string,boolean>;settings?:Record<string,any>;permissions?:Permissions;is_platform_admin?:boolean};
type Context={profile?:{full_name:string|null;email:string};organization?:{id:string;name:string;slug:string}|null};
type View="dashboard"|"newOrder"|"orders"|"customers"|"loyalty"|"services"|"settings";
type CartItem={service_id:string;quantity:number};

const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const defaultWorkflow=["received","sorting","washing","drying","folding","ready","completed"];
const defaultPayments=["cash","gcash","maya","card","bank_transfer"];
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function LabaFlowApp(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [context,setContext]=useState<Context>({}),[access,setAccess]=useState<Access>({has_membership:false}),[view,setView]=useState<View>("dashboard");
 const [customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[orders,setOrders]=useState<Order[]>([]);
 const [showCustomer,setShowCustomer]=useState(false),[showService,setShowService]=useState(false),[qr,setQr]=useState<{customer:Customer;image:string}|null>(null);
 const [customerForm,setCustomerForm]=useState({full_name:"",mobile:"",email:"",preferred_branch_id:""});
 const [serviceForm,setServiceForm]=useState({name:"",description:"",pricing_unit:"kg",default_price:"",loyalty_points:"0"});
 const [servicePoints,setServicePoints]=useState<Record<string,string>>({});
 const [orgForm,setOrgForm]=useState({name:"",slug:"",branch_name:"Main Branch",branch_code:"MAIN"});
 const [orderCustomer,setOrderCustomer]=useState(""),[orderBranch,setOrderBranch]=useState(""),[orderNotes,setOrderNotes]=useState(""),[orderDiscount,setOrderDiscount]=useState("0"),[cart,setCart]=useState<CartItem[]>([]);
 const [payment,setPayment]=useState<Record<string,{amount:string;method:string;reference:string}>>({}),[scanToken,setScanToken]=useState("");

 const permissions=access.permissions??{manage_organization:false,manage_services:false,manage_staff:false,manage_customers:false,adjust_loyalty:false,create_orders:false,process_orders:false,record_payments:false,delivery_access:false,view_reports:false};
 const branches=access.branches??[];
 const workflow=(access.settings?.order_workflow?.stages as string[]|undefined)?.filter(Boolean)??defaultWorkflow;
 const paymentMethods=(access.settings?.payment_methods?.methods as string[]|undefined)?.filter(Boolean)??defaultPayments;
 const requireFullPayment=Boolean(access.settings?.completion_rules?.require_full_payment_before_completion);
 const activeWorkflow=workflow.filter(s=>!["cancelled","on_hold","completed"].includes(s));

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load();else{setContext({});setAccess({has_membership:false});setCustomers([]);setServices([]);setOrders([])}},[session]);

 async function load(){setMessage("");const [c,a]=await Promise.all([supabase.rpc("get_my_labaflow_context"),supabase.rpc("get_current_access_context")]);if(c.error||a.error){setMessage(c.error?.message||a.error?.message||"Unable to load workspace");return}const next=c.data??{},acc=(a.data??{has_membership:false}) as Access;setContext(next);setAccess(acc);const first=acc.branches?.[0]?.id??"";setOrderBranch(first);if(next.organization&&acc.has_membership)await Promise.all([loadCustomers(),loadServices(),loadOrders()])}
 async function loadCustomers(){const {data,error}=await supabase.from("customers").select("id,customer_code,full_name,mobile,email,loyalty_points,lifetime_visits,lifetime_spend,created_at").eq("active",true).order("created_at",{ascending:false});if(error)setMessage(error.message);else setCustomers((data??[]) as Customer[])}
 async function loadServices(){const {data,error}=await supabase.from("services").select("id,name,description,pricing_unit,default_price,loyalty_points,active").eq("active",true).order("name");if(error)setMessage(error.message);else{const rows=(data??[]).map((x:any)=>({...x,default_price:Number(x.default_price),loyalty_points:Number(x.loyalty_points??0)})) as Service[];setServices(rows);setServicePoints(Object.fromEntries(rows.map(s=>[s.id,String(s.loyalty_points)])))}}
 async function loadOrders(){const {data,error}=await supabase.from("laundry_orders").select("id,order_code,branch_id,customer_id,status,payment_status,subtotal,discount,total,amount_paid,created_at,loyalty_awarded,customers(full_name,customer_code)").order("created_at",{ascending:false}).limit(100);if(error)setMessage(error.message);else setOrders((data??[]).map((x:any)=>({...x,subtotal:Number(x.subtotal),discount:Number(x.discount),total:Number(x.total),amount_paid:Number(x.amount_paid)})))}

 async function signIn(e:FormEvent){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage(error.message)}
 async function signUp(){if(!email.trim()||password.length<8){setMessage("Enter an email and a password with at least 8 characters.");return}const {error}=await supabase.auth.signUp({email:email.trim(),password});setMessage(error?error.message:"Account created. Confirm your email if required, then sign in.")}
 async function createOrganization(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("create_organization_with_main_branch",{p_name:orgForm.name,p_slug:orgForm.slug,p_branch_name:orgForm.branch_name,p_branch_code:orgForm.branch_code});if(error)setMessage(error.message);else await load()}
 async function createCustomer(e:FormEvent){e.preventDefault();const {data,error}=await supabase.rpc("create_customer_with_qr",{p_full_name:customerForm.full_name,p_mobile:customerForm.mobile||null,p_email:customerForm.email||null,p_preferred_branch_id:customerForm.preferred_branch_id||null});if(error){setMessage(error.message);return}setShowCustomer(false);setCustomerForm({full_name:"",mobile:"",email:"",preferred_branch_id:""});await loadCustomers();await showQr(data.customer,data.qr_token)}
 async function createService(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("create_laundry_service",{p_name:serviceForm.name,p_description:serviceForm.description||null,p_pricing_unit:serviceForm.pricing_unit,p_default_price:Number(serviceForm.default_price),p_loyalty_points:Number(serviceForm.loyalty_points)||0});if(error)setMessage(error.message);else{setShowService(false);setServiceForm({name:"",description:"",pricing_unit:"kg",default_price:"",loyalty_points:"0"});await loadServices()}}
 async function saveServicePoints(service:Service){const points=Math.max(Number(servicePoints[service.id]??service.loyalty_points)||0,0);const {error}=await supabase.rpc("update_service_loyalty_points",{p_service_id:service.id,p_loyalty_points:points});if(error)setMessage(error.message);else{setMessage(`${service.name} reward set to ${points} points.`);await loadServices()}}
 async function showQr(customer:Customer,token?:string){let t=token;if(!t){const {data,error}=await supabase.rpc("get_customer_qr",{p_customer_id:customer.id});if(error){setMessage(error.message);return}t=data.qr_token}const image=await QRCode.toDataURL(`labaflow:${t}`,{width:360,margin:2});setQr({customer,image})}
 async function lookupQr(){const token=scanToken.trim().replace(/^labaflow:/i,"");if(!token)return;const {data,error}=await supabase.rpc("lookup_customer_by_qr",{p_token:token});if(error)setMessage(error.message);else{setOrderCustomer(data.id);setScanToken("");setView("newOrder");setMessage(`Customer selected: ${data.full_name}`)}}
 async function adjustPoints(c:Customer,points:number){const {error}=await supabase.rpc("adjust_customer_loyalty",{p_customer_id:c.id,p_points:points,p_description:points>0?"Manual loyalty award":"Reward redemption",p_branch_id:branches[0]?.id??null});if(error)setMessage(error.message);else await loadCustomers()}

 function addService(s:Service){setCart(x=>{const f=x.find(i=>i.service_id===s.id);return f?x.map(i=>i.service_id===s.id?{...i,quantity:i.quantity+1}:i):[...x,{service_id:s.id,quantity:1}]})}
 const subtotal=cart.reduce((n,i)=>n+(services.find(s=>s.id===i.service_id)?.default_price??0)*i.quantity,0),total=Math.max(subtotal-(Number(orderDiscount)||0),0);
 async function createOrder(e:FormEvent){e.preventDefault();if(!cart.length||!orderBranch)return;const {data,error}=await supabase.rpc("create_laundry_order",{p_branch_id:orderBranch,p_customer_id:orderCustomer||null,p_items:cart,p_discount:Number(orderDiscount)||0,p_notes:orderNotes||null,p_due_at:null});if(error)setMessage(error.message);else{setCart([]);setOrderDiscount("0");setOrderNotes("");await loadOrders();setView("orders");setMessage(`Order ${data.order_code} created.`)}}
 function nextStatus(current:string){const i=workflow.indexOf(current);return i>=0&&i<workflow.length-1?workflow[i+1]:null}
 async function moveOrder(o:Order){const next=nextStatus(o.status);if(!next)return;if(next==="completed"&&requireFullPayment&&o.amount_paid<o.total){setMessage(`Full payment is required before completing ${o.order_code}.`);return}const {error}=await supabase.rpc("update_order_status",{p_order_id:o.id,p_status:next,p_notes:null});if(error)setMessage(error.message);else await Promise.all([loadOrders(),loadCustomers()])}
 async function recordPayment(o:Order){const p=payment[o.id]??{amount:"",method:paymentMethods[0]??"cash",reference:""};const amount=Number(p.amount);if(!amount)return;const {error}=await supabase.rpc("record_order_payment",{p_order_id:o.id,p_amount:amount,p_method:p.method,p_reference:p.reference||null});if(error)setMessage(error.message);else{setPayment(x=>({...x,[o.id]:{amount:"",method:p.method,reference:""}}));await Promise.all([loadOrders(),loadCustomers()]);setMessage(amount>=Math.max(o.total-o.amount_paid,0)?"Payment completed. Customer rewards were calculated automatically if qualified.":"Partial payment recorded.")}}

 const stats=useMemo(()=>({today:orders.filter(o=>o.created_at.slice(0,10)===new Date().toISOString().slice(0,10)).length,ready:orders.filter(o=>o.status==="ready").length,revenue:orders.filter(o=>o.payment_status==="paid").reduce((n,o)=>n+o.total,0),points:customers.reduce((n,c)=>n+c.loyalty_points,0)}),[orders,customers]);
 if(checking)return <main className="center"><div className="loader">Loading LabaFlow…</div></main>;
 if(!session)return <main className="authPage"><section className="brandPanel"><div className="logoMark">LF</div><h1>LabaFlow</h1><p>Laundry management, simplified.</p></section><section className="authCard"><p className="eyebrow">WELCOME</p><h2>Sign in to your laundry workspace</h2><form onSubmit={signIn} className="stack"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Sign In</button><button type="button" className="secondary" onClick={signUp}>Create Account</button></form>{message&&<p className="notice">{message}</p>}</section></main>;
 if(!access.has_membership&&!context.organization)return <main className="onboarding"><section className="onboardCard"><p className="eyebrow">FIRST-TIME SETUP</p><h1>Create your LabaFlow organization</h1><form onSubmit={createOrganization} className="gridForm"><label>Business name<input value={orgForm.name} onChange={e=>setOrgForm({...orgForm,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")})} required/></label><label>Slug<input value={orgForm.slug} onChange={e=>setOrgForm({...orgForm,slug:e.target.value})} required/></label><label>Main branch<input value={orgForm.branch_name} onChange={e=>setOrgForm({...orgForm,branch_name:e.target.value})}/></label><label>Branch code<input value={orgForm.branch_code} onChange={e=>setOrgForm({...orgForm,branch_code:e.target.value.toUpperCase()})}/></label><button className="primary wide">Create Organization</button></form></section></main>;
 if(!context.organization||access.membership_active===false||access.organization_active===false)return <main className="center"><section className="onboardCard"><h2>Workspace unavailable</h2><button className="secondary" onClick={()=>supabase.auth.signOut()}>Sign Out</button></section></main>;

 const canSeeOrders=permissions.create_orders||permissions.process_orders||permissions.record_payments||permissions.view_reports||permissions.delivery_access;
 const canSeeCustomers=permissions.manage_customers||permissions.create_orders||permissions.adjust_loyalty;
 const activeBranch=branches.find(b=>b.id===orderBranch)??branches[0];
 return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="logoMark small">LF</div><div><strong>LabaFlow</strong><small>{context.organization.name}</small></div></div><div className="roleBadge"><strong>{context.profile?.full_name||session.user.email}</strong><span>{label(access.role??"member")}{activeBranch?` · ${activeBranch.name}`:""}</span></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>Dashboard</button>{permissions.create_orders&&<button className={view==="newOrder"?"active":""} onClick={()=>setView("newOrder")}>New Order</button>}{canSeeOrders&&<button className={view==="orders"?"active":""} onClick={()=>setView("orders")}>Orders</button>}{canSeeCustomers&&<button className={view==="customers"?"active":""} onClick={()=>setView("customers")}>Customers</button>}{(permissions.adjust_loyalty||permissions.view_reports)&&<button className={view==="loyalty"?"active":""} onClick={()=>setView("loyalty")}>Loyalty</button>}{permissions.manage_services&&<button className={view==="services"?"active":""} onClick={()=>setView("services")}>Services & Pricing</button>}{permissions.manage_organization&&<><hr/><button onClick={()=>location.href="/organization"}>Organization Admin</button><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}>Organization Settings</button></>}{access.is_platform_admin&&<button onClick={()=>location.href="/admin"}>Platform Admin</button>}</nav><div className="sidebarFooter"><small>{session.user.email}</small><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><main className="workspace"><header><div><p className="eyebrow">{activeBranch?.name??label(access.role??"member")}</p><h1>{view==="dashboard"?"Laundry Dashboard":label(view)}</h1></div><div className="headerActions">{permissions.manage_customers&&<button className="secondary" onClick={()=>setShowCustomer(true)}>+ Customer</button>}{permissions.create_orders&&view!=="services"&&<button className="primary" onClick={()=>setView("newOrder")}>+ New Order</button>}{permissions.manage_services&&view==="services"&&<button className="primary" onClick={()=>setShowService(true)}>+ Service</button>}</div></header>{message&&<p className="notice">{message}</p>}

 {view==="dashboard"&&<><section className="stats"><article><span>Today's Orders</span><strong>{stats.today}</strong></article><article><span>Ready</span><strong>{stats.ready}</strong></article><article><span>Customers</span><strong>{customers.length}</strong></article><article><span>Paid Revenue</span><strong>{permissions.record_payments||permissions.view_reports?peso.format(stats.revenue):"—"}</strong></article></section>{permissions.create_orders&&<section className="panel"><h2>Scan Customer QR</h2><div className="scanBar"><input value={scanToken} onChange={e=>setScanToken(e.target.value)} placeholder="Scan or paste QR token"/><button className="primary" onClick={lookupQr}>Start Order</button></div></section>}<section className="panel"><div className="panelHead"><h2>Laundry Workflow</h2><small>{workflow.map(label).join(" → ")}</small></div><div className="workflow">{activeWorkflow.map((s,i)=><div key={s}><span>{i+1}</span><strong>{label(s)}</strong><b>{orders.filter(o=>o.status===s).length}</b></div>)}</div></section></>}

 {view==="services"&&permissions.manage_services&&<section className="panel"><div className="panelHead"><div><h2>Services & Pricing</h2><small>Service rewards are fixed per service rendered, not multiplied by kg/pieces.</small></div></div><div className="serviceGrid">{services.map(s=><article key={s.id}><strong>{s.name}</strong><small>{s.description||"Laundry service"}</small><b>{peso.format(s.default_price)}</b><span>per {s.pricing_unit}</span><label style={{marginTop:12,display:"grid",gap:5}}>Reward points<input type="number" min="0" value={servicePoints[s.id]??String(s.loyalty_points)} onChange={e=>setServicePoints(x=>({...x,[s.id]:e.target.value}))}/></label><button className="miniBtn" style={{marginTop:8}} onClick={()=>saveServicePoints(s)}>Save Reward</button></article>)}</div></section>}

 {view==="newOrder"&&permissions.create_orders&&<form onSubmit={createOrder}><section className="twoCols orderLayout"><article className="panel"><h2>Order Details</h2><div className="gridForm"><label>Customer<select value={orderCustomer} onChange={e=>setOrderCustomer(e.target.value)}><option value="">Walk-in</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name} — {c.customer_code}</option>)}</select></label><label>Branch<select value={orderBranch} onChange={e=>setOrderBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="wide">Notes<textarea value={orderNotes} onChange={e=>setOrderNotes(e.target.value)}/></label></div><div className="servicePicker">{services.map(s=><button type="button" key={s.id} onClick={()=>addService(s)}><strong>{s.name}</strong><small>{peso.format(s.default_price)} / {s.pricing_unit}{s.loyalty_points>0?` · +${s.loyalty_points} pts`:""}</small></button>)}</div></article><article className="panel orderSummary"><h2>Summary</h2>{cart.map(i=>{const s=services.find(x=>x.id===i.service_id)!;return <div className="cartRow" key={i.service_id}><div><strong>{s.name}</strong><small>{s.loyalty_points>0?`+${s.loyalty_points} reward pts when fully paid`:"No service reward"}</small></div><input type="number" min="0.01" step="0.01" value={i.quantity} onChange={e=>setCart(x=>x.map(z=>z.service_id===i.service_id?{...z,quantity:Number(e.target.value)}:z))}/><b>{peso.format(s.default_price*i.quantity)}</b></div>})}<div className="totals"><label>Discount<input type="number" value={orderDiscount} onChange={e=>setOrderDiscount(e.target.value)}/></label><div><span>Subtotal</span><b>{peso.format(subtotal)}</b></div><div className="grand"><span>Total</span><b>{peso.format(total)}</b></div></div><button className="primary wide" disabled={!cart.length}>Create Laundry Order</button></article></section></form>}

 {view==="orders"&&canSeeOrders&&<section className="panel"><div className="panelHead"><h2>Order Queue</h2><span>{orders.length} orders</span></div><div className="orderList">{orders.map(o=>{const p=payment[o.id]??{amount:"",method:paymentMethods[0]??"cash",reference:""};const next=nextStatus(o.status);const blocked=next==="completed"&&requireFullPayment&&o.amount_paid<o.total;const paid=o.payment_status==="paid"||o.amount_paid>=o.total;return <article className="orderCard" key={o.id}><div className="orderTop"><div><strong>{o.order_code}</strong><small>{o.customers?.full_name??"Walk-in"}</small></div><div><span className={`status ${o.status}`}>{label(o.status)}</span><b>{peso.format(o.total)}</b></div></div><div className="orderMeta"><span>Paid <b>{peso.format(o.amount_paid)}</b></span><span>Balance <b>{peso.format(Math.max(o.total-o.amount_paid,0))}</b></span><span>{paid?"Rewards calculated on full payment":requireFullPayment?"Full payment required before completion":"Partial payment allowed"}</span></div><div className="orderActions">{permissions.process_orders&&next&&<button type="button" className="secondary" disabled={blocked} title={blocked?"Full payment required before completion":""} onClick={()=>moveOrder(o)}>{next==="completed"?"Complete Order":`Move to ${label(next)}`}</button>}{permissions.record_payments&&(paid?<span className="status active">✓ Paid</span>:<><select value={p.method} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,method:e.target.value}}))}>{paymentMethods.map(m=><option key={m} value={m}>{label(m)}</option>)}</select><input type="number" min="0.01" max={Math.max(o.total-o.amount_paid,0)} step="0.01" placeholder={`Balance ${peso.format(Math.max(o.total-o.amount_paid,0))}`} value={p.amount} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,amount:e.target.value}}))}/><button type="button" className="primary" onClick={()=>recordPayment(o)}>Record Payment</button></>)}</div></article>})}</div></section>}

 {view==="customers"&&canSeeCustomers&&<section className="panel"><h2>Customers</h2><div className="table"><div className="tableHeader"><span>Customer</span><span>Contact</span><span>Loyalty</span><span>QR</span></div>{customers.map(c=><div className="tableRow" key={c.id}><span><strong>{c.full_name}</strong><small>{c.customer_code}</small></span><span>{c.mobile||c.email||"—"}</span><span>{c.loyalty_points} pts</span><span><button className="miniBtn" onClick={()=>showQr(c)}>Show QR</button></span></div>)}</div></section>}
 {view==="loyalty"&&<section className="panel"><h2>Customer Loyalty</h2>{customers.map(c=><div className="loyaltyRow" key={c.id}><div><strong>{c.full_name}</strong><small>{c.lifetime_visits} paid visits · {peso.format(c.lifetime_spend)}</small></div><div className="points">{c.loyalty_points} pts</div>{permissions.adjust_loyalty&&<div className="actions"><button onClick={()=>adjustPoints(c,10)}>+10</button><button disabled={c.loyalty_points<10} onClick={()=>adjustPoints(c,-10)}>-10</button></div>}</div>)}</section>}
 {view==="settings"&&permissions.manage_organization&&<section className="panel"><h2>Organization Settings</h2><div className="settingsGrid"><div><span>Workflow</span><strong>{workflow.map(label).join(" → ")}</strong></div><div><span>Payment methods</span><strong>{paymentMethods.map(label).join(", ")}</strong></div><div><span>Completion rule</span><strong>{requireFullPayment?"Full payment required":"Partial allowed"}</strong></div><div><span>Role</span><strong>{label(access.role??"member")}</strong></div></div><button className="primary" onClick={()=>location.href="/organization"}>Edit Organization Settings</button></section>}
 </main>

 {showCustomer&&<div className="modalBackdrop"><section className="modal"><div className="panelHead"><h2>New Customer</h2><button className="iconBtn" onClick={()=>setShowCustomer(false)}>×</button></div><form onSubmit={createCustomer} className="gridForm"><label>Full name<input value={customerForm.full_name} onChange={e=>setCustomerForm({...customerForm,full_name:e.target.value})} required/></label><label>Mobile<input value={customerForm.mobile} onChange={e=>setCustomerForm({...customerForm,mobile:e.target.value})}/></label><label>Email<input value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/></label><label>Preferred branch<select value={customerForm.preferred_branch_id} onChange={e=>setCustomerForm({...customerForm,preferred_branch_id:e.target.value})}><option value="">None</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary wide">Create Customer + QR</button></form></section></div>}
 {showService&&<div className="modalBackdrop"><section className="modal"><div className="panelHead"><h2>New Service</h2><button className="iconBtn" onClick={()=>setShowService(false)}>×</button></div><form onSubmit={createService} className="gridForm"><label>Name<input value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})} required/></label><label>Unit<select value={serviceForm.pricing_unit} onChange={e=>setServiceForm({...serviceForm,pricing_unit:e.target.value})}><option value="kg">Per kg</option><option value="piece">Per piece</option><option value="load">Per load</option><option value="package">Package</option></select></label><label>Price<input type="number" min="0" step="0.01" value={serviceForm.default_price} onChange={e=>setServiceForm({...serviceForm,default_price:e.target.value})} required/></label><label>Reward points<input type="number" min="0" step="1" value={serviceForm.loyalty_points} onChange={e=>setServiceForm({...serviceForm,loyalty_points:e.target.value})}/></label><label className="wide">Description<input value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})}/></label><button className="primary wide">Create Service</button></form></section></div>}
 {qr&&<div className="modalBackdrop"><section className="modal qrModal"><div className="panelHead"><h2>{qr.customer.full_name}</h2><button className="iconBtn" onClick={()=>setQr(null)}>×</button></div><div className="customerCard"><img src={qr.image} alt="Customer QR"/><strong>{qr.customer.customer_code}</strong><span>{qr.customer.loyalty_points} points</span></div><div className="qrActions"><button className="primary" onClick={()=>window.print()}>Print Customer Card</button></div></section></div>}
 </div>;
}
