"use client";

import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
import {getStoredLocalStaffSession,getLocalStaffOperationalContext} from "../lib/localStaff";

type Order={id:string;order_code:string;status:string;total:number;amount_paid:number};
const defaults=["received","sorting","washing","drying","folding","ready","completed"];
const title=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function OrderStatusSelectorEnhancer(){
 const [orders,setOrders]=useState<Order[]>([]),[workflow,setWorkflow]=useState(defaults),[canProcess,setCanProcess]=useState(false),[requireFull,setRequireFull]=useState(false);
 useEffect(()=>{if(location.pathname!=="/orders")return;let mounted=true;(async()=>{const local=getStoredLocalStaffSession();if(local){const result=await getLocalStaffOperationalContext();if(!mounted||!result.data)return;setOrders((result.data.orders??[]) as Order[]);setWorkflow((result.data.settings?.order_workflow?.stages??defaults).filter(Boolean));setCanProcess(Boolean(result.data.permissions?.process_orders));setRequireFull(Boolean(result.data.settings?.completion_rules?.require_full_payment_before_completion));return}const [access,list]=await Promise.all([supabase.rpc("get_current_access_context"),supabase.from("laundry_orders").select("id,order_code,status,total,amount_paid").order("created_at",{ascending:false}).limit(200)]);if(!mounted)return;if(!list.error)setOrders((list.data??[]) as Order[]);setWorkflow((access.data?.settings?.order_workflow?.stages??defaults).filter(Boolean));setCanProcess(Boolean(access.data?.permissions?.process_orders));setRequireFull(Boolean(access.data?.settings?.completion_rules?.require_full_payment_before_completion))})();return()=>{mounted=false}},[]);
 useEffect(()=>{if(!canProcess)return;const enhance=()=>{document.querySelectorAll<HTMLElement>(".polishedOrder").forEach(card=>{const code=card.querySelector<HTMLElement>(".orderTop strong")?.textContent?.trim(),order=orders.find(o=>o.order_code===code),actions=card.querySelector<HTMLElement>(".orderActions");if(!order||!actions||actions.querySelector("[data-order-status-selector]"))return;const wrap=document.createElement("label");wrap.className="orderStatusSelector";wrap.dataset.orderStatusSelector="1";const caption=document.createElement("span");caption.textContent="Status";const select=document.createElement("select");const feedback=document.createElement("small");feedback.className="orderStatusFeedback";const statuses=[...new Set([...workflow,"cancelled",order.status])];statuses.forEach(status=>{const option=document.createElement("option");option.value=status;option.textContent=title(status);option.selected=status===order.status;select.appendChild(option)});select.disabled=["completed","cancelled"].includes(order.status)||!navigator.onLine;select.onchange=async()=>{const previous=order.status,next=select.value;if(next==="completed"&&requireFull&&Number(order.amount_paid)<Number(order.total)){alert("Full payment is required before completing this order.");select.value=previous;return}select.disabled=true;feedback.textContent="Saving…";const local=getStoredLocalStaffSession();const result=local?await supabase.rpc("update_order_status_local",{p_token:local.token,p_order_id:order.id,p_status:next,p_notes:"Status selected from Order Management"}):await supabase.rpc("update_order_status",{p_order_id:order.id,p_status:next,p_notes:"Status selected from Order Management"});if(result.error){alert(result.error.message);select.value=previous;select.disabled=false;feedback.textContent="";return}order.status=next;const badge=card.querySelector<HTMLElement>(".orderTop .status");if(badge){badge.textContent=title(next);badge.className=`status ${next}`}select.disabled=["completed","cancelled"].includes(next)||!navigator.onLine;feedback.textContent="Updated";window.setTimeout(()=>{feedback.textContent=""},1800)};wrap.append(caption,select,feedback);actions.querySelectorAll<HTMLButtonElement>("button").forEach(button=>{if(button.textContent?.trim().startsWith("Move to "))button.hidden=true});actions.prepend(wrap)});};enhance();const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[orders,workflow,canProcess,requireFull]);
 return null;
}
