"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import QRCode from "qrcode";
import { supabase } from "../lib/supabase";

type Branch={id:string;code:string;name:string;address:string|null};
type Customer={id:string;customer_code:string;full_name:string;mobile:string|null;email:string|null;loyalty_points:number;lifetime_visits:number;lifetime_spend:number;created_at:string};
type Service={id:string;name:string;description:string|null;pricing_unit:"kg"|"piece"|"load"|"package";default_price:number;active:boolean};
type Order={id:string;order_code:string;branch_id:string;customer_id:string|null;status:string;payment_status:string;subtotal:number;discount:number;total:number;amount_paid:number;notes:string|null;due_at:string|null;created_at:string;customers:{full_name:string;customer_code:string}|null};
type Context={profile?:{full_name:string|null;email:string};organization?:{id:string;name:string;slug:string}|null;membership?:{role:string}|null;branches?:Branch[]};
type View="dashboard"|"newOrder"|"orders"|"customers"|"loyalty"|"services"|"settings";
type QrProfile={customer:Customer;token:string;image:string};
type CartItem={service_id:string;quantity:number};

const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const statuses=["received","sorting","washing","drying","folding","ready","completed"];
const statusLabel=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function Home(){
  const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true);
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");
  const [context,setContext]=useState<Context>({}),[view,setView]=useState<View>("dashboard");
  const [customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[orders,setOrders]=useState<Order[]>([]);
  const [showCustomer,setShowCustomer]=useState(false),[showService,setShowService]=useState(false),[qrProfile,setQrProfile]=useState<QrProfile|null>(null),[scanToken,setScanToken]=useState("");
  const [customerForm,setCustomerForm]=useState({full_name:"",mobile:"",email:"",preferred_branch_id:""});
  const [serviceForm,setServiceForm]=useState({name:"",description:"",pricing_unit:"kg",default_price:""});
  const [orgForm,setOrgForm]=useState({name:"",slug:"",branch_name:"Main Branch",branch_code:"MAIN"});
  const [orderCustomer,setOrderCustomer]=useState(""),[orderBranch,setOrderBranch]=useState(""),[orderNotes,setOrderNotes]=useState(""),[orderDiscount,setOrderDiscount]=useState("0"),[cart,setCart]=useState<CartItem[]>([]);
  const [payment,setPayment]=useState<Record<string,{amount:string;method:string;reference:string}>>({});

  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(session)loadContext();else{setContext({});setCustomers([]);setServices([]);setOrders([])}},[session]);

  async function loadContext(){
    setMessage("");const {data,error}=await supabase.rpc("get_my_labaflow_context");if(error){setMessage(error.message);return}
    const next=(data??{}) as Context;setContext(next);if(next.organization){setOrderBranch(next.branches?.[0]?.id??"");await Promise.all([loadCustomers(),loadServices(),loadOrders()])}
  }
  async function loadCustomers(){const {data,error}=await supabase.from("customers").select("id,customer_code,full_name,mobile,email,loyalty_points,lifetime_visits,lifetime_spend,created_at").eq("active",true).order("created_at",{ascending:false}).limit(200);if(error){setMessage(error.message);return}setCustomers((data??[]) as Customer[])}
  async function loadServices(){const {data,error}=await supabase.from("services").select("id,name,description,pricing_unit,default_price,active").eq("active",true).order("name");if(error){setMessage(error.message);return}setServices((data??[]).map((s:any)=>({...s,default_price:Number(s.default_price)})) as Service[])}
  async function loadOrders(){const {data,error}=await supabase.from("laundry_orders").select("id,order_code,branch_id,customer_id,status,payment_status,subtotal,discount,total,amount_paid,notes,due_at,created_at,customers(full_name,customer_code)").order("created_at",{ascending:false}).limit(100);if(error){setMessage(error.message);return}setOrders((data??[]).map((o:any)=>({...o,subtotal:Number(o.subtotal),discount:Number(o.discount),total:Number(o.total),amount_paid:Number(o.amount_paid)})) as Order[])}

  async function signIn(e:FormEvent){e.preventDefault();setMessage("");const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage(error.message)}
  async function signUp(){setMessage("");if(!email.trim()){setMessage("Enter your email address before creating an account.");return}if(password.length<8){setMessage("Use a password with at least 8 characters.");return}const {error}=await supabase.auth.signUp({email:email.trim(),password});setMessage(error?error.message:"Account created. Check your email if confirmation is enabled, then sign in.")}
  async function createOrganization(e:FormEvent){e.preventDefault();setMessage("");const {error}=await supabase.rpc("create_organization_with_main_branch",{p_name:orgForm.name,p_slug:orgForm.slug,p_branch_name:orgForm.branch_name,p_branch_code:orgForm.branch_code});if(error){setMessage(error.message);return}await loadContext()}
  async function createCustomer(e:FormEvent){e.preventDefault();setMessage("");const {data,error}=await supabase.rpc("create_customer_with_qr",{p_full_name:customerForm.full_name,p_mobile:customerForm.mobile||null,p_email:customerForm.email||null,p_preferred_branch_id:customerForm.preferred_branch_id||null});if(error){setMessage(error.message);return}const result=data as {customer:Customer;qr_token:string};setCustomerForm({full_name:"",mobile:"",email:"",preferred_branch_id:""});setShowCustomer(false);await loadCustomers();await showQr(result.customer,result.qr_token)}
  async function createService(e:FormEvent){e.preventDefault();setMessage("");const {error}=await supabase.rpc("create_laundry_service",{p_name:serviceForm.name,p_description:serviceForm.description||null,p_pricing_unit:serviceForm.pricing_unit,p_default_price:Number(serviceForm.default_price)});if(error){setMessage(error.message);return}setServiceForm({name:"",description:"",pricing_unit:"kg",default_price:""});setShowService(false);await loadServices()}

  async function showCustomerQr(customer:Customer){const {data,error}=await supabase.rpc("get_customer_qr",{p_customer_id:customer.id});if(error){setMessage(error.message);return}const result=data as {customer:Customer;qr_token:string};await showQr(result.customer,result.qr_token)}
  async function showQr(customer:Customer,token:string){const image=await QRCode.toDataURL(`labaflow:${token}`,{width:360,margin:2,errorCorrectionLevel:"M"});setQrProfile({customer,token,image})}
  async function lookupQr(){const token=scanToken.trim().replace(/^labaflow:/i,"");if(!token){setMessage("Enter or scan a LabaFlow QR token.");return}const {data,error}=await supabase.rpc("lookup_customer_by_qr",{p_token:token});if(error){setMessage(error.message);return}const c=data as Customer;setScanToken("");setOrderCustomer(c.id);setView("newOrder");setMessage(`Customer selected: ${c.full_name}`)}
  async function adjustPoints(customer:Customer,points:number){const {error}=await supabase.rpc("adjust_customer_loyalty",{p_customer_id:customer.id,p_points:points,p_description:points>0?"Manual loyalty award":"Reward redemption",p_branch_id:context.branches?.[0]?.id??null});if(error){setMessage(error.message);return}await loadCustomers()}

  function addService(service:Service){setCart(current=>{const found=current.find(x=>x.service_id===service.id);return found?current.map(x=>x.service_id===service.id?{...x,quantity:x.quantity+1}:x):[...current,{service_id:service.id,quantity:1}]})}
  function setQty(serviceId:string,qty:number){setCart(current=>qty<=0?current.filter(x=>x.service_id!==serviceId):current.map(x=>x.service_id===serviceId?{...x,quantity:qty}:x))}
  const cartSubtotal=cart.reduce((sum,item)=>{const s=services.find(x=>x.id===item.service_id);return sum+(s?s.default_price*item.quantity:0)},0);
  const cartTotal=Math.max(cartSubtotal-(Number(orderDiscount)||0),0);
  async function createOrder(e:FormEvent){e.preventDefault();setMessage("");if(!orderBranch){setMessage("Select a branch.");return}if(!cart.length){setMessage("Add at least one service.");return}const {data,error}=await supabase.rpc("create_laundry_order",{p_branch_id:orderBranch,p_customer_id:orderCustomer||null,p_items:cart.map(x=>({service_id:x.service_id,quantity:x.quantity})),p_discount:Number(orderDiscount)||0,p_notes:orderNotes||null,p_due_at:null});if(error){setMessage(error.message);return}setCart([]);setOrderNotes("");setOrderDiscount("0");await loadOrders();setView("orders");setMessage(`Order ${(data as Order).order_code} created.`)}
  async function updateStatus(order:Order,status:string){const {error}=await supabase.rpc("update_order_status",{p_order_id:order.id,p_status:status,p_notes:null});if(error){setMessage(error.message);return}await Promise.all([loadOrders(),loadCustomers()])}
  async function recordPayment(order:Order){const form=payment[order.id]??{amount:"",method:"cash",reference:""};const amount=Number(form.amount);if(!amount){setMessage("Enter a payment amount.");return}const {error}=await supabase.rpc("record_order_payment",{p_order_id:order.id,p_amount:amount,p_method:form.method,p_reference:form.reference||null});if(error){setMessage(error.message);return}setPayment(p=>({...p,[order.id]:{amount:"",method:form.method,reference:""}}));await loadOrders()}

  const stats=useMemo(()=>({customers:customers.length,points:customers.reduce((s,c)=>s+c.loyalty_points,0),todayOrders:orders.filter(o=>o.created_at.slice(0,10)===new Date().toISOString().slice(0,10)).length,ready:orders.filter(o=>o.status==="ready").length,revenue:orders.filter(o=>o.payment_status==="paid").reduce((s,o)=>s+o.total,0)}),[customers,orders]);
  const statusCounts=Object.fromEntries(statuses.map(s=>[s,orders.filter(o=>o.status===s).length]));

  if(checking)return <main className="center"><div className="loader">Loading LabaFlow…</div></main>;
  if(!session)return <main className="authPage"><section className="brandPanel"><div className="logoMark">LF</div><h1>LabaFlow</h1><p>Laundry management, simplified.</p><div className="washGraphic"><span/><span/><span/></div></section><section className="authCard"><p className="eyebrow">WELCOME</p><h2>Sign in to your laundry workspace</h2><p className="muted">Manage customers, loyalty, branches, orders, and daily operations from one place.</p><form onSubmit={signIn} className="stack"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Sign In</button><button type="button" className="secondary" onClick={signUp}>Create Account</button></form>{message&&<p className="notice">{message}</p>}</section></main>;
  if(!context.organization)return <main className="onboarding"><section className="onboardCard"><div className="logoMark">LF</div><p className="eyebrow">FIRST-TIME SETUP</p><h1>Create your LabaFlow organization</h1><p className="muted">Your first branch and loyalty program will be created automatically.</p><form onSubmit={createOrganization} className="gridForm"><label>Business name<input value={orgForm.name} onChange={e=>setOrgForm({...orgForm,name:e.target.value,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")})} required/></label><label>Organization slug<input value={orgForm.slug} onChange={e=>setOrgForm({...orgForm,slug:e.target.value})} required/></label><label>Main branch name<input value={orgForm.branch_name} onChange={e=>setOrgForm({...orgForm,branch_name:e.target.value})} required/></label><label>Branch code<input value={orgForm.branch_code} onChange={e=>setOrgForm({...orgForm,branch_code:e.target.value.toUpperCase()})} required/></label><button className="primary wide">Create Organization</button></form>{message&&<p className="notice">{message}</p>}</section></main>;

  const title=view==="dashboard"?"Good day — here’s your laundry flow.":view==="newOrder"?"New Laundry Order":view==="orders"?"Laundry Orders":view==="customers"?"Customers":view==="loyalty"?"Customer Loyalty":view==="services"?"Services & Pricing":"Organization Settings";
  return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="logoMark small">LF</div><div><strong>LabaFlow</strong><small>{context.organization.name}</small></div></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>Dashboard</button><button className={view==="newOrder"?"active":""} onClick={()=>setView("newOrder")}>New Order</button><button className={view==="orders"?"active":""} onClick={()=>setView("orders")}>Orders</button><button className={view==="customers"?"active":""} onClick={()=>setView("customers")}>Customers</button><button className={view==="loyalty"?"active":""} onClick={()=>setView("loyalty")}>Loyalty</button><button className={view==="services"?"active":""} onClick={()=>setView("services")}>Services & Pricing</button><button disabled>Pickup & Delivery <span>Soon</span></button><hr/><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}>Organization Settings</button></nav><div className="sidebarFooter"><small>{session.user.email}</small><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside>

  <main className="workspace"><header><div><p className="eyebrow">{context.branches?.find(b=>b.id===orderBranch)?.name??context.branches?.[0]?.name??"LabaFlow"}</p><h1>{title}</h1></div><div className="headerActions"><button className="secondary" onClick={()=>setShowCustomer(true)}>+ Customer</button>{view==="services"&&<button className="primary" onClick={()=>setShowService(true)}>+ Service</button>}{view!=="services"&&<button className="primary" onClick={()=>setView("newOrder")}>+ New Order</button>}</div></header>{message&&<p className="notice">{message}</p>}

  {view==="dashboard"&&<><section className="stats"><article><span>Today's Orders</span><strong>{stats.todayOrders}</strong><small>Created today</small></article><article><span>Ready for Pickup</span><strong>{stats.ready}</strong><small>Waiting for customers</small></article><article><span>Customers</span><strong>{stats.customers}</strong><small>Registered profiles</small></article><article><span>Paid Revenue</span><strong>{peso.format(stats.revenue)}</strong><small>Paid orders</small></article></section><section className="panel"><p className="eyebrow">CUSTOMER LOOKUP</p><h2>Scan or paste a customer QR</h2><div className="scanBar"><input placeholder="Scan QR here or paste LabaFlow token" value={scanToken} onChange={e=>setScanToken(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")lookupQr()}}/><button className="primary" onClick={lookupQr}>Start Order</button></div></section><section className="panel"><div className="panelHead"><div><p className="eyebrow">OPERATIONS</p><h2>Laundry Workflow</h2></div><small>{orders.filter(o=>!["completed","cancelled"].includes(o.status)).length} active orders</small></div><div className="workflow">{["received","sorting","washing","drying","folding","ready"].map((x,i)=><div key={x}><span>{i+1}</span><strong>{statusLabel(x)}</strong><b>{statusCounts[x]??0}</b></div>)}</div></section></>}

  {view==="services"&&<section className="panel"><div className="panelHead"><div><p className="eyebrow">CATALOG</p><h2>Services & Pricing</h2></div><span>{services.length} active services</span></div>{services.length?<div className="serviceGrid">{services.map(s=><article key={s.id}><div><strong>{s.name}</strong><small>{s.description||"Laundry service"}</small></div><b>{peso.format(s.default_price)}</b><span>per {s.pricing_unit}</span></article>)}</div>:<p className="empty">Create your first laundry service, such as Wash + Dry + Fold.</p>}</section>}

  {view==="newOrder"&&<form onSubmit={createOrder}><section className="twoCols orderLayout"><article className="panel"><p className="eyebrow">1. CUSTOMER & BRANCH</p><h2>Order details</h2><div className="gridForm"><label>Customer<select value={orderCustomer} onChange={e=>setOrderCustomer(e.target.value)}><option value="">Walk-in / No customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.full_name} — {c.customer_code}</option>)}</select></label><label>Branch<select value={orderBranch} onChange={e=>setOrderBranch(e.target.value)} required>{context.branches?.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label className="wide">Notes<textarea value={orderNotes} onChange={e=>setOrderNotes(e.target.value)} placeholder="Special instructions, stain notes, rush request..."/></label></div><p className="eyebrow servicePickerLabel">2. SELECT SERVICES</p><div className="servicePicker">{services.map(s=><button type="button" key={s.id} onClick={()=>addService(s)}><strong>{s.name}</strong><small>{peso.format(s.default_price)} / {s.pricing_unit}</small></button>)}</div></article><article className="panel orderSummary"><p className="eyebrow">3. ORDER SUMMARY</p><h2>Services</h2>{cart.length?cart.map(item=>{const s=services.find(x=>x.id===item.service_id)!;return <div className="cartRow" key={item.service_id}><div><strong>{s.name}</strong><small>{peso.format(s.default_price)} / {s.pricing_unit}</small></div><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>setQty(item.service_id,Number(e.target.value))}/><b>{peso.format(s.default_price*item.quantity)}</b></div>}):<p className="empty">Select services to build the order.</p>}<div className="totals"><label>Discount<input type="number" min="0" step="0.01" value={orderDiscount} onChange={e=>setOrderDiscount(e.target.value)}/></label><div><span>Subtotal</span><b>{peso.format(cartSubtotal)}</b></div><div className="grand"><span>Total</span><b>{peso.format(cartTotal)}</b></div></div><button className="primary wide" disabled={!cart.length}>Create Laundry Order</button></article></section></form>}

  {view==="orders"&&<section className="panel"><div className="panelHead"><div><p className="eyebrow">OPERATIONS</p><h2>Order Queue</h2></div><span>{orders.length} orders</span></div>{orders.length?<div className="orderList">{orders.map(o=>{const p=payment[o.id]??{amount:"",method:"cash",reference:""};const idx=statuses.indexOf(o.status);const next=statuses[Math.min(Math.max(idx,0)+1,statuses.length-1)];return <article className="orderCard" key={o.id}><div className="orderTop"><div><strong>{o.order_code}</strong><small>{o.customers?.full_name??"Walk-in customer"} · {new Date(o.created_at).toLocaleString()}</small></div><div><span className={`status ${o.status}`}>{statusLabel(o.status)}</span><b>{peso.format(o.total)}</b></div></div><div className="orderMeta"><span>Paid: <b>{peso.format(o.amount_paid)}</b></span><span>Balance: <b>{peso.format(Math.max(o.total-o.amount_paid,0))}</b></span><span>Payment: <b>{statusLabel(o.payment_status)}</b></span></div><div className="orderActions">{o.status!=="completed"&&o.status!=="cancelled"&&<button type="button" className="secondary" onClick={()=>updateStatus(o,next)}>{next==="completed"?"Complete Order":`Move to ${statusLabel(next)}`}</button>}<select value={p.method} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,method:e.target.value}}))}><option value="cash">Cash</option><option value="gcash">GCash</option><option value="maya">Maya</option><option value="card">Card</option><option value="bank_transfer">Bank Transfer</option></select><input type="number" placeholder="Payment amount" value={p.amount} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,amount:e.target.value}}))}/><button type="button" className="primary" onClick={()=>recordPayment(o)}>Record Payment</button></div></article>})}</div>:<p className="empty">No laundry orders yet.</p>}</section>}

  {view==="customers"&&<section className="panel"><div className="panelHead"><div><p className="eyebrow">CRM</p><h2>Customer Directory</h2></div><span>{customers.length} customers</span></div>{customers.length?<div className="table"><div className="tableHeader"><span>Customer</span><span>Contact</span><span>Loyalty</span><span>QR</span></div>{customers.map(c=><div className="tableRow" key={c.id}><span><strong>{c.full_name}</strong><small>{c.customer_code}</small></span><span>{c.mobile||c.email||"—"}</span><span><b>{c.loyalty_points}</b> pts</span><span><button className="miniBtn" onClick={()=>showCustomerQr(c)}>Show QR</button></span></div>)}</div>:<p className="empty">No customers yet.</p>}</section>}
  {view==="loyalty"&&<section className="panel"><div className="panelHead"><div><p className="eyebrow">REWARDS</p><h2>Loyalty Accounts</h2></div><span>{stats.points} total points</span></div>{customers.map(c=><div className="loyaltyRow" key={c.id}><div><strong>{c.full_name}</strong><small>{c.customer_code} · {c.lifetime_visits} visits · {peso.format(c.lifetime_spend)} lifetime spend</small></div><div className="points">{c.loyalty_points} pts</div><div className="actions"><button onClick={()=>adjustPoints(c,10)}>+10</button><button disabled={c.loyalty_points<10} onClick={()=>adjustPoints(c,-10)}>-10</button><button onClick={()=>showCustomerQr(c)}>QR</button></div></div>)}</section>}
  {view==="settings"&&<section className="panel"><p className="eyebrow">ADMINISTRATION</p><h2>{context.organization.name}</h2><div className="settingsGrid"><div><span>Organization slug</span><strong>{context.organization.slug}</strong></div><div><span>Your role</span><strong>{context.membership?.role??"Member"}</strong></div><div><span>Branches</span><strong>{context.branches?.length??0}</strong></div><div><span>Loyalty</span><strong>Enabled</strong></div></div><h3>Configured modules</h3><div className="featureList">{["Customer loyalty","Services & pricing","Laundry orders","Payments","Order workflow","Pickup & delivery","Inventory","Expenses"].map((f,i)=><div key={f}><span>{f}</span><b>{i<5?"Enabled":"Planned"}</b></div>)}</div></section>}
  </main>

  {showCustomer&&<div className="modalBackdrop" onMouseDown={()=>setShowCustomer(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><p className="eyebrow">NEW CUSTOMER</p><h2>Create customer profile</h2></div><button className="iconBtn" onClick={()=>setShowCustomer(false)}>×</button></div><form onSubmit={createCustomer} className="gridForm"><label>Full name<input value={customerForm.full_name} onChange={e=>setCustomerForm({...customerForm,full_name:e.target.value})} required/></label><label>Mobile<input value={customerForm.mobile} onChange={e=>setCustomerForm({...customerForm,mobile:e.target.value})}/></label><label>Email<input type="email" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/></label><label>Preferred branch<select value={customerForm.preferred_branch_id} onChange={e=>setCustomerForm({...customerForm,preferred_branch_id:e.target.value})}><option value="">None</option>{context.branches?.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary wide">Create Customer + QR</button></form></section></div>}
  {showService&&<div className="modalBackdrop" onMouseDown={()=>setShowService(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><p className="eyebrow">NEW SERVICE</p><h2>Add laundry service</h2></div><button className="iconBtn" onClick={()=>setShowService(false)}>×</button></div><form onSubmit={createService} className="gridForm"><label>Service name<input value={serviceForm.name} onChange={e=>setServiceForm({...serviceForm,name:e.target.value})} placeholder="Wash + Dry + Fold" required/></label><label>Pricing unit<select value={serviceForm.pricing_unit} onChange={e=>setServiceForm({...serviceForm,pricing_unit:e.target.value})}><option value="kg">Per kg</option><option value="piece">Per piece</option><option value="load">Per load</option><option value="package">Package</option></select></label><label>Default price<input type="number" min="0" step="0.01" value={serviceForm.default_price} onChange={e=>setServiceForm({...serviceForm,default_price:e.target.value})} required/></label><label>Description<input value={serviceForm.description} onChange={e=>setServiceForm({...serviceForm,description:e.target.value})}/></label><button className="primary wide">Create Service</button></form></section></div>}
  {qrProfile&&<div className="modalBackdrop" onMouseDown={()=>setQrProfile(null)}><section className="modal qrModal" onMouseDown={e=>e.stopPropagation()}><div className="panelHead noPrint"><div><p className="eyebrow">CUSTOMER ID</p><h2>{qrProfile.customer.full_name}</h2></div><button className="iconBtn" onClick={()=>setQrProfile(null)}>×</button></div><div className="customerCard"><div className="cardBrand"><div className="logoMark small">LF</div><div><strong>LabaFlow</strong><small>{context.organization.name}</small></div></div><img src={qrProfile.image} alt={`QR code for ${qrProfile.customer.full_name}`}/><h2>{qrProfile.customer.full_name}</h2><strong className="customerCode">{qrProfile.customer.customer_code}</strong><div className="cardStats"><span><b>{qrProfile.customer.loyalty_points}</b> points</span><span><b>{qrProfile.customer.lifetime_visits}</b> visits</span></div><small>Present this QR at the counter for quick customer lookup and loyalty tracking.</small></div><div className="qrActions noPrint"><button className="primary" onClick={()=>window.print()}>Print Customer Card</button><button className="secondary" onClick={()=>{setOrderCustomer(qrProfile.customer.id);setQrProfile(null);setView("newOrder")}}>Start New Order</button></div></section></div>}
  </div>;
}
