"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
type Product={id:string;name:string;sku:string|null;barcode:string|null;selling_price:number;branch_id:string;branch_name:string;quantity:number;active:boolean};
type Pick={product_id:string;quantity:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
export default function ProductSalesEnhancer(){
 const [products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Pick[]>([]),[branchId,setBranchId]=useState(""),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{if(!location.pathname.startsWith("/new-order"))return;void load();const timer=setInterval(syncBranch,600);return()=>clearInterval(timer)},[]);
 async function load(){const {data,error}=await supabase.rpc("get_products_inventory");if(error){setMessage(error.message);return}setProducts((data??[]).map((x:any)=>({...x,selling_price:Number(x.selling_price),quantity:Number(x.quantity)})).filter((x:any)=>x.active));syncBranch()}
 function syncBranch(){const sel=document.querySelector<HTMLSelectElement>('.orderDetailsPanel select[required]');if(sel?.value)setBranchId(sel.value)}
 function qty(id:string){return cart.find(x=>x.product_id===id)?.quantity??0}
 function setQty(p:Product,n:number){const next=Math.max(0,Math.min(Math.floor(n),Math.floor(p.quantity)));setCart(c=>next<=0?c.filter(x=>x.product_id!==p.id):c.some(x=>x.product_id===p.id)?c.map(x=>x.product_id===p.id?{...x,quantity:next}:x):[...c,{product_id:p.id,quantity:next}])}
 const visible=useMemo(()=>products.filter(p=>(!branchId||p.branch_id===branchId)&&p.quantity>0&&(`${p.name} ${p.sku??""} ${p.barcode??""}`).toLowerCase().includes(search.toLowerCase())),[products,branchId,search]);
 const total=cart.reduce((n,x)=>n+(products.find(p=>p.id===x.product_id)?.selling_price??0)*x.quantity,0);
 useEffect(()=>{const form=document.querySelector<HTMLFormElement>('.newOrderExperience form');if(!form)return;const handler=async(e:SubmitEvent)=>{if(!cart.length)return;const submitter=e.submitter as HTMLButtonElement|null;if(submitter?.dataset.productResume==="1")return;e.preventDefault();e.stopImmediatePropagation();setMessage("Creating laundry order, then adding products…");const once=async()=>{for(let tries=0;tries<30;tries++){await new Promise(r=>setTimeout(r,100));const href=location.href;const m=href.match(/\/order-details\?id=([^&]+)/);if(m){const orderId=decodeURIComponent(m[1]);const {error}=await supabase.rpc("add_products_to_order",{p_order_id:orderId,p_products:cart});if(error){sessionStorage.setItem("labaflow.product-sale-error",error.message);return}sessionStorage.removeItem("labaflow.pending-products");return}}};sessionStorage.setItem("labaflow.pending-products",JSON.stringify(cart));form.removeEventListener("submit",handler,true);const hidden=document.createElement("button");hidden.type="submit";hidden.style.display="none";hidden.dataset.productResume="1";form.appendChild(hidden);hidden.click();void once()};form.addEventListener("submit",handler,true);return()=>form.removeEventListener("submit",handler,true)},[cart]);
 if(!products.length)return null;
 return <section className="panel" style={{marginTop:16}}><div className="panelHead"><div><p className="eyebrow">RETAIL PRODUCTS</p><h2>Add Laundry Products</h2><span>Optional items for self-service customers</span></div>{total>0&&<strong>{peso.format(total)}</strong>}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product, SKU or barcode…"/><div className="servicePicker" style={{marginTop:12}}>{visible.map(p=>{const n=qty(p.id);return <div className={`mobileServiceCard ${n?"selected":""}`} key={`${p.id}-${p.branch_id}`}><div className="serviceMain"><span className="serviceGlyph">▣</span><span><strong>{p.name}</strong><small>{peso.format(p.selling_price)} · {p.quantity} in stock</small></span></div><div className="qtyStepper"><button type="button" onClick={()=>setQty(p,n-1)}>−</button><b>{n}</b><button type="button" onClick={()=>setQty(p,n+1)} disabled={n>=p.quantity}>+</button></div></div>})}</div>{!visible.length&&<p className="empty">No in-stock products for the selected branch.</p>}{message&&<p className="notice">{message}</p>}<p className="muted" style={{marginTop:10}}>Product stock is reserved and deducted when the order is created. Product total will be added to the order total.</p></section>
}
