"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";

type Branch={id:string;name:string};
type Customer={id:string;full_name:string;customer_code:string};
type Service={id:string;name:string;pricing_unit:string;default_price:number;loyalty_points:number};
type AddonType="pickup"|"delivery"|"pickup_delivery";
type Rate={id:string;addon_type:AddonType;label:string;min_km:number;max_km:number|null;price:number};
type CartItem={service_id:string;quantity:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const addonLabels:Record<AddonType,string>={pickup:"Pickup",delivery:"Delivery",pickup_delivery:"Pickup + Delivery"};

export default function NewOrderPage(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState("");
 const [branches,setBranches]=useState<Branch[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[services,setServices]=useState<Service[]>([]),[rates,setRates]=useState<Rate[]>([]);
 const [branchId,setBranchId]=useState(""),[customerId,setCustomerId]=useState(""),[notes,setNotes]=useState(""),[discount,setDiscount]=useState("0"),[cart,setCart]=useState<CartItem[]>([]);
 const [addon,setAddon]=useState<{type:AddonType;rate:Rate}|null>(null),[showDistance,setShowDistance]=useState<AddonType|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const [a,c,s,r]=await Promise.all([supabase.rpc("get_current_access_context"),supabase.from("customers").select("id,full_name,customer_code").eq("active",true).order("full_name"),supabase.from("services").select("id,name,pricing_unit,default_price,loyalty_points").eq("active",true).order("name"),supabase.rpc("get_delivery_distance_rates",{p_addon_type:null})]);if(a.error||c.error||s.error||r.error){setMessage(a.error?.message||c.error?.message||s.error?.message||r.error?.message||"");return}const bs=(a.data?.branches??[]) as Branch[];setBranches(bs);setBranchId(bs[0]?.id??"");setCustomers((c.data??[]) as Customer[]);setServices((s.data??[]).map((x:any)=>({...x,default_price:Number(x.default_price),loyalty_points:Number(x.loyalty_points??0)})));setRates((r.data??[]).map((x:any)=>({...x,min_km:Number(x.min_km),max_km:x.max_km==null?null:Number(x.max_km),price:Number(x.price)})))}
 function addService(s:Service){setCart(x=>{const found=x.find(i=>i.service_id===s.id);return found?x.map(i=>i.service_id===s.id?{...i,quantity:i.quantity+1}:i):[...x,{service_id:s.id,quantity:1}]})}
 const serviceSubtotal=useMemo(()=>cart.reduce((n,i)=>n+(services.find(s=>s.id===i.service_id)?.default_price??0)*i.quantity,0),[cart,services]);
 const deliveryFee=addon?.rate.price??0;
 const total=Math.max(serviceSubtotal+deliveryFee-(Number(discount)||0),0);
 const ratesForType=(type:AddonType)=>rates.filter(r=>r.addon_type===type);
 async function createOrder(e:FormEvent){e.preventDefault();if(!cart.length){setMessage("Add at least one laundry service.");return}if(addon&&!customerId){setMessage("Pickup/Delivery requires a registered customer.");return}const {data,error}=await supabase.rpc("create_laundry_order",{p_branch_id:branchId,p_customer_id:customerId||null,p_items:cart,p_discount:Number(discount)||0,p_notes:notes||null,p_due_at:null,p_delivery_addon_type:addon?.type??null,p_delivery_distance_rate_id:addon?.rate.id??null});if(error){setMessage(error.message);return}setMessage(`Order ${data.order_code} created${addon?` with ${addonLabels[addon.type]} add-on (${addon.rate.label}).`:"."}`);setCart([]);setDiscount("0");setNotes("");setAddon(null)}
 function chooseAddon(type:AddonType){if(!customerId){setMessage("Select a registered customer before adding Pickup/Delivery.");return}const available=ratesForType(type);if(!available.length){setMessage(`No ${addonLabels[type]} distance rates are configured. Ask an organization admin to configure them first.`);return}setShowDistance(type)}
 if(checking)return <main className="center"><div className="loader">Loading order form…</div></main>;
 if(!session)return <main className="center"><section className="onboardCard"><h2>Sign in required</h2><button className="primary" onClick={()=>location.href="/"}>Back to LabaFlow</button></section></main>;
 return <main className="workspace"><div className="panelHead"><div><p className="eyebrow">NEW ORDER</p><h1>Laundry Order</h1><p className="muted">Add laundry services and optional Pickup/Delivery distance pricing.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/"}>LabaFlow</button><button className="secondary" onClick={()=>location.href="/pickup-delivery"}>Dispatch Board</button></div></div>{message&&<p className="notice">{message}</p>}
 <form onSubmit={createOrder}><section className="twoCols orderLayout"><article className="panel"><h2>Order Details</h2><div className="gridForm"><label>Customer<select value={customerId} onChange={e=>{setCustomerId(e.target.value);if(!e.target.value)setAddon(null)}}><option value="">Walk-in / No customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name} — {c.customer_code}</option>)}</select></label><label>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)} required>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="wide">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>
 <h3>Laundry Services</h3><div className="servicePicker">{services.map(s=><button type="button" key={s.id} onClick={()=>addService(s)}><strong>{s.name}</strong><small>{peso.format(s.default_price)} / {s.pricing_unit}{s.loyalty_points?` · +${s.loyalty_points} pts`:""}</small></button>)}</div>
 <h3>Order Add-ons</h3><div className="servicePicker"><button type="button" onClick={()=>chooseAddon("pickup")}><strong>Pickup</strong><small>Collect laundry from customer · {ratesForType("pickup").length} pricing options</small></button><button type="button" onClick={()=>chooseAddon("delivery")}><strong>Delivery</strong><small>Deliver finished laundry · {ratesForType("delivery").length} pricing options</small></button><button type="button" onClick={()=>chooseAddon("pickup_delivery")}><strong>Pickup + Delivery</strong><small>Round-trip service · {ratesForType("pickup_delivery").length} pricing options</small></button></div>{addon&&<div className="notice"><strong>{addonLabels[addon.type]}</strong> · {addon.rate.label} · {peso.format(addon.rate.price)} <button type="button" className="miniBtn" onClick={()=>setAddon(null)}>Remove</button></div>}</article>
 <article className="panel orderSummary"><h2>Summary</h2>{cart.length?cart.map(i=>{const s=services.find(x=>x.id===i.service_id)!;return <div className="cartRow" key={i.service_id}><div><strong>{s.name}</strong><small>{peso.format(s.default_price)} / {s.pricing_unit}</small></div><input type="number" min="0.01" step="0.01" value={i.quantity} onChange={e=>setCart(x=>x.map(z=>z.service_id===i.service_id?{...z,quantity:Number(e.target.value)}:z))}/><b>{peso.format(s.default_price*i.quantity)}</b></div>}):<p className="empty">Select laundry services.</p>}{addon&&<div className="cartRow"><div><strong>{addonLabels[addon.type]} Add-on</strong><small>{addon.rate.label}</small></div><span>1</span><b>{peso.format(deliveryFee)}</b></div>}<div className="totals"><label>Discount<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><div><span>Laundry services</span><b>{peso.format(serviceSubtotal)}</b></div><div><span>Pickup/Delivery</span><b>{peso.format(deliveryFee)}</b></div><div className="grand"><span>Total</span><b>{peso.format(total)}</b></div></div><button className="primary wide" disabled={!cart.length}>Create Laundry Order</button></article></section></form>
 {showDistance&&<div className="modalBackdrop" onMouseDown={()=>setShowDistance(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><p className="eyebrow">{addonLabels[showDistance]}</p><h2>Select Distance</h2></div><button className="iconBtn" onClick={()=>setShowDistance(null)}>×</button></div><p className="muted">These prices are configured specifically for {addonLabels[showDistance]}.</p><div className="serviceGrid">{ratesForType(showDistance).map(r=><article key={r.id}><strong>{r.label}</strong><small>{r.min_km} km – {r.max_km==null?"No limit":`${r.max_km} km`}</small><b>{peso.format(r.price)}</b><button type="button" className="primary" onClick={()=>{setAddon({type:showDistance,rate:r});setShowDistance(null)}}>Select</button></article>)}</div></section></div>}
 </main>;
}
