"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";

type Branch={id:string;name:string};
type Order={id:string;order_code:string;branch_id:string;customer_id:string|null;subtotal:number;discount:number;total:number;amount_paid:number;payment_status:string;status:string;created_at:string;customers:{full_name:string}|null};
type Payment={id:string;order_id:string;branch_id:string;amount:number;method:string|null;reference:string|null;created_at:string};
type Preset="daily"|"weekly"|"monthly"|"all"|"custom";
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const methods=["cash","gcash","maya","card","bank_transfer","qrph"];
const label=(v:string|null|undefined)=>{const s=String(v??"").trim();if(!s)return "Unspecified";return s==="qrph"?"QR Ph":s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())};
const iso=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
function presetRange(p:Preset){const today=new Date();if(p==="all")return {start:"",end:""};if(p==="daily")return {start:iso(today),end:iso(today)};if(p==="weekly"){const s=new Date(today);s.setDate(today.getDate()-6);return {start:iso(s),end:iso(today)}}if(p==="monthly"){const s=new Date(today.getFullYear(),today.getMonth(),1);return {start:iso(s),end:iso(today)}}return {start:iso(today),end:iso(today)}}

export default function ReportsPage(){
 const initial=presetRange("daily");
 const [preset,setPreset]=useState<Preset>("daily"),[startDate,setStartDate]=useState(initial.start),[endDate,setEndDate]=useState(initial.end),[branch,setBranch]=useState("all"),[method,setMethod]=useState("all"),[status,setStatus]=useState("all"),[branches,setBranches]=useState<Branch[]>([]),[orders,setOrders]=useState<Order[]>([]),[payments,setPayments]=useState<Payment[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[showTransactions,setShowTransactions]=useState(true),[showCollections,setShowCollections]=useState(true),[showMethods,setShowMethods]=useState(true);
 useEffect(()=>{void load()},[startDate,endDate,branch]);
 async function load(){if(!navigator.onLine){setMessage("Reports require internet so figures reflect synchronized transactions.");setLoading(false);return}setLoading(true);setMessage("");const access=await supabase.rpc("get_current_access_context");if(access.error){setMessage(access.error.message);setLoading(false);return}setBranches(access.data?.branches??[]);
  let oq=supabase.from("laundry_orders").select("id,order_code,branch_id,customer_id,subtotal,discount,total,amount_paid,payment_status,status,created_at,customers(full_name)").order("created_at",{ascending:false});
  let pq=supabase.from("payments").select("id,order_id,branch_id,amount,method,reference,created_at").order("created_at",{ascending:false});
  if(startDate){oq=oq.gte("created_at",`${startDate}T00:00:00+08:00`);pq=pq.gte("created_at",`${startDate}T00:00:00+08:00`)}
  if(endDate){const e=new Date(`${endDate}T00:00:00+08:00`);e.setDate(e.getDate()+1);const end=e.toISOString();oq=oq.lt("created_at",end);pq=pq.lt("created_at",end)}
  if(branch!=="all"){oq=oq.eq("branch_id",branch);pq=pq.eq("branch_id",branch)}
  const [o,p]=await Promise.all([oq.limit(5000),pq.limit(5000)]);if(o.error||p.error){setMessage(o.error?.message||p.error?.message||"Unable to load report");setLoading(false);return}
  setOrders((o.data??[]).map((x:any)=>({...x,subtotal:Number(x.subtotal),discount:Number(x.discount),total:Number(x.total),amount_paid:Number(x.amount_paid),customers:Array.isArray(x.customers)?x.customers[0]??null:x.customers??null})));setPayments((p.data??[]).map((x:any)=>({...x,amount:Number(x.amount)})));setLoading(false)
 }
 function choose(p:Preset){setPreset(p);const r=presetRange(p);setStartDate(r.start);setEndDate(r.end)}
 const filteredOrders=useMemo(()=>orders.filter(o=>status==="all"||o.status===status),[orders,status]);
 const filteredPayments=useMemo(()=>payments.filter(p=>method==="all"||p.method===method),[payments,method]);
 const gross=filteredOrders.reduce((n,o)=>n+o.subtotal,0),discounts=filteredOrders.reduce((n,o)=>n+o.discount,0),net=filteredOrders.reduce((n,o)=>n+o.total,0),collected=filteredPayments.reduce((n,p)=>n+p.amount,0),outstanding=filteredOrders.reduce((n,o)=>n+Math.max(o.total-o.amount_paid,0),0),avg=filteredOrders.length?net/filteredOrders.length:0,customers=new Set(filteredOrders.map(o=>o.customer_id).filter(Boolean)).size,walkins=filteredOrders.filter(o=>!o.customer_id).length;
 const byMethod=methods.map(m=>({method:m,amount:payments.filter(p=>p.method===m).reduce((n,p)=>n+p.amount,0)}));
 const reportName=preset==="daily"?"Daily":preset==="weekly"?"Weekly":preset==="monthly"?"Monthly":preset==="all"?"All Time":"Custom";
 function csv(){const rows:any[][]=[[`LabaFlow ${reportName} Report`],["Period",startDate||"Beginning","to",endDate||"Present"],["Branch",branch==="all"?"All Branches":branches.find(b=>b.id===branch)?.name??""],["Gross Sales",gross],["Discounts",discounts],["Net Sales",net],["Collected",collected],["Outstanding",outstanding],["Orders",filteredOrders.length],["Customers",customers],["Walk-ins",walkins],[],["PAYMENT METHODS"],["Method","Amount"],...byMethod.map(x=>[label(x.method),x.amount]),[],["ORDERS"],["Order","Customer","Status","Gross","Discount","Net","Paid","Balance"],...filteredOrders.map(o=>[o.order_code,o.customers?.full_name??"Walk-in",label(o.status),o.subtotal,o.discount,o.total,o.amount_paid,Math.max(o.total-o.amount_paid,0)])];const text=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob([text],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`labaflow-${reportName.toLowerCase().replaceAll(" ","-")}-report.csv`;a.click();URL.revokeObjectURL(url)}
 return <main className="workspace reportsPage"><header className="reportsHeader"><div><p className="eyebrow">REPORTS</p><h1>Reports</h1><p className="muted">Run prefiltered sales reports or customize the period, branch, payment method, status and report sections.</p></div><div className="headerActions"><button className="secondary" onClick={()=>window.print()}>Print</button><button className="primary" onClick={csv}>Export CSV</button></div></header>{message&&<p className="notice">{message}</p>}
 <section className="reportPresets"><button className={preset==="daily"?"active":""} onClick={()=>choose("daily")}><strong>Daily</strong><span>Today</span></button><button className={preset==="weekly"?"active":""} onClick={()=>choose("weekly")}><strong>Weekly</strong><span>Last 7 days</span></button><button className={preset==="monthly"?"active":""} onClick={()=>choose("monthly")}><strong>Monthly</strong><span>This month</span></button><button className={preset==="all"?"active":""} onClick={()=>choose("all")}><strong>All Time</strong><span>Full history</span></button></section>
 <section className="panel reportBuilder"><div className="panelHead"><div><p className="eyebrow">CUSTOMIZE</p><h2>Report Builder</h2><span>{reportName} report</span></div></div><div className="reportFilters"><label>Start Date<input type="date" value={startDate} onChange={e=>{setPreset("custom");setStartDate(e.target.value)}}/></label><label>End Date<input type="date" value={endDate} onChange={e=>{setPreset("custom");setEndDate(e.target.value)}}/></label><label>Branch<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All Branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Payment Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="all">All Methods</option>{methods.map(m=><option key={m} value={m}>{label(m)}</option>)}</select></label><label>Order Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Statuses</option>{[...new Set(orders.map(o=>o.status))].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label></div><div className="reportSections"><label><input type="checkbox" checked={showMethods} onChange={e=>setShowMethods(e.target.checked)}/> Payment Method Summary</label><label><input type="checkbox" checked={showTransactions} onChange={e=>setShowTransactions(e.target.checked)}/> Sales Transactions</label><label><input type="checkbox" checked={showCollections} onChange={e=>setShowCollections(e.target.checked)}/> Collection Transactions</label></div></section>
 {loading?<p>Loading report…</p>:<><section className="stats reportStats"><article><span>Gross Sales</span><strong>{peso.format(gross)}</strong></article><article><span>Discounts</span><strong>{peso.format(discounts)}</strong></article><article><span>Net Sales</span><strong>{peso.format(net)}</strong></article><article><span>Collected</span><strong>{peso.format(collected)}</strong></article><article><span>Outstanding</span><strong>{peso.format(outstanding)}</strong></article><article><span>Orders</span><strong>{filteredOrders.length}</strong></article><article><span>Customers</span><strong>{customers}</strong></article><article><span>Avg. Order</span><strong>{peso.format(avg)}</strong></article></section>
 {showMethods&&<section className="panel reportSection"><div className="panelHead"><div><h2>Collections by Payment Method</h2><span>{reportName} collection mix</span></div></div><div className="paymentSummary">{byMethod.map(x=><article key={x.method}><span>{label(x.method)}</span><strong>{peso.format(x.amount)}</strong></article>)}</div></section>}
 {showTransactions&&<section className="panel reportSection"><div className="panelHead"><div><h2>Sales Transactions</h2><span>{customers} registered customers · {walkins} walk-in orders</span></div></div><div className="customerTableWrap"><table className="customerTable reportTable"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Net</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{filteredOrders.map(o=><tr key={o.id}><td><strong>{o.order_code}</strong></td><td>{o.customers?.full_name??"Walk-in"}</td><td>{label(o.status)}</td><td><strong>{peso.format(o.total)}</strong></td><td>{peso.format(o.amount_paid)}</td><td>{peso.format(Math.max(o.total-o.amount_paid,0))}</td></tr>)}</tbody></table></div></section>}
 {showCollections&&<section className="panel reportSection"><div className="panelHead"><div><h2>Collection Transactions</h2><span>{filteredPayments.length} payment transactions</span></div></div><div className="customerTableWrap"><table className="customerTable reportTable"><thead><tr><th>Date</th><th>Order</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{filteredPayments.map(p=><tr key={p.id}><td>{new Date(p.created_at).toLocaleString("en-PH")}</td><td>{orders.find(o=>o.id===p.order_id)?.order_code??p.order_id.slice(0,8)}</td><td>{label(p.method)}</td><td>{p.reference||"—"}</td><td><strong>{peso.format(p.amount)}</strong></td></tr>)}</tbody></table></div></section>}</>}</main>}
