import type { Metadata } from "next";
import "../legal.css";

export const metadata: Metadata = {
  title: "Account Deletion | LabaFlow",
  description: "Request deletion of a LabaFlow account and associated personal data.",
};

export default function AccountDeletionPage(){return <main className="legalPage"><div className="legalShell">
  <nav className="legalNav" aria-label="Legal pages"><a className="legalBrand" href="/"><img src="/labaflow-icon.svg" alt=""/>LabaFlow</a><div className="legalNavLinks"><a href="/privacy">Privacy</a><a href="/account-deletion" aria-current="page">Delete account</a></div></nav>
  <header className="legalHero"><p className="legalEyebrow">ACCOUNT & DATA CONTROLS</p><h1>Delete your LabaFlow account</h1><p>You can request deletion of your login and associated personal data even if you no longer have the LabaFlow app installed.</p><span className="legalUpdated">Last updated September 8, 2026</span></header>
  <article className="legalContent">
    <section><h2>Before you submit a request</h2><p>There are three kinds of LabaFlow users. Follow the instructions that match your account:</p><ul><li><strong>Organization owner or administrator:</strong> request deletion of your login, your organization workspace, or both.</li><li><strong>Staff member:</strong> ask your organization administrator to remove your staff access, or submit a request if you cannot contact them.</li><li><strong>Customer:</strong> ask the relevant organization to delete your customer profile. If the same email is connected to several organizations, name each organization whose records should be deleted.</li></ul></section>
    <section><h2>How to request deletion</h2><ol><li>Visit the official <a href="https://paotechs.com" target="_blank" rel="noreferrer">PAO Technologies contact page</a>.</li><li>Use the subject or first line <strong>“LabaFlow account deletion request.”</strong></li><li>Provide the email address used to sign in, your full name, and the organization name or ID. State whether you want to delete only your login, one customer relationship, or an entire organization workspace.</li><li>We may ask you to verify control of the account or confirm the request with the organization administrator before deletion.</li></ol><div className="legalCallout"><strong>Do not include sensitive credentials.</strong><p>Never send your password, payment-card details, recovery codes, or authentication tokens. We will not ask for them.</p><a className="legalAction" href="https://paotechs.com" target="_blank" rel="noreferrer">Open PAO Technologies contact →</a></div></section>
    <section><h2>What is deleted</h2><p>Once the request is verified and approved, the requested account relationship is disabled and personal information under PAO Technologies’ control is deleted or de-identified. Depending on the request, this can include:</p><ul><li>Your LabaFlow authentication account, profile, role, and branch access.</li><li>Your customer profile, contact details, QR identifier, addresses, and loyalty account for the named organization.</li><li>An organization workspace and its operational data when requested by an authorized owner and when no retention obligation applies.</li></ul></section>
    <section><h2>What may be retained</h2><p>Some information may be retained for a limited period where needed for legal compliance, fraud prevention, security, backups, disputes, or an organization’s legitimate transaction and accounting records. For example, completed order and payment records may need to remain as business records but can be separated from an active login or customer profile where appropriate. Backup copies are removed through the normal backup lifecycle.</p></section>
    <section><h2>Timing and effect</h2><p>We will acknowledge a complete request and explain any verification needed. Deletion is permanent once completed. You may lose access to order history, loyalty points, receipts, and every organization relationship included in the request. Deleting the app from a device does not itself delete an account or its data.</p></section>
    <section><h2>Privacy questions</h2><p>For more information about collection, processing, sharing, and retention, read the <a href="/privacy">LabaFlow Privacy Policy</a>.</p></section>
  </article><footer className="legalFooter">© 2026 PAO Technologies · <a href="/">Return to LabaFlow</a></footer>
</div></main>}
