"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";

type DispatchJob={job_type:"pickup"|"delivery";status:string};
type Order={id:string;order_code:string;branch_id:string;customer_id:string|null;status:string;payment_status:string;subtotal:number;discount:number;total:number;amount_paid:number;created_at:string;delivery_addon_type?:"pickup"|"delivery"|"pickup_delivery"|null;delivery_distance_label?:string|null;delivery_fee?:number;delivery_jobs?:DispatchJob[];customers:{full_name:string;customer_code:string}|null};
type Access={settings?:Record<string,any>;permissions?:Record<string,boolean>};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const fallbackWorkflow=["received","sorting","washing","drying","folding","ready","completed"];
const fallbackPayments=["cash","gcash","maya","card","bank_transfer"];

export default function OrdersPage(){
 const [orders,setOrders]=useState<Order[]>([]),[access,setAccess]=useState<Access>({}),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("all");
 const [payment,setPayment]=useState<Record<string,{amount:string;method:string;reference:string}>>({});
 useEffect(()=>{load()},[]);
 async function load(){setMessage("");const [a,o]=await Promise.all([supabase.rpc("get_current_access_context"),supabase.from("laundry_orders").select("id,order_code,branch_id,customer_id,status,payment_status,subtotal,discount,total,amount_paid,created_at,delivery_addon_type,delivery_distance_label,delivery_fee,delivery_jobs(job_type,status),customers(full_name,customer_code)").order("created_at",{ascending:false}).limit(200)]);if(a.error||o.error){setMessage(a.error?.message||o.error?.message||"Unable to load orders");return}setAccess(a.data??{});setOrders((o.data??[]).map((x:any)=>({...x,subtotal:Number(x.subtotal),discount:Number(x.discount),total:Number(x.total),amount_paid:Number(x.amount_paid),delivery_fee:Number(x.delivery_fee??0)})))}
 const permissions=access.permissions??{};const workflow=(access.settings?.order_workflow?.stages as string[]|undefined)?.filter(Boolean)??fallbackWorkflow;const methods=(access.settings?.payment_methods?.methods as string[]|undefined)?.filter(Boolean)??fallbackPayments;const requireFull=Boolean(access.settings?.completion_rules?.require_full_payment_before_completion);
 const nextStatus=(s:string)=>{const i=workflow.indexOf(s);return i>=0&&i<workflow.length-1?workflow[i+1]:null};
 async function move(o:Order){const next=nextStatus(o.status);if(!next)return;if(next==="completed"&&requireFull&&o.amount_paid<o.total){setMessage(`Full payment is required before completing ${o.order_code}.`);return}const {error}=await supabase.rpc("update_order_status",{p_order_id:o.id,p_status:next,p_notes:null});if(error)setMessage(error.message);else await load()}
 async function pay(o:Order){const p=payment[o.id]??{amount:"",method:methods[0]??"cash",reference:""};const amount=Number(p.amount);if(!amount)return;const {error}=await supabase.rpc("record_order_payment",{p_order_id:o.id,p_amount:amount,p_method:p.method,p_reference:p.reference||null});if(error){setMessage(error.message);return}setPayment(x=>({...x,[o.id]:{amount:"",method:p.method,reference:""}}));await load();setMessage(amount>=Math.max(o.total-o.amount_paid,0)?"Payment completed. Loyalty rewards were calculated automatically.":"Partial payment recorded.")}
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return orders.filter(o=>(statusFilter==="all"||o.status===statusFilter)&&(!q||`${o.order_code} ${o.customers?.full_name??""} ${o.customers?.customer_code??""}`.toLowerCase().includes(q)))},[orders,search,statusFilter]);
 const stats=useMemo(()=>({open:orders.filter(o=>!["completed","cancelled"].includes(o.status)).length,ready:orders.filter(o=>o.status==="ready").length,unpaid:orders.filter(o=>o.amount_paid<o.total).length,revenue:orders.filter(o=>o.payment_status==="paid"||o.amount_paid>=o.total).reduce((n,o)=>n+o.total,0)}),[orders]);
 return <main className="workspace ordersExperience"><header><div><p className="eyebrow">ORDERS</p><h1>Order Management</h1><p className="muted">Track laundry progress, payments, and Pickup/Delivery from one place.</p></div><div className="headerActions"><button className="primary" onClick={()=>location.href="/new-order"}>+ New Order</button></div></header>{message&&<p className="notice">{message}</p>}
 <section className="stats orderStats"><article><span>Open Orders</span><strong>{stats.open}</strong></article><article><span>Ready</span><strong>{stats.ready}</strong></article><article><span>Unpaid</span><strong>{stats.unpaid}</strong></article><article><span>Paid Revenue</span><strong>{peso.format(stats.revenue)}</strong></article></section>
 <section className="panel ordersPanel"><div className="ordersToolbar"><div><h2>Orders</h2><span>{visible.length} shown · {orders.length} total</span></div><div className="ordersFilters"><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option>{workflow.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input placeholder="Search order or customer" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="orderList">{visible.map(o=>{const p=payment[o.id]??{amount:"",method:methods[0]??"cash",reference:""};const next=nextStatus(o.status);const paid=o.payment_status==="paid"||o.amount_paid>=o.total;const balance=Math.max(o.total-o.amount_paid,0);return <article className="orderCard polishedOrder" key={o.id}><div className="orderTop"><div><strong>{o.order_code}</strong><small>{o.customers?.full_name??"Walk-in"}{o.customers?.customer_code?` · ${o.customers.customer_code}`:""}</small></div><div><span className={`status ${o.status}`}>{label(o.status)}</span><b>{peso.format(o.total)}</b></div></div><div className="orderMeta"><span>Paid <b>{peso.format(o.amount_paid)}</b></span><span>Balance <b>{peso.format(balance)}</b></span><span>Payment <b>{paid?"Paid":label(o.payment_status)}</b></span>{o.delivery_addon_type&&<span>Pickup/Delivery <b>{label(o.delivery_addon_type)}{o.delivery_distance_label?` · ${o.delivery_distance_label}`:""}</b></span>}</div><div className="orderActions">{o.delivery_jobs?.length? <button className="secondary" onClick={()=>location.href="/pickup-delivery"}>Dispatch Board</button>:null}{permissions.process_orders&&next&&<button className="secondary" disabled={next==="completed"&&requireFull&&!paid} onClick={()=>move(o)}>{next==="completed"?"Complete Order":`Move to ${label(next)}`}</button>}{permissions.record_payments&&(paid?<span className="status active">✓ Paid</span>:<><select value={p.method} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,method:e.target.value}}))}>{methods.map(m=><option key={m} value={m}>{label(m)}</option>)}</select><input type="number" min="0.01" max={balance} step="0.01" placeholder={`Balance ${peso.format(balance)}`} value={p.amount} onChange={e=>setPayment(x=>({...x,[o.id]:{...p,amount:e.target.value}}))}/><button className="primary" onClick={()=>pay(o)}>Record Payment</button></>)}</div></article>})}{!visible.length&&<p className="empty">No orders match your filters.</p>}</div></section></main>
}
