export type OfflineJobKind="create_order"|"update_order_status"|"record_cash_payment"|"create_customer";
export type OfflineJob={id:string;kind:OfflineJobKind;payload:Record<string,any>;createdAt:string;status:"pending"|"syncing"|"failed";error?:string;scope?:string;dependsOn?:string};
export type SyncHistory={id:string;kind:OfflineJobKind;syncedAt:string;scope?:string};
const DB="labaflow-offline-v1",STORE="jobs",CACHE="reference",HISTORY="history",RESOLVED="resolved";
function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,3);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"});if(!d.objectStoreNames.contains(CACHE))d.createObjectStore(CACHE);if(!d.objectStoreNames.contains(HISTORY))d.createObjectStore(HISTORY,{keyPath:"id"});if(!d.objectStoreNames.contains(RESOLVED))d.createObjectStore(RESOLVED)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export function offlineScope(userId?:string|null,organizationId?:string|null){return userId&&organizationId?`${userId}:${organizationId}`:"unscoped"}
export async function queueJob(kind:OfflineJobKind,payload:Record<string,any>,opts?:{scope?:string;dependsOn?:string;id?:string}){const d=await db(),job:OfflineJob={id:opts?.id??crypto.randomUUID(),kind,payload,createdAt:new Date().toISOString(),status:"pending",scope:opts?.scope,dependsOn:opts?.dependsOn};await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(job);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"));return job}
export async function jobs(scope?:string){const d=await db();return await new Promise<OfflineJob[]>((resolve,reject)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result.filter((x:OfflineJob)=>!scope||x.scope===scope||!x.scope).sort((a:OfflineJob,b:OfflineJob)=>a.createdAt.localeCompare(b.createdAt)));r.onerror=()=>reject(r.error)})}
export async function removeJob(id:string){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"))}
export async function updateJob(job:OfflineJob){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(job);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"))}
export async function addHistory(item:SyncHistory){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(HISTORY,"readwrite");t.objectStore(HISTORY).put(item);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
export async function syncHistory(scope?:string){const d=await db();return await new Promise<SyncHistory[]>((resolve,reject)=>{const r=d.transaction(HISTORY).objectStore(HISTORY).getAll();r.onsuccess=()=>resolve(r.result.filter((x:SyncHistory)=>!scope||x.scope===scope||!x.scope).sort((a:SyncHistory,b:SyncHistory)=>b.syncedAt.localeCompare(a.syncedAt)).slice(0,50));r.onerror=()=>reject(r.error)})}
export async function setResolved(localId:string,serverId:string){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(RESOLVED,"readwrite");t.objectStore(RESOLVED).put(serverId,localId);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
export async function getResolved(localId:string){const d=await db();return await new Promise<string|null>((resolve,reject)=>{const r=d.transaction(RESOLVED).objectStore(RESOLVED).get(localId);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
export async function cacheReference(key:string,value:unknown,scope?:string){const d=await db(),k=scope?`${scope}:${key}`:key;await new Promise<void>((resolve,reject)=>{const t=d.transaction(CACHE,"readwrite");t.objectStore(CACHE).put(value,k);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
export async function getReference<T>(key:string,scope?:string){const d=await db(),k=scope?`${scope}:${key}`:key;return await new Promise<T|null>((resolve,reject)=>{const r=d.transaction(CACHE).objectStore(CACHE).get(k);r.onsuccess=()=>resolve((r.result??null) as T|null);r.onerror=()=>reject(r.error)})}
