export type OfflineJob={id:string;kind:"create_order";payload:Record<string,any>;createdAt:string;status:"pending"|"syncing"|"failed";error?:string};
const DB="labaflow-offline-v1",STORE="jobs",CACHE="reference";
function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"});if(!d.objectStoreNames.contains(CACHE))d.createObjectStore(CACHE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function queueJob(kind:OfflineJob["kind"],payload:Record<string,any>){const d=await db(),job:OfflineJob={id:crypto.randomUUID(),kind,payload,createdAt:new Date().toISOString(),status:"pending"};await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(job);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"));return job}
export async function jobs(){const d=await db();return await new Promise<OfflineJob[]>((resolve,reject)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function removeJob(id:string){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"))}
export async function updateJob(job:OfflineJob){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(job);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)});window.dispatchEvent(new Event("labaflow:queue-changed"))}
export async function cacheReference(key:string,value:unknown){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(CACHE,"readwrite");t.objectStore(CACHE).put(value,key);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
export async function getReference<T>(key:string){const d=await db();return await new Promise<T|null>((resolve,reject)=>{const r=d.transaction(CACHE).objectStore(CACHE).get(key);r.onsuccess=()=>resolve((r.result??null) as T|null);r.onerror=()=>reject(r.error)})}
