"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

export default function CustomerJoinPage(){
 const [token,setToken]=useState(""),[org,setOrg]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({full_name:"",mobile:"",email:""});
 useEffect(()=>{const t=new URLSearchParams(location.search).get("org")||"";setToken(t);if(t)loadOrg(t);else setMessage("This enrollment link is incomplete. Please scan the laundry shop QR again.")},[]);
 async function loadOrg(t:string){const {data,error}=await supabase.rpc("get_customer_enrollment_org",{p_token:t});if(error||!data){setMessage(error?.message||"This enrollment QR is no longer available.");return}setOrg(data.organization_name)}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {data,error}=await supabase.rpc("enroll_customer_portal",{p_token:token,p_full_name:form.full_name,p_mobile:form.mobile||null,p_email:form.email||null});setBusy(false);if(error){setMessage(error.message);return}localStorage.setItem("labaflow_customer_access",data.access_token);location.href="/customer"}
 return <main className="customerPortalPage"><section className="customerPortalHero"><div className="customerPortalLogo">LF</div><p className="eyebrow">MY LABAFLOW</p><h1>{org||"Customer Registration"}</h1><p>Register once to follow your laundry orders and loyalty rewards from your phone.</p></section><section className="customerPortalCard"><h2>Welcome</h2><p className="muted">Enter your information. If you are already a customer of this laundry shop, LabaFlow will connect to your existing record.</p>{message&&<p className="notice">{message}</p>}<form className="stack" onSubmit={submit}><label>Full name<input required autoComplete="name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Mobile number<input inputMode="tel" autoComplete="tel" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} placeholder="09xx xxx xxxx"/></label><label>Email address<input type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Optional if mobile is provided"/></label><button className="primary customerPortalPrimary" disabled={busy||!token}>{busy?"Connecting…":"Continue to My LabaFlow"}</button></form><small className="customerPrivacy">Your profile and rewards remain separate for each LabaFlow laundry organization.</small></section></main>}
