"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

export default function CustomerJoinPage(){
 const [token,setToken]=useState(""),[org,setOrg]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({full_name:"",mobile:"",email:""});
 useEffect(()=>{const t=new URLSearchParams(location.search).get("org")||"";setToken(t);if(!t){setMessage("This enrollment link is incomplete. Please scan the laundry shop QR again.");return}loadOrg(t);supabase.auth.getSession().then(({data})=>{const session=data.session;if(!session){location.replace(`/customer/login?returnTo=${encodeURIComponent(`/customer/join?org=${t}`)}`);return}setForm(x=>({...x,full_name:session.user.user_metadata?.full_name||x.full_name,email:session.user.email||x.email}))})},[]);
 async function loadOrg(t:string){const {data,error}=await supabase.rpc("get_customer_enrollment_org",{p_token:t});if(error||!data){setMessage(error?.message||"This enrollment QR is no longer available.");return}setOrg(data.organization_name)}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {data,error}=await supabase.rpc("enroll_my_customer_portal",{p_token:token,p_full_name:form.full_name,p_mobile:form.mobile||null});setBusy(false);if(error){setMessage(error.message);return}localStorage.setItem("labaflow_customer_access",data.access_token);location.href="/customer"}
 return <main className="customerPortalPage"><section className="customerPortalHero"><div className="customerPortalLogo">LF</div><p className="eyebrow">MY LABAFLOW</p><h1>{org||"Customer Registration"}</h1><p>Connect this laundry organization to your customer account.</p></section><section className="customerPortalCard"><h2>Welcome</h2><p className="muted">If you are already a customer here, LabaFlow will connect your existing record using your verified account email.</p>{message&&<p className="notice">{message}</p>}<form className="stack" onSubmit={submit}><label>Full name<input required autoComplete="name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Mobile number<input inputMode="tel" autoComplete="tel" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} placeholder="09xx xxx xxxx"/></label><label>Account email<input type="email" value={form.email} readOnly disabled/></label><button className="primary customerPortalPrimary" disabled={busy||!token}>{busy?"Connecting…":"Add Organization"}</button></form><small className="customerPrivacy">Orders, QR codes and rewards remain separate for each organization.</small></section></main>}
