"use client";
import {useEffect,useState} from "react";
import QRCode from "qrcode";
import {supabase} from "../../lib/supabase";
type Dashboard={organization_name:string;customer:{customer_code:string;full_name:string;mobile:string|null;email:string|null;loyalty_points:number;lifetime_points:number;lifetime_visits:number;lifetime_spend:number};orders:Array<{id:string;order_code:string;status:string;payment_status:string;total:number;amount_paid:number;created_at:string;due_at:string|null;branch_name:string}>;loyalty_history:Array<{transaction_type:string;points:number;description:string|null;created_at:string}>};
type Workspace={organization_id:string;organization_name:string;customer_id:string;customer_name:string;customer_code:string;access_token:string};
type Branding={organization_name:string;organization_logo_url:string|null};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function CustomerPortal(){
 const [data,setData]=useState<Dashboard|null>(null),[branding,setBranding]=useState<Branding|null>(null),[workspaces,setWorkspaces]=useState<Workspace[]>([]),[selectedToken,setSelectedToken]=useState(""),[message,setMessage]=useState("Loading My LabaFlow…"),[tab,setTab]=useState("home"),[qr,setQr]=useState("");
 useEffect(()=>{void initialize()},[]);
 async function initialize(){const {data:session}=await supabase.auth.getSession();if(session.session){const linked=await supabase.rpc("link_my_customer_portals_by_email");if(!linked.error&&Array.isArray(linked.data)){setWorkspaces(linked.data);const saved=localStorage.getItem("labaflow_customer_access"),token=linked.data.some((x:Workspace)=>x.access_token===saved)?saved:linked.data[0]?.access_token;if(token){localStorage.setItem("labaflow_customer_access",token);setSelectedToken(token);await load(token);return}}}const legacy=localStorage.getItem("labaflow_customer_access");if(legacy){setSelectedToken(legacy);await load(legacy);return}location.href="/customer/login"}
 async function load(token:string){setMessage("Loading My LabaFlow…");setData(null);setBranding(null);setQr("");const [{data:d,error},{data:q,error:qrError},{data:b,error:brandingError}]=await Promise.all([supabase.rpc("get_customer_portal_dashboard",{p_access_token:token}),supabase.rpc("get_customer_portal_qr",{p_access_token:token}),supabase.rpc("get_customer_branding",{p_access_token:token})]);if(error){setMessage(error.message);return}setData(d);if(!brandingError&&b)setBranding(b);if(!qrError&&q?.qr_token)setQr(await QRCode.toDataURL(`labaflow:${q.qr_token}`,{width:360,margin:2}));setMessage("")}
 async function switchWorkspace(token:string){if(!token||token===selectedToken)return;setSelectedToken(token);localStorage.setItem("labaflow_customer_access",token);setTab("home");await load(token)}
 async function leave(){localStorage.removeItem("labaflow_customer_access");await supabase.auth.signOut();location.href="/customer/login"}
 if(!data)return <main className="customerPortalPage"><section className="customerPortalCard"><h2>My LabaFlow</h2><p className="muted">{message}</p></section></main>;
 const active=data.orders.filter(o=>!["completed","cancelled"].includes(o.status)),organizationName=branding?.organization_name||data.organization_name;
 return <main className="customerPortalPage customerDashboard"><header className="customerAppHeader"><div className="customerAppIdentity"><div className="customerAppOrgLogo">{branding?.organization_logo_url?<img src={branding.organization_logo_url} alt={`${organizationName} logo`}/>:<span>LF</span>}</div><div><small>MY LABAFLOW</small>{workspaces.length>1?<select aria-label="Laundry organization" value={selectedToken} onChange={e=>void switchWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.organization_id} value={w.access_token}>{w.organization_name}</option>)}</select>:<strong>{organizationName}</strong>}</div></div><button onClick={()=>void leave()}>Sign out</button></header><section className="customerWelcome"><p>Welcome back</p><h1>{data.customer.full_name}</h1><span>{data.customer.customer_code}</span></section>
 {tab==="home"&&<><section className="customerPortalStats"><article><small>ACTIVE ORDERS</small><strong>{active.length}</strong><span>In progress</span></article><article><small>REWARDS</small><strong>{data.customer.loyalty_points}</strong><span>Available points</span></article></section>{qr&&<section className="customerPortalCard customerQrCard"><div><small>MY CUSTOMER QR</small><h2>Scan me at the counter</h2><p className="muted">Show this QR when placing an order so the staff can select your account instantly.</p></div><img src={qr} alt={`${data.customer.full_name} customer QR code`}/><strong>{data.customer.customer_code}</strong></section>}<section className="customerPortalCard"><div className="customerSectionHead"><h2>Your Laundry</h2><button onClick={()=>setTab("orders")}>View all</button></div>{active.length?active.slice(0,3).map(o=><OrderCard key={o.id} order={o}/>):<div className="customerEmptyState">✓<strong>You're all caught up.</strong><span>No laundry orders are currently in progress.</span></div>}</section><section className="customerRewardCard"><small>LOYALTY REWARDS</small><strong>{data.customer.loyalty_points} points</strong><span>{data.customer.lifetime_points} lifetime points · {data.customer.lifetime_visits} visits</span><button onClick={()=>setTab("rewards")}>View rewards activity</button></section></>}
 {tab==="orders"&&<section className="customerPortalCard"><h2>Order History</h2>{data.orders.length?data.orders.map(o=><OrderCard key={o.id} order={o}/>):<p className="muted">No orders yet.</p>}</section>}{tab==="rewards"&&<section className="customerPortalCard"><h2>Rewards</h2><div className="rewardBalance"><strong>{data.customer.loyalty_points}</strong><span>available points</span></div>{data.loyalty_history.length?data.loyalty_history.map((x,i)=><div className="rewardHistory" key={i}><div><strong>{x.description||label(x.transaction_type)}</strong><small>{new Date(x.created_at).toLocaleDateString()}</small></div><b className={x.points>=0?"positive":""}>{x.points>0?"+":""}{x.points}</b></div>):<p className="muted">Your rewards activity will appear here.</p>}</section>}{tab==="profile"&&<section className="customerPortalCard"><h2>Your Profile</h2><div className="customerProfileList"><div><small>Name</small><strong>{data.customer.full_name}</strong></div><div><small>Mobile</small><strong>{data.customer.mobile||"—"}</strong></div><div><small>Email</small><strong>{data.customer.email||"—"}</strong></div><div><small>Lifetime spend</small><strong>{peso.format(data.customer.lifetime_spend)}</strong></div></div></section>}
 <nav className="customerBottomNav"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}>⌂<span>Home</span></button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>▤<span>Orders</span></button><button className={tab==="rewards"?"active":""} onClick={()=>setTab("rewards")}>★<span>Rewards</span></button><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}>●<span>Profile</span></button></nav></main>}
function OrderCard({order:o}:{order:Dashboard["orders"][number]}){const balance=Math.max(Number(o.total)-Number(o.amount_paid),0);return <article className="customerOrderCard"><div><strong>{o.order_code}</strong><span>{o.branch_name} · {new Date(o.created_at).toLocaleDateString()}</span></div><span className={`customerOrderStatus ${o.status}`}>{label(o.status)}</span><div className="customerOrderProgress"><i></i></div><footer><b>{peso.format(Number(o.total))}</b><span>{balance?`${peso.format(balance)} balance`:"Paid"}</span></footer></article>}
