"use client";
import {useEffect,useState} from "react";
import {chooseBluetoothPrinter,loadPrinterSettings,savePrinterSettings,supportsWebBluetooth,type PrinterSettings} from "../../../lib/printerSettings";
import "./printer.css";

function testPrint(format:"standard"|"58mm"){
 const thermal=format==="58mm",win=window.open("","_blank",thermal?"width=360,height=700":"width=760,height=700");if(!win)throw new Error("Please allow pop-ups to run the test print.");
 const page=thermal?"@page{size:58mm auto;margin:2mm}":"@page{size:auto;margin:10mm}";
 win.document.write(`<!doctype html><html><head><title>LabaFlow Printer Test</title><style>${page}body{box-sizing:border-box;width:${thermal?"54mm":"100%"};max-width:${thermal?"54mm":"180mm"};margin:0 auto;padding:${thermal?"1mm":"10mm"};font-family:${thermal?'"Courier New",monospace':'Arial,sans-serif'};font-size:${thermal?"8pt":"12pt"};color:#000}h1,p{margin:0;text-align:center}.line{border-top:1px dashed #000;margin:4mm 0}.row{display:flex;justify-content:space-between;margin:1.5mm 0}.ok{text-align:center;font-weight:700;margin-top:5mm}@media print{body{padding:${thermal?"0":"4mm"}}}</style></head><body><h1>LabaFlow</h1><p>Printer Test · ${thermal?"58 mm":"Standard"}</p><div class="line"></div><div class="row"><span>Date</span><strong>${new Date().toLocaleString()}</strong></div><div class="row"><span>Width</span><strong>${thermal?"58 mm thermal":"Standard / PDF"}</strong></div><div class="line"></div><p class="ok">✓ Printer setup is ready</p><script>window.onload=()=>window.print()</script></body></html>`);win.document.close();
}

export default function PrinterSettingsPage(){
 const [settings,setSettings]=useState<PrinterSettings>(()=>loadPrinterSettings()),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[bluetooth,setBluetooth]=useState(false),[platform,setPlatform]=useState("this device");
 useEffect(()=>{setBluetooth(supportsWebBluetooth());const ua=navigator.userAgent;setPlatform(/Android/i.test(ua)?"Android":/iPhone|iPad|iPod/i.test(ua)?"iPhone / iPad":"Desktop")},[]);
 function update(next:Partial<PrinterSettings>){const value={...settings,...next};setSettings(value);savePrinterSettings(value);setMessage("Printer preference saved on this device.")}
 async function connect(){setBusy(true);setMessage("Opening Bluetooth device selection…");try{const device=await chooseBluetoothPrinter();update({connectionMode:"web_bluetooth",deviceId:device.id,deviceName:device.name});setMessage(`${device.name} detected${device.connected?" and connected":""}. Use Test Print to confirm browser printing.`)}catch(e:any){setMessage(e?.name==="NotFoundError"?"No printer was selected.":e?.message||"Unable to detect a Bluetooth printer.")}finally{setBusy(false)}}
 function runTest(){try{testPrint(settings.defaultFormat);setMessage("Test print opened. On Android, choose PrinterApp or the installed printer service in the print screen.")}catch(e:any){setMessage(e?.message||"Unable to open the test print.")}}
 return <main className="workspace printerSettingsPage"><header><div><p className="eyebrow">DEVICE SETTINGS</p><h1>Printer Settings</h1><p className="muted">Configure receipt printing for this phone, tablet, or computer.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/organization"}>Organization Admin</button></div></header>{message&&<p className="notice">{message}</p>}<section className="panel printerSetupPanel"><div className="panelHead"><div><h2>Receipt Printer</h2><span>These preferences stay on this device, so each counter can use its own printer.</span></div><span className="status active">{platform}</span></div><div className="printerChoiceGrid"><label className={settings.defaultFormat==="58mm"?"selected":""}><input type="radio" name="format" checked={settings.defaultFormat==="58mm"} onChange={()=>update({defaultFormat:"58mm"})}/><strong>58 mm Thermal</strong><span>Compact ESC/POS-style receipt</span></label><label className={settings.defaultFormat==="standard"?"selected":""}><input type="radio" name="format" checked={settings.defaultFormat==="standard"} onChange={()=>update({defaultFormat:"standard"})}/><strong>Standard / PDF</strong><span>Full-page printing and PDF</span></label></div></section><section className="panel"><div className="panelHead"><div><h2>Connection</h2><span>Use direct discovery when supported, or Android PrinterApp/System Print for generic printers.</span></div></div><div className="printerConnectionCard"><div><small>CURRENT METHOD</small><strong>{settings.connectionMode==="web_bluetooth"?(settings.deviceName||"Bluetooth printer"):"PrinterApp / System Print"}</strong><span>{settings.connectionMode==="web_bluetooth"?"Browser permission saved for this printer":"Recommended for your current unbranded printer"}</span></div><div className="printerConnectionActions"><button className="primary" disabled={!bluetooth||busy} onClick={connect}>{busy?"Detecting…":"Connect Bluetooth Printer"}</button><button className="secondary" onClick={()=>update({connectionMode:"system",deviceId:null,deviceName:null})}>Use PrinterApp / System Print</button></div></div>{!bluetooth&&<p className="printerHelp">Direct Bluetooth discovery is unavailable in this browser. Pair the printer inside PrinterApp, then use LabaFlow’s print screen and select PrinterApp or its print service.</p>}</section><section className="panel printerTestPanel"><div><h2>Test Printer</h2><p className="muted">Prints a small sample using your saved {settings.defaultFormat==="58mm"?"58 mm thermal":"standard"} layout.</p></div><button className="primary" onClick={runTest}>Print Test Page</button></section></main>
}
