"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";

type Row={id:string;name:string;sku:string|null;barcode:string|null;cost_price:number;selling_price:number;loyalty_points:number;active:boolean;created_branch_id:string|null;branch_id:string;branch_name:string;branch_code:string;quantity:number;low_stock_level:number};
type Branch={id:string;name:string;code:string};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const fmt=(n:number)=>Number.isInteger(n)?n.toLocaleString():n.toLocaleString("en-PH",{maximumFractionDigits:3});
export default function ProductsPage(){
 const [rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[editing,setEditing]=useState<Row|null>(null),[showForm,setShowForm]=useState(false),[stockRow,setStockRow]=useState<Row|null>(null),[stockChange,setStockChange]=useState(""),[stockNotes,setStockNotes]=useState(""),[search,setSearch]=useState(""),[branchFilter,setBranchFilter]=useState("all"),[archiveOpen,setArchiveOpen]=useState(false);
 const [name,setName]=useState(""),[barcode,setBarcode]=useState(""),[cost,setCost]=useState("0"),[price,setPrice]=useState("0"),[points,setPoints]=useState("0"),[active,setActive]=useState(true),[createBranchId,setCreateBranchId]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const {data,error}=await supabase.rpc("get_products_inventory");if(error)return setMessage(error.message);const next=(data??[]).map((x:any)=>({...x,cost_price:Number(x.cost_price),selling_price:Number(x.selling_price),loyalty_points:Number(x.loyalty_points),quantity:Number(x.quantity),low_stock_level:Number(x.low_stock_level)}));setRows(next);if(!createBranchId&&next[0]?.branch_id)setCreateBranchId(next[0].branch_id);setMessage("")}
 const branches=useMemo<Branch[]>(()=>Array.from(new Map(rows.map(r=>[r.branch_id,{id:r.branch_id,name:r.branch_name,code:r.branch_code}])).values()).sort((a,b)=>a.name.localeCompare(b.name)),[rows]);
 const products=useMemo(()=>Array.from(new Map(rows.map(r=>[r.id,r])).values()),[rows]);
 const activeProducts=products.filter(p=>p.active),archivedProducts=products.filter(p=>!p.active);
 const activeRows=rows.filter(r=>r.active),totalStock=activeRows.reduce((n,r)=>n+r.quantity,0),lowStockProducts=new Set(activeRows.filter(r=>r.quantity>0&&r.quantity<=r.low_stock_level).map(r=>r.id)).size,outStockProducts=new Set(activeProducts.filter(p=>activeRows.filter(r=>r.id===p.id).every(r=>r.quantity<=0)).map(p=>p.id)).size;
 const visibleBranches=branches.filter(b=>branchFilter==="all"||b.id===branchFilter);
 function matchesSearch(r:Row){const q=search.trim().toLowerCase(),text=`${r.name} ${r.sku??""} ${r.barcode??""}`.toLowerCase();return !q||text.includes(q)}
 function openNew(){setEditing(null);setName("");setBarcode("");setCost("0");setPrice("0");setPoints("0");setActive(true);setCreateBranchId(branchFilter!=="all"?branchFilter:(branches[0]?.id??""));setShowForm(true)}
 function openEdit(r:Row){setEditing(r);setName(r.name);setBarcode(r.barcode??"");setCost(String(r.cost_price));setPrice(String(r.selling_price));setPoints(String(r.loyalty_points));setActive(r.active);setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();if(!editing&&!createBranchId)return setMessage("Select a branch for SKU generation.");const branchForSku=(editing?.created_branch_id??createBranchId)||null;const {error}=await supabase.rpc("save_product_v2",{p_product_id:editing?.id??null,p_branch_id:branchForSku,p_name:name,p_barcode:barcode||null,p_cost_price:Number(cost)||0,p_selling_price:Number(price)||0,p_loyalty_points:Number(points)||0,p_active:active});if(error)return setMessage(error.message);setShowForm(false);setMessage(editing?(active?"Product updated.":"Product moved to Archive."):"Product created with an automatically generated SKU.");await load()}
 async function restore(r:Row){const {error}=await supabase.rpc("save_product_v2",{p_product_id:r.id,p_branch_id:r.created_branch_id,p_name:r.name,p_barcode:r.barcode,p_cost_price:r.cost_price,p_selling_price:r.selling_price,p_loyalty_points:r.loyalty_points,p_active:true});if(error)return setMessage(error.message);setMessage(`${r.name} restored to active products.`);await load()}
 async function adjust(e:FormEvent){e.preventDefault();if(!stockRow)return;const q=Number(stockChange);if(!q)return setMessage("Enter a non-zero stock adjustment.");const {error}=await supabase.rpc("adjust_product_stock",{p_product_id:stockRow.id,p_branch_id:stockRow.branch_id,p_quantity_change:q,p_notes:stockNotes||null});if(error)return setMessage(error.message);setStockRow(null);setStockChange("");setStockNotes("");setMessage("Stock updated.");await load()}
 const tableRows=(branchRows:Row[],archived=false)=><div className="catalogTableWrap"><table className="catalogTable branchProductTable"><thead><tr><th>Product</th><th>SKU / Barcode</th><th>Price</th><th>Stock</th><th>Low Stock Level</th><th>Status</th><th>Actions</th></tr></thead><tbody>{branchRows.map(r=><tr key={`${r.branch_id}-${r.id}`}><td><div className="productIdentity"><span className="productGlyph">▣</span><div><strong>{r.name}</strong>{r.loyalty_points>0&&<small>{r.loyalty_points} loyalty pt{r.loyalty_points===1?"":"s"}</small>}</div></div></td><td><strong>{r.sku||"—"}</strong>{r.barcode&&<small>{r.barcode}</small>}</td><td><strong>{peso.format(r.selling_price)}</strong><small>Cost: {peso.format(r.cost_price)}</small></td><td><strong>{fmt(r.quantity)}</strong><small>On hand</small></td><td><strong>{fmt(r.low_stock_level)}</strong></td><td><span className={`catalogBadge ${archived?"inactive":"active"}`}>{archived?"Archived":"Active"}</span>{!archived&&r.quantity<=0&&<small className="stockNote out">Out of stock</small>}{!archived&&r.quantity>0&&r.quantity<=r.low_stock_level&&<small className="stockNote low">Low stock</small>}</td><td><div className="rowActions"><button className="iconBtn" onClick={()=>openEdit(r)} title="Edit product">✎</button>{archived?<button className="secondary compact" onClick={()=>void restore(r)}>Restore</button>:<button className="secondary compact" onClick={()=>setStockRow(r)}>Adjust Stock</button>}</div></td></tr>)}</tbody></table>{!branchRows.length&&<p className="empty">No products to display.</p>}</div>;
 return <main className="workspace catalogPage productBranchPage"><header className="catalogHeader"><div><p className="eyebrow">CATALOG</p><h1>Products & Inventory</h1><p className="muted">Manage retail laundry products, branch stock and selling prices.</p></div><button className="primary catalogPrimary" onClick={openNew}>+ Add Product</button></header>{message&&<p className="notice">{message}</p>}
 <section className="catalogStats"><article><span className="statIcon green">▣</span><div><small>Active Products</small><strong>{activeProducts.length}</strong><span>Available for sale</span></div></article><article><span className="statIcon blue">◫</span><div><small>Total Stock</small><strong>{fmt(totalStock)}</strong><span>Across all branches</span></div></article><article><span className="statIcon amber">!</span><div><small>Low Stock Items</small><strong>{lowStockProducts}</strong><span>Reorder soon</span></div></article><article><span className="statIcon red">◇</span><div><small>Out of Stock</small><strong>{outStockProducts}</strong><span>Needs attention</span></div></article></section>
 <section className="panel catalogToolbarPanel"><div className="catalogToolbar"><div className="catalogSearch"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search active products by name, SKU or barcode..."/></div><select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)}><option value="all">All Branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div></section>
 <div className="branchInventoryStack">{visibleBranches.map(branch=>{const branchRows=rows.filter(r=>r.active&&r.branch_id===branch.id&&matchesSearch(r));return <section className="panel branchInventoryPanel" key={branch.id}><div className="branchInventoryHeader"><div className="branchTitleIcon">▦</div><div><h2>{branch.name}</h2><p>{branch.code} · {branchRows.length} active product{branchRows.length===1?"":"s"}</p></div></div>{tableRows(branchRows)}</section>})}</div>
 <section className="panel productArchivePanel"><button type="button" className="archiveHeader" onClick={()=>setArchiveOpen(v=>!v)}><div className="archiveTitle"><span className="archiveIcon">▣</span><div><p className="eyebrow">ARCHIVE</p><h2>Inactive Products</h2><span>{archivedProducts.length} archived product{archivedProducts.length===1?"":"s"} · Hidden from sales</span></div></div><span className="archiveToggle">{archiveOpen?"Hide":"View Archive"} {archiveOpen?"⌃":"⌄"}</span></button>{archiveOpen&&<div className="archiveBody">{visibleBranches.map(branch=>{const archivedRows=rows.filter(r=>!r.active&&r.branch_id===branch.id&&matchesSearch(r));if(!archivedRows.length)return null;return <div className="archiveBranch" key={branch.id}><div className="archiveBranchHead"><strong>{branch.name}</strong><span>{branch.code}</span></div>{tableRows(archivedRows,true)}</div>})}{!archivedProducts.length&&<p className="empty">No inactive products. Products you deactivate will appear here.</p>}</div>}</section>
 {showForm&&<div className="modalBackdrop"><form className="panel modalCard catalogModal" onSubmit={save}><div className="modalTitle"><div><p className="eyebrow">PRODUCT</p><h2>{editing?"Edit Product":"Add Product"}</h2></div><button type="button" className="secondary iconBtn" onClick={()=>setShowForm(false)}>×</button></div><div className="gridForm">{editing?<label>SKU<input value={editing.sku??""} readOnly disabled/><small className="fieldHint">SKU is generated automatically and cannot be changed.</small></label>:<label>Branch for SKU<select value={createBranchId} onChange={e=>setCreateBranchId(e.target.value)} required><option value="">Select branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name} ({b.code})</option>)}</select><small className="fieldHint">SKU example: {(branches.find(b=>b.id===createBranchId)?.code||"MAIN")}-00001.</small></label>}<label>Product Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Barcode<input value={barcode} onChange={e=>setBarcode(e.target.value)}/></label><label>Cost Price<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Selling Price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Loyalty Points<input type="number" min="0" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label></div><label className="checkLabel"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active product</label><small className="fieldHint">Turn this off to move the product to Archive. Archived products are excluded from sales.</small><div className="headerActions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">Save Product</button></div></form></div>}
 {stockRow&&<div className="modalBackdrop"><form className="panel modalCard catalogModal" onSubmit={adjust}><div className="modalTitle"><div><p className="eyebrow">INVENTORY</p><h2>Adjust Stock</h2><p className="muted">{stockRow.name} · {stockRow.branch_name} · Current: {fmt(stockRow.quantity)}</p></div><button type="button" className="secondary iconBtn" onClick={()=>setStockRow(null)}>×</button></div><label>Quantity Change<input type="number" step="0.001" value={stockChange} onChange={e=>setStockChange(e.target.value)} placeholder="e.g. 20 or -2" required/></label><label>Reason / Notes<textarea value={stockNotes} onChange={e=>setStockNotes(e.target.value)} placeholder="Restock, damaged item, correction…"/></label><div className="headerActions"><button type="button" className="secondary" onClick={()=>setStockRow(null)}>Cancel</button><button className="primary">Update Stock</button></div></form></div>}
 </main>
}
