"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

type Row={id:string;name:string;sku:string|null;barcode:string|null;cost_price:number;selling_price:number;loyalty_points:number;active:boolean;branch_id:string;branch_name:string;quantity:number;low_stock_level:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
export default function ProductsPage(){
 const [rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[editing,setEditing]=useState<Row|null>(null),[showForm,setShowForm]=useState(false),[stockRow,setStockRow]=useState<Row|null>(null),[stockChange,setStockChange]=useState(""),[stockNotes,setStockNotes]=useState("");
 const [name,setName]=useState(""),[sku,setSku]=useState(""),[barcode,setBarcode]=useState(""),[cost,setCost]=useState("0"),[price,setPrice]=useState("0"),[points,setPoints]=useState("0"),[active,setActive]=useState(true);
 useEffect(()=>{void load()},[]);
 async function load(){const {data,error}=await supabase.rpc("get_products_inventory");if(error)return setMessage(error.message);setRows((data??[]).map((x:any)=>({...x,cost_price:Number(x.cost_price),selling_price:Number(x.selling_price),loyalty_points:Number(x.loyalty_points),quantity:Number(x.quantity),low_stock_level:Number(x.low_stock_level)})));setMessage("")}
 function openNew(){setEditing(null);setName("");setSku("");setBarcode("");setCost("0");setPrice("0");setPoints("0");setActive(true);setShowForm(true)}
 function openEdit(r:Row){setEditing(r);setName(r.name);setSku(r.sku??"");setBarcode(r.barcode??"");setCost(String(r.cost_price));setPrice(String(r.selling_price));setPoints(String(r.loyalty_points));setActive(r.active);setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("save_product",{p_product_id:editing?.id??null,p_name:name,p_sku:sku||null,p_barcode:barcode||null,p_cost_price:Number(cost)||0,p_selling_price:Number(price)||0,p_loyalty_points:Number(points)||0,p_active:active});if(error)return setMessage(error.message);setShowForm(false);await load()}
 async function adjust(e:FormEvent){e.preventDefault();if(!stockRow)return;const q=Number(stockChange);if(!q)return setMessage("Enter a non-zero stock adjustment.");const {error}=await supabase.rpc("adjust_product_stock",{p_product_id:stockRow.id,p_branch_id:stockRow.branch_id,p_quantity_change:q,p_notes:stockNotes||null});if(error)return setMessage(error.message);setStockRow(null);setStockChange("");setStockNotes("");await load()}
 const grouped=Array.from(new Map(rows.map(r=>[r.id,r])).values());
 return <main className="workspace"><header className="pageHeader"><div><p className="eyebrow">CATALOG</p><h1>Products & Inventory</h1><p className="muted">Manage retail laundry products, branch stock and selling prices.</p></div><button className="primary" onClick={openNew}>+ Add Product</button></header>{message&&<p className="notice">{message}</p>}
 <section className="panel"><div style={{overflowX:"auto"}}><table className="dataTable"><thead><tr><th>Product</th><th>SKU / Barcode</th><th>Price</th><th>Branch</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.id}-${r.branch_id}`}><td><strong>{r.name}</strong>{r.loyalty_points>0&&<small className="muted" style={{display:"block"}}>{r.loyalty_points} loyalty pts</small>}</td><td>{r.sku||"—"}<small className="muted" style={{display:"block"}}>{r.barcode||""}</small></td><td>{peso.format(r.selling_price)}</td><td>{r.branch_name}</td><td><strong>{r.quantity}</strong>{r.quantity<=r.low_stock_level&&<small style={{display:"block"}}>Low stock</small>}</td><td>{r.active?"Active":"Inactive"}</td><td><button className="secondary" onClick={()=>openEdit(r)}>Edit</button> <button className="secondary" onClick={()=>setStockRow(r)}>Adjust Stock</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No products yet. Add detergent, fabric conditioner, laundry bags or other retail items.</p>}</div></section>
 {showForm&&<div className="modalBackdrop"><form className="panel modalCard" onSubmit={save}><div className="pageHeader"><h2>{editing?"Edit Product":"Add Product"}</h2><button type="button" className="secondary" onClick={()=>setShowForm(false)}>×</button></div><div className="gridForm"><label>Product Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label>Barcode<input value={barcode} onChange={e=>setBarcode(e.target.value)}/></label><label>Cost Price<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Selling Price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Loyalty Points<input type="number" min="0" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label></div><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active product</label><div className="headerActions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">Save Product</button></div></form></div>}
 {stockRow&&<div className="modalBackdrop"><form className="panel modalCard" onSubmit={adjust}><div className="pageHeader"><div><h2>Adjust Stock</h2><p className="muted">{stockRow.name} · {stockRow.branch_name} · Current: {stockRow.quantity}</p></div><button type="button" className="secondary" onClick={()=>setStockRow(null)}>×</button></div><label>Quantity Change<input type="number" step="0.001" value={stockChange} onChange={e=>setStockChange(e.target.value)} placeholder="e.g. 20 or -2" required/></label><label>Reason / Notes<textarea value={stockNotes} onChange={e=>setStockNotes(e.target.value)} placeholder="Restock, damaged item, correction…"/></label><div className="headerActions"><button type="button" className="secondary" onClick={()=>setStockRow(null)}>Cancel</button><button className="primary">Update Stock</button></div></form></div>}
 </main>
}
