"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";

type Row={id:string;name:string;sku:string|null;barcode:string|null;cost_price:number;selling_price:number;loyalty_points:number;active:boolean;branch_id:string;branch_name:string;quantity:number;low_stock_level:number};
type ProductGroup={product:Row;branches:Row[];totalStock:number;lowStockBranches:number;outOfStockBranches:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const fmt=(n:number)=>Number.isInteger(n)?n.toLocaleString():n.toLocaleString("en-PH",{maximumFractionDigits:3});
export default function ProductsPage(){
 const [rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[editing,setEditing]=useState<Row|null>(null),[showForm,setShowForm]=useState(false),[stockRow,setStockRow]=useState<Row|null>(null),[stockChange,setStockChange]=useState(""),[stockNotes,setStockNotes]=useState(""),[search,setSearch]=useState(""),[branchFilter,setBranchFilter]=useState("all"),[expanded,setExpanded]=useState<string|null>(null);
 const [name,setName]=useState(""),[sku,setSku]=useState(""),[barcode,setBarcode]=useState(""),[cost,setCost]=useState("0"),[price,setPrice]=useState("0"),[points,setPoints]=useState("0"),[active,setActive]=useState(true);
 useEffect(()=>{void load()},[]);
 async function load(){const {data,error}=await supabase.rpc("get_products_inventory");if(error)return setMessage(error.message);setRows((data??[]).map((x:any)=>({...x,cost_price:Number(x.cost_price),selling_price:Number(x.selling_price),loyalty_points:Number(x.loyalty_points),quantity:Number(x.quantity),low_stock_level:Number(x.low_stock_level)})));setMessage("")}
 function openNew(){setEditing(null);setName("");setSku("");setBarcode("");setCost("0");setPrice("0");setPoints("0");setActive(true);setShowForm(true)}
 function openEdit(r:Row){setEditing(r);setName(r.name);setSku(r.sku??"");setBarcode(r.barcode??"");setCost(String(r.cost_price));setPrice(String(r.selling_price));setPoints(String(r.loyalty_points));setActive(r.active);setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("save_product",{p_product_id:editing?.id??null,p_name:name,p_sku:sku||null,p_barcode:barcode||null,p_cost_price:Number(cost)||0,p_selling_price:Number(price)||0,p_loyalty_points:Number(points)||0,p_active:active});if(error)return setMessage(error.message);setShowForm(false);setMessage(editing?"Product updated.":"Product created.");await load()}
 async function adjust(e:FormEvent){e.preventDefault();if(!stockRow)return;const q=Number(stockChange);if(!q)return setMessage("Enter a non-zero stock adjustment.");const {error}=await supabase.rpc("adjust_product_stock",{p_product_id:stockRow.id,p_branch_id:stockRow.branch_id,p_quantity_change:q,p_notes:stockNotes||null});if(error)return setMessage(error.message);setStockRow(null);setStockChange("");setStockNotes("");setMessage("Stock updated.");await load()}
 const branches=useMemo(()=>Array.from(new Map(rows.map(r=>[r.branch_id,r.branch_name])).entries()),[rows]);
 const groups=useMemo<ProductGroup[]>(()=>{const map=new Map<string,Row[]>();for(const r of rows){const a=map.get(r.id)??[];a.push(r);map.set(r.id,a)}return Array.from(map.values()).map(bs=>({product:bs[0],branches:bs,totalStock:bs.reduce((n,b)=>n+b.quantity,0),lowStockBranches:bs.filter(b=>b.quantity>0&&b.quantity<=b.low_stock_level).length,outOfStockBranches:bs.filter(b=>b.quantity<=0).length})).filter(g=>{const q=search.trim().toLowerCase();const matchesSearch=!q||`${g.product.name} ${g.product.sku??""} ${g.product.barcode??""}`.toLowerCase().includes(q);const matchesBranch=branchFilter==="all"||g.branches.some(b=>b.branch_id===branchFilter);return matchesSearch&&matchesBranch}).sort((a,b)=>a.product.name.localeCompare(b.product.name))},[rows,search,branchFilter]);
 const totalProducts=new Set(rows.map(r=>r.id)).size,totalStock=groups.reduce((n,g)=>n+g.totalStock,0),lowStock=groups.filter(g=>g.lowStockBranches>0).length,outOfStock=groups.filter(g=>g.totalStock<=0).length;
 return <main className="workspace catalogPage"><header className="catalogHeader"><div><p className="eyebrow">CATALOG</p><h1>Products & Inventory</h1><p className="muted">Manage retail laundry products, branch stock and selling prices.</p></div><button className="primary catalogPrimary" onClick={openNew}>+ Add Product</button></header>{message&&<p className="notice">{message}</p>}
 <section className="catalogStats"><article><span className="statIcon green">▣</span><div><small>Total Products</small><strong>{totalProducts}</strong><span>Active SKUs</span></div></article><article><span className="statIcon blue">◫</span><div><small>Total Stock</small><strong>{fmt(totalStock)}</strong><span>Across all branches</span></div></article><article><span className="statIcon amber">!</span><div><small>Low Stock Items</small><strong>{lowStock}</strong><span>Reorder soon</span></div></article><article><span className="statIcon red">◇</span><div><small>Out of Stock</small><strong>{outOfStock}</strong><span>Needs attention</span></div></article></section>
 <section className="panel catalogPanel"><div className="catalogToolbar"><div className="catalogSearch"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products by name, SKU or barcode..."/></div><select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)}><option value="all">All Branches</option>{branches.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
 <div className="catalogTableWrap"><table className="catalogTable"><thead><tr><th>Product</th><th>SKU / Barcode</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{groups.map(g=>{const p=g.product,open=expanded===p.id;return <>{<tr key={p.id} className="catalogProductRow"><td><div className="productIdentity"><span className="productGlyph">▣</span><div><strong>{p.name}</strong>{p.loyalty_points>0&&<small>{p.loyalty_points} loyalty pt{p.loyalty_points===1?"":"s"}</small>}</div></div></td><td><strong>{p.sku||"—"}</strong>{p.barcode&&<small>{p.barcode}</small>}</td><td><strong>{peso.format(p.selling_price)}</strong><small>Cost: {peso.format(p.cost_price)}</small></td><td><strong>{fmt(g.totalStock)}</strong><small>{g.branches.length} branch{g.branches.length===1?"":"es"}</small></td><td><span className={`catalogBadge ${p.active?"active":"inactive"}`}>{p.active?"Active":"Inactive"}</span></td><td><div className="rowActions"><button className="iconBtn" onClick={()=>openEdit(p)} title="Edit product">✎</button><button className="iconBtn" onClick={()=>setExpanded(open?null:p.id)} title="Branch inventory">{open?"⌃":"⌄"}</button></div></td></tr>}{open&&<tr className="branchDetailRow"><td colSpan={6}><div className="branchStockCard"><div className="branchStockHead"><span>Branch Stock</span><span>Available</span><span>Low Stock Level</span><span>Status</span><span></span></div>{g.branches.filter(b=>branchFilter==="all"||b.branch_id===branchFilter).map(b=><div className="branchStockLine" key={b.branch_id}><strong>▦ {b.branch_name}</strong><span>{fmt(b.quantity)}</span><span>{fmt(b.low_stock_level)}</span><span><em className={`stockState ${b.quantity<=0?"out":b.quantity<=b.low_stock_level?"low":"in"}`}>{b.quantity<=0?"Out of Stock":b.quantity<=b.low_stock_level?"Low Stock":"In Stock"}</em></span><button className="secondary compact" onClick={()=>setStockRow(b)}>Adjust Stock</button></div>)}</div></td></tr>}</>})}</tbody></table>{!groups.length&&<p className="empty">No products match your filters.</p>}</div></section>
 {showForm&&<div className="modalBackdrop"><form className="panel modalCard catalogModal" onSubmit={save}><div className="modalTitle"><div><p className="eyebrow">PRODUCT</p><h2>{editing?"Edit Product":"Add Product"}</h2></div><button type="button" className="secondary iconBtn" onClick={()=>setShowForm(false)}>×</button></div><div className="gridForm"><label>Product Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label>Barcode<input value={barcode} onChange={e=>setBarcode(e.target.value)}/></label><label>Cost Price<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Selling Price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Loyalty Points<input type="number" min="0" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label></div><label className="checkLabel"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Active product</label><div className="headerActions"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">Save Product</button></div></form></div>}
 {stockRow&&<div className="modalBackdrop"><form className="panel modalCard catalogModal" onSubmit={adjust}><div className="modalTitle"><div><p className="eyebrow">INVENTORY</p><h2>Adjust Stock</h2><p className="muted">{stockRow.name} · {stockRow.branch_name} · Current: {fmt(stockRow.quantity)}</p></div><button type="button" className="secondary iconBtn" onClick={()=>setStockRow(null)}>×</button></div><label>Quantity Change<input type="number" step="0.001" value={stockChange} onChange={e=>setStockChange(e.target.value)} placeholder="e.g. 20 or -2" required/></label><label>Reason / Notes<textarea value={stockNotes} onChange={e=>setStockNotes(e.target.value)} placeholder="Restock, damaged item, correction…"/></label><div className="headerActions"><button type="button" className="secondary" onClick={()=>setStockRow(null)}>Cancel</button><button className="primary">Update Stock</button></div></form></div>}
 </main>
}
