"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";

export default function CustomerLoginPage(){
 const [mode,setMode]=useState<"signin"|"signup">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const returnTo=typeof window!=="undefined"?new URLSearchParams(location.search).get("returnTo")||"/customer":"/customer";
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)void finish()})},[]);
 async function finish(){await supabase.rpc("link_my_customer_portals_by_email");location.replace(returnTo.startsWith("/customer")?returnTo:"/customer")}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");if(mode==="signin"){const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error)return setMessage(error.message);return void finish()}const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),account_type:"customer"}}});setBusy(false);if(error)return setMessage(error.message);if(data.session)return void finish();setMode("signin");setMessage("Account created. Confirm your email, then sign in to continue.")}
 return <main className="customerPortalPage customerLoginPage"><section className="customerPortalHero"><div className="customerPortalLogo">LF</div><p className="eyebrow">MY LABAFLOW</p><h1>{mode==="signin"?"Customer Sign In":"Create Customer Account"}</h1><p>Use one account to view your laundry activity across every participating organization.</p></section><section className="customerPortalCard"><form className="stack" onSubmit={submit}>{mode==="signup"&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="signin"?"current-password":"new-password"} minLength={8} required/></label><button className="primary customerPortalPrimary" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Open My LabaFlow":"Create Customer Account"}</button></form><button className="customerModeSwitch" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"New customer? Create an account":"Already have an account? Sign in"}</button>{message&&<p className="notice">{message}</p>}<small className="customerPrivacy">The same email can securely connect to separate customer profiles from multiple laundry organizations.</small></section></main>
}
