"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "../../../lib/supabase";

type AddonType="pickup"|"delivery"|"pickup_delivery";
type Rate={id:string;addon_type:AddonType;label:string;min_km:number;max_km:number|null;price:number;active:boolean;sort_order:number};
const peso=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"});
const addonLabels:Record<AddonType,string>={pickup:"Pickup",delivery:"Delivery",pickup_delivery:"Pickup + Delivery"};

export default function DeliveryPricingPage(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState("");
 const [rates,setRates]=useState<Rate[]>([]),[editing,setEditing]=useState<string|null>(null),[activeType,setActiveType]=useState<AddonType>("pickup");
 const [form,setForm]=useState({addon_type:"pickup" as AddonType,label:"",min_km:"0",max_km:"",price:"0",active:true,sort_order:"0"});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data,error}=await supabase.from("delivery_distance_rates").select("id,addon_type,label,min_km,max_km,price,active,sort_order").order("addon_type").order("sort_order").order("min_km");if(error)setMessage(error.message);else setRates((data??[]).map((r:any)=>({...r,min_km:Number(r.min_km),max_km:r.max_km==null?null:Number(r.max_km),price:Number(r.price)})))}
 const visibleRates=useMemo(()=>rates.filter(r=>r.addon_type===activeType),[rates,activeType]);
 function edit(r:Rate){setEditing(r.id);setActiveType(r.addon_type);setForm({addon_type:r.addon_type,label:r.label,min_km:String(r.min_km),max_km:r.max_km==null?"":String(r.max_km),price:String(r.price),active:r.active,sort_order:String(r.sort_order)})}
 function reset(type:AddonType=activeType){setEditing(null);setForm({addon_type:type,label:"",min_km:"0",max_km:"",price:"0",active:true,sort_order:"0"})}
 function changeType(type:AddonType){setActiveType(type);reset(type)}
 async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc("upsert_delivery_distance_rate",{p_id:editing,p_addon_type:form.addon_type,p_label:form.label,p_min_km:Number(form.min_km)||0,p_max_km:form.max_km===""?null:Number(form.max_km),p_price:Number(form.price)||0,p_active:form.active,p_sort_order:Number(form.sort_order)||0});if(error)setMessage(error.message);else{setMessage(editing?`${addonLabels[form.addon_type]} distance rate updated.`:`${addonLabels[form.addon_type]} distance rate created.`);const type=form.addon_type;reset(type);await load()}}
 if(checking)return <main className="center"><div className="loader">Loading distance pricing…</div></main>;
 if(!session)return <main className="center"><section className="onboardCard"><h2>Sign in required</h2><button className="primary" onClick={()=>location.href="/organization"}>Organization Administration</button></section></main>;
 return <main className="workspace"><div className="panelHead"><div><p className="eyebrow">PICKUP & DELIVERY</p><h1>Add-on Distance Pricing</h1><p className="muted">Configure Pickup, Delivery, and Pickup + Delivery independently.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/organization"}>Organization Admin</button><button className="primary" onClick={()=>location.href="/"}>LabaFlow</button></div></div>{message&&<p className="notice">{message}</p>}
 <section className="panel"><div className="servicePicker">{(["pickup","delivery","pickup_delivery"] as AddonType[]).map(type=><button type="button" key={type} className={activeType===type?"active":""} onClick={()=>changeType(type)}><strong>{addonLabels[type]}</strong><small>{rates.filter(r=>r.addon_type===type&&r.active).length} active distance bands</small></button>)}</div></section>
 <section className="twoCols"><article className="panel"><h2>{editing?`Edit ${addonLabels[form.addon_type]} Rate`:`New ${addonLabels[activeType]} Rate`}</h2><form onSubmit={save} className="gridForm"><label>Add-on Type<select value={form.addon_type} onChange={e=>{const type=e.target.value as AddonType;setForm({...form,addon_type:type});setActiveType(type)}}><option value="pickup">Pickup</option><option value="delivery">Delivery</option><option value="pickup_delivery">Pickup + Delivery</option></select></label><label>Label<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder="0–3 km" required/></label><label>Minimum km<input type="number" min="0" step="0.1" value={form.min_km} onChange={e=>setForm({...form,min_km:e.target.value})} required/></label><label>Maximum km<input type="number" min="0" step="0.1" value={form.max_km} onChange={e=>setForm({...form,max_km:e.target.value})} placeholder="Leave blank for unlimited"/></label><label>Price<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label>Sort order<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label><span>Availability</span><button type="button" className="miniBtn" onClick={()=>setForm({...form,active:!form.active})}>{form.active?"Active":"Inactive"}</button></label><button className="primary wide">{editing?"Save Changes":"Add Distance Band"}</button>{editing&&<button type="button" className="secondary wide" onClick={()=>reset(activeType)}>Cancel Edit</button>}</form></article>
 <article className="panel"><div className="panelHead"><div><h2>{addonLabels[activeType]} Rates</h2><small>Only these rates appear when {addonLabels[activeType]} is selected on an order.</small></div></div>{visibleRates.length?visibleRates.map(r=><div className="adminRow" key={r.id}><div><strong>{r.label}</strong><small>{r.min_km} km – {r.max_km==null?"No limit":`${r.max_km} km`} · {peso.format(r.price)}</small></div><span className={r.active?"status active":"status inactive"}>{r.active?"Active":"Inactive"}</span><button className="miniBtn" onClick={()=>edit(r)}>Edit</button></div>):<p className="empty">No {addonLabels[activeType]} rates configured yet.</p>}</article></section>
 </main>;
}
