"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";

type FeaturePrice={feature_key:string;display_name:string;monthly_price:number;active:boolean;sort_order:number};
type OrgFeature={feature_key:string;display_name:string;enabled:boolean;monthly_price:number};
type SubscriptionOrg={id:string;name:string;slug:string;active:boolean;created_at:string;trial_started_at:string;trial_ends_at:string;trial_days_remaining:number;in_trial:boolean;status:string;billing_started_at:string|null;next_billing_at:string|null;notes:string|null;monthly_estimate:number;features:OrgFeature[]};
type Context={summary:{organizations:number;trialing:number;billable:number;past_due:number;estimated_mrr:number};feature_prices:FeaturePrice[];organizations:SubscriptionOrg[]};

const money=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:2});
const statusLabel=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function PlatformSubscriptionsPage(){
 const [data,setData]=useState<Context|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState("");
 const [prices,setPrices]=useState<Record<string,string>>({}),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState({status:"trialing",trial_ends_at:"",next_billing_at:"",notes:""});
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);const {data:d,error}=await supabase.rpc("get_platform_subscription_context");if(error){setMessage(error.message);setLoading(false);return}const next=d as Context;setData(next);setPrices(Object.fromEntries((next.feature_prices??[]).map(p=>[p.feature_key,String(p.monthly_price)])));setLoading(false)}
 async function savePrice(feature:FeaturePrice){const value=Number(prices[feature.feature_key]);if(Number.isNaN(value)||value<0){setMessage("Enter a valid non-negative monthly price.");return}const {error}=await supabase.rpc("set_subscription_feature_price",{p_feature_key:feature.feature_key,p_monthly_price:value});setMessage(error?error.message:`${feature.display_name} price updated.`);if(!error)await load()}
 function editOrg(o:SubscriptionOrg){setEditing(o.id);setDraft({status:o.status,trial_ends_at:o.trial_ends_at?o.trial_ends_at.slice(0,10):"",next_billing_at:o.next_billing_at?o.next_billing_at.slice(0,10):"",notes:o.notes??""})}
 async function saveOrg(o:SubscriptionOrg){const trial=draft.trial_ends_at?new Date(`${draft.trial_ends_at}T23:59:59`).toISOString():null;const next=draft.next_billing_at?new Date(`${draft.next_billing_at}T09:00:00`).toISOString():null;const {error}=await supabase.rpc("set_organization_subscription",{p_organization_id:o.id,p_status:draft.status,p_trial_ends_at:trial,p_next_billing_at:next,p_notes:draft.notes||null});setMessage(error?error.message:`${o.name} subscription updated.`);if(!error){setEditing(null);await load()}}
 const rows=useMemo(()=>{const q=search.trim().toLowerCase();return (data?.organizations??[]).filter(o=>!q||o.name.toLowerCase().includes(q)||o.slug.toLowerCase().includes(q)||o.status.toLowerCase().includes(q))},[data,search]);
 if(loading)return <main className="workspace"><p className="eyebrow">PLATFORM ADMINISTRATION</p><h1>Organization Subscriptions</h1><p className="muted">Loading subscription data…</p></main>;
 if(!data)return <main className="workspace"><p className="eyebrow">PLATFORM ADMINISTRATION</p><h1>Organization Subscriptions</h1>{message&&<p className="notice">{message}</p>}</main>;
 return <main className="workspace subscriptionAdminPage">
   <div className="panelHead"><div><p className="eyebrow">PLATFORM ADMINISTRATION</p><h1>Organization Subscriptions</h1><p className="muted">30-day free trials, feature-based pricing, billing readiness, and organization status.</p></div><div className="headerActions"><button className="secondary" onClick={()=>location.href="/admin"}>Back to Tenants</button></div></div>
   {message&&<p className="notice">{message}</p>}
   <section className="stats subscriptionStats"><article><small>ORGANIZATIONS</small><strong>{data.summary.organizations}</strong><span>Total tenants</span></article><article><small>FREE TRIAL</small><strong>{data.summary.trialing}</strong><span>Within 30 days</span></article><article><small>BILLABLE</small><strong>{data.summary.billable}</strong><span>Trial ended</span></article><article><small>EST. MRR</small><strong>{money.format(Number(data.summary.estimated_mrr||0))}</strong><span>Active post-trial</span></article></section>

   <section className="panel"><div className="panelHead"><div><h2>Feature Pricing</h2><p className="muted">Set the monthly price for each billable feature. A feature contributes to the estimate when it is enabled for an organization.</p></div></div><div className="subscriptionPriceGrid">{data.feature_prices.map(f=><div className="subscriptionPriceRow" key={f.feature_key}><div><strong>{f.display_name}</strong><small>{f.feature_key}</small></div><label>Monthly price<input type="number" min="0" step="1" value={prices[f.feature_key]??"0"} onChange={e=>setPrices({...prices,[f.feature_key]:e.target.value})}/></label><button className="miniBtn" onClick={()=>savePrice(f)}>Save</button></div>)}</div></section>

   <section className="panel"><div className="panelHead"><div><h2>Organization Subscription Monitor</h2><p className="muted">Trial dates are initialized from the organization creation date. Billing estimates exclude organizations still in trial.</p></div><div className="scanBar"><input placeholder="Search organization or status" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
   <div className="subscriptionOrgList">{rows.map(o=>{const open=editing===o.id;const enabled=o.features.filter(f=>f.enabled);return <article className={`subscriptionOrgCard ${open?"editing":""}`} key={o.id}><div className="subscriptionOrgHead"><div><strong>{o.name}</strong><small>{o.slug} · created {new Date(o.created_at).toLocaleDateString()}</small></div><span className={`status ${o.status==="active"||o.status==="trialing"?"active":"inactive"}`}>{o.in_trial?`Trial · ${o.trial_days_remaining}d left`:statusLabel(o.status)}</span><div className="subscriptionAmount"><small>EST. MONTHLY</small><b>{money.format(Number(o.monthly_estimate||0))}</b></div><button className="miniBtn" onClick={()=>open?setEditing(null):editOrg(o)}>{open?"Close":"Manage"}</button></div>
   <div className="subscriptionMeta"><span><b>Trial:</b> {new Date(o.trial_started_at).toLocaleDateString()} – {new Date(o.trial_ends_at).toLocaleDateString()}</span><span><b>Features:</b> {enabled.length} enabled</span>{o.next_billing_at&&<span><b>Next billing:</b> {new Date(o.next_billing_at).toLocaleDateString()}</span>}</div>
   <div className="subscriptionFeatureChips">{o.features.map(f=><span key={f.feature_key} className={f.enabled?"enabled":"disabled"}>{f.display_name} · {f.enabled?money.format(Number(f.monthly_price)):"Off"}</span>)}</div>
   {open&&<div className="subscriptionEditor"><div className="gridForm"><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="trialing">Trialing</option><option value="active">Active</option><option value="past_due">Past Due</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select></label><label>Trial ends<input type="date" value={draft.trial_ends_at} onChange={e=>setDraft({...draft,trial_ends_at:e.target.value})}/></label><label>Next billing<input type="date" value={draft.next_billing_at} onChange={e=>setDraft({...draft,next_billing_at:e.target.value})}/></label><label>Notes<input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Optional billing note"/></label></div><div className="branchEditActions"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={()=>saveOrg(o)}>Save Subscription</button></div></div>}
   </article>})}{rows.length===0&&<p className="muted">No organizations match your search.</p>}</div></section>
 </main>
}
